### ISSUE TITLE
writing large SQL queries

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#1]
The best way to write large SQL queries is via CTEs:

```sql
WITH something AS (
  SELECT * FROM some_table
  WHERE column = 1
)
SELECT *
FROM something
WHERE another_column = 2
```

However, when writing CTEs, we lose the ability to run the sub-expressions interactively.

We could add something like this:

```sql
%%sql --name something
SELECT * FROM some_table
WHERE column = 1
```

Then, to re-use the previous query:

```sql
%%sql
SELECT *
-- refer to the previous query
FROM ':something'
WHERE another_column = 2
```

And have the extension automatically expand the expression above to:

```sql
WITH something AS (
  SELECT * FROM some_table
  WHERE column = 1
)
SELECT *
FROM something
WHERE another_column = 2
```

Before submitting to the database.

**Comment by vikjam** [comment]
[Copying Slack thread](https://ploomber-io.slack.com/archives/C03R6FJ7H2R/p1658975447030999) over to this GitHub issue.

Instead of converting a subquery to a CTE for the user, it might be more explicit to have them specify the CTEs in the magics function. For example,

```
%%sql --with something
SELECT *
FROM something
WHERE another_column = 2
```
