### ISSUE TITLE
CI Fix

### ISSUE THREAD

**Issue by neelasha23** [ploomber/jupysql#1001]
CI is breaking: https://github.com/ploomber/jupysql/actions/runs/8421670907/job/23059148267

This is probably due to latest SQLAlchemy 2.0.29

**Comment by edublancas** [comment]
we tempporarily pinned versions: https://github.com/ploomber/jupysql/pull/1000

**Comment by neelasha23** [comment]
DuckdB latest version: https://github.com/ploomber/jupysql/pull/1017/files
