### ISSUE TITLE
Links broken in auto-generated PR text

### ISSUE THREAD

**Issue by laowantong** [ploomber/jupysql#1003]
### What happens?

When I open a PR a boilerplate is generated. The generated links seem to be broken, e.g.:

> 📚 Documentation preview 📚: https://jupysql--1002.org.readthedocs.build/en/1002/

### To Reproduce

Just open a PR.

### OS:

MacOS

### JupySQL Version:

0.10.0

### Full Name:

Aristide Grange

### Affiliation:

Université de Lorraine

**Comment by edublancas** [comment]
it's not broken, that's the documentation preview. building the docs takes a few mins so the URL will work until the build is done

**Comment by laowantong** [comment]
You're right for this link, it is working now. But the other ones yield a 404:

- https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#testing: 404
- https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#linting-formatting: 404
- https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features
- https://ploomber-contributing.readthedocs.io/en/latest/contributing/pr.html#documenting-changes-and-new-features

In the case they need several minutes too, a warning would be a plus.

<img width="861" alt="image" src="https://github.com/ploomber/jupysql/assets/3048819/ce3ccad4-289e-4df3-99e4-ba5fa8a3dc7f">

**Comment by edublancas** [comment]
those were indeed broken, fixed them, thanks

https://github.com/ploomber/jupysql/blob/master/.github/pull_request_template.md
