### ISSUE TITLE
Disable tracking setting not respected

### ISSUE THREAD

**Issue by janrito** [ploomber/jupysql#1013]
### What happens?

I've tried to modify the settings as specified here https://github.com/ploomber/jupysql/issues/664

I've also tried adding `stats_enabled: False` to `pyproject.toml` in `[tool.jupysql.SqlMagic]` and `[tool.jupysql]`, but I still see messages being sent to posthog

### To Reproduce

```
%load_ext sql
```

### OS:

macOS

### JupySQL Version:

 0.10.7

### Full Name:

Alejandro Giacometti

### Affiliation:

Beauhurst

**Comment by edublancas** [comment]
the stats_enabled flag must be set in the  `~/.ploomber/stats/config.yaml` file

or via the `export PLOOMBER_STATS_ENABLED=false` environment variable

[more details here](https://docs.ploomber.io/en/latest/community/user-stats.html#how-to-opt-out)
