### ISSUE TITLE
Issue on page /api/magic-tables-columns.html

### ISSUE THREAD

**Issue by dominijk** [ploomber/jupysql#1014]
Is it possible to use sqlcmd with an alias? I've attempted this as below 

`%sqlcmd one tables` 

and get

```
UsageError: %sqlcmd has no command: 'one'. Valid commands are: tables, columns, test, profile, explore, snippets, connect
```

What's the equivalent of showing tables for a specific alias?

**Comment by edublancas** [comment]
you're getting that error because the first argument to `%sqlcmd` must be a valid command. if you want to show tables you can do `%sqlcmd tables`, this will show the tables in the default schema, if you want a different schema, you can do `%sqlcmd tables --schema schemaname` does this help?

**Comment by dominijk** [comment]
I think the answer is no, i had set an alias as

`%sql sqlite:///one.db --alias one` 

but then wanted to get the table of the alias using

`%sqlcmd tables%` but as my error %sqlcmd doesn't have that command

**Comment by edublancas** [comment]
ok got it. you meant a connection alias

you're right, currently we don't support that. I'll keep this issue open

It should be an easy fix; contributions are welcome!
