### ISSUE TITLE
ADD %%sqlnotice magic

### ISSUE THREAD

**Issue by benabel** [ploomber/jupysql#1019]
Hi, and thanks for this awesome open-source project:)

I'm using postgresql, and I would like to output notice. 

```sql
do 
'declare
   film_count integer;
begin 
   select count(*) into film_count
   from film;

   raise notice ''The number of films: %'', film_count;
end;'
;
```

This can be done using the psycopg connection with poll `method`.

```python
 # Check for notices
    connection.poll()
    while connection.notices:
        notice = connection.notices.pop(0)
        print("Notice: ", notice)
```
With this magic we would output the notices instead of results. Do you think it is worth doing it(my use case is for teaching).

**Comment by edublancas** [comment]
Hi Ben, thanks for your feedback.

Unfortunately, this is pretty niche, and the team doesn't have the bandwidth to work on it. You're welcome to fork the project and add the magic!

**Comment by benabel** [comment]
Thanks for your answer, I've tried to work on implementing this in the `sql.run.run.run_statements` function without a new magic and it seems not so easy to access the notices list. Best for your project.
