### ISSUE TITLE
How to use jupysql with ODBC Driver and DSN?

### ISSUE THREAD

**Issue by bhishanpdl** [ploomber/jupysql#108]
I have a been trying to use the jupysql magic (%sql) with some of the databases I have set up with ODBC and Azure authentication but could not find a way to set up the configuration.

I have:
1.  DSN called 'FUSION'  with ODBC Driver 17 for SQL Server
2. it has Azure Active Directory Integrated authentication and I don't have plain text password and username.

I can query the database using pyodbc like this and it is SUCCESSFUL:

```python
with pyodbc.connect(DSN='FUSION') as conn:
    df = pd.read_sql(query, conn)
```

I tried to do same thing in jupyter notebook in my Windows Laptop,

```python
%load_ext sql

%sql mssql+pyodbc://DSN=FUSION

%sql select top 2 * from mytable;

```

But this does not work, how to work with pyodbc and jupysql?

# Error
```
(pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/14/rvf5)
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])
```

**Comment by edublancas** [comment]
currently, jupysql relies on sqlalchemy for db connections. it seems like sqlalchemy supports [mssql via pyodbc](https://docs.sqlalchemy.org/en/14/dialects/mssql.html).

if you can get the `create_engine` from sqlalchemy up and running, you can pass the engine object to jupysql:

```python
mssql_engine = create_engine(...)
```

```python
%sql mssql_engine
```

```python
%%sql
SELECT * FROM ...
```

let me know if this works!

**Comment by bhishanpdl** [comment]
@edublancas Thanks, I figured out how to work with Windows Authenticaion and Azure Authentication. Here is the snippet, if it helps other programmers:

```python
import urllib

# Look at Driver Name from ODBC data source admin app in your windows computer
# In my case it is odbc driver 17
params = urllib.parse.quote_plus("DRIVER={ODBC Driver 17 for SQL Server};"
                                 "SERVER=XXX;"
                                 "DATABASE=XXX;"
                                 "Trusted_Connection=yes")

engine = sqlalchemy.create_engine("mssql+pyodbc:///?odbc_connect={}".format(params))

query = 'select top 2 * FROM [myschema].[mytable]'

with engine.connect() as conn:
    dfx = pd.read_sql(query,conn)

dfx
```

**Comment by edublancas** [comment]
awesome! thanks for sharing the solution, closing this now!
