### ISSUE TITLE
Feat: Telemetry - Collect database version 

### ISSUE THREAD

**Issue by tonykploomber** [ploomber/jupysql#113]
We need to collect database version https://github.com/ploomber/jupysql/issues/92#issuecomment-1416191480 to get the context that what we should write the integration test for that

**Comment by edublancas** [comment]
we can start with database type (duckdb, postgres, sqlite, etc).

**Comment by edublancas** [comment]
sqlalchemy has a dialect property that returns the database: https://github.com/ploomber/jupysql/blob/1ed7c4a1a7df08aa1612a9479ce9e40982f252f2/src/sql/run.py#L365

perhaps there is also one that returns the version?

**Comment by tonykploomber** [comment]
2 Parts need to be done in this task:

1. Collect the version number from sqlalchemy, I did not see there is an explicit way to return the version number yet...however, we might able to get some meta from logging and see if any version numbers contain
2. Modify the telemetry decorator with (payload = True) in execute function https://github.com/ploomber/jupysql/blob/master/src/sql/magic.py#L194, then inject the collected version into payload

The first one seems challenging since I was spending sometime on how to get the version number, if this is the blocker we can start to collect database type
