### ISSUE TITLE
integration tests improvements

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#116]
follow-ups for https://github.com/ploomber/jupysql/pull/111

1. add SQLite and DuckDB
2. adds test with [autocommit mode turned on](https://github.com/ploomber/jupysql/issues/90#issue-1557844367) - add a xfail flag for postgres since we're expecting this to fail 
3. add [mariaDB](https://firefart.at/post/using-mysql-service-with-github-actions/) - note: this blog post also mentions the ubuntu image already comes with a MySQL database, so perhaps we can simplify the github actions setup, and remove the MySQL service? it might speed things up
4. test postgres meta commands (more info here: https://github.com/ploomber/jupysql/issues/48)

**Comment by tonykploomber** [comment]
For 1,2,4: Add in https://github.com/ploomber/jupysql/pull/117

For 3: I think we still need to declare the service attributes like env (database account / password ), ports and image (it's required attribute in the service part, also we might need to test different database version by setting different matrix later on), I suggest we might still keep it?

**Comment by edublancas** [comment]
>  I suggest we might still keep it?

sure, let's keep it
