### ISSUE TITLE
Output scroll

### ISSUE THREAD

**Issue by neelasha23** [ploomber/jupysql#121]
Scroller can be added to the `Data Preview` section [here](https://jupysql.ploomber.io/en/latest/plot.html)
`:tags: [output_scroll]`

**Comment by edublancas** [comment]
let's see if this works because the [docs](https://jupyterbook.org/en/stable/content/code-outputs.html) only show examples where vertical scrolling is added, and here we need horizontal scrolling.

**Comment by neelasha23** [comment]
had added this in [SQLiteTracker](https://github.com/ploomber/sklearn-evaluation/blob/master/docs/comparison/SQLiteTracker.md)

**Comment by edublancas** [comment]
I see, then it'll work!

**Comment by edublancas** [comment]
this is fixed in jupyter-book 0.14, it'll be fixed once we migrate
