### ISSUE TITLE
detecting when a db driver is missing

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#124]
In https://github.com/ploomber/jupysql/pull/120, we improved the error message displayed when failing to open a connection to a database. However, we're ignoring the error message content and printing a generic message. This leads to a confusing message when the connection string is valid, and the failure is due to another reason.

There are X reasons a connection might fail, but we should at least cover the most common ones. For example, missing a driver ([see this](https://github.com/ploomber/jupysql/pull/120#pullrequestreview-1289598402)). In such case, we should display a more appropriate message like "fix it by installing X package and try again"

I ran a few tests with some sample [URIs](https://docs.sqlalchemy.org/en/20/core/engines.html#postgresql) and the error is always the same `ModuleNotFoundError: No module named 'name'`.

The second case we must cover is when the plugin is missing. For example, if we run:

```
create_engine("duckdb://")
```

with duckdb-engine installed but duckdb *uninstalled*, we get: `ModuleNotFoundError: No module named 'duckdb'` (same as the use case described above).

However, if we uninstall duckdb-engine (regardless of duckdb installed or not), we get:

```
NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:duckdb
```

`NoSuchModuleError` could be either a typo or an actual plugin missing (in this case, the duckdb-engine plugin is missing). So we should keep a list of plugins to distinguish between the two.

**Comment by tonykploomber** [comment]
ACK and working on this

**Comment by tonykploomber** [comment]
@edublancas 
Would you be able to elaborate on this?
> So we should keep a list of plugins to distinguish between the two.

**Comment by edublancas** [comment]
> Would you be able to elaborate on this?

Sure. When we see this error:

```
NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:duckdb
```

We should indicate the user that they're missing a package. In this case, they're missing duckdb. So we should be able to map the error to the missing package (hence keep a list). I'm guessing we can extract the package name from `sqlalchemy.dialects:{package_name}` but maybe it won't match all the time. I think for now, as long as we cover the most popular ones, we're good.
