### ISSUE TITLE
Snowflake - No active connection

### ISSUE THREAD

**Issue by tekumara** [ploomber/jupysql#128]
```python
from snowflake.sqlalchemy import URL
from sqlalchemy import create_engine

url = URL(
    user=...,
    account=...,
    authenticator="externalbrowser",
    warehouse=...,
    database=...
)

engine = create_engine(url)
connection = engine.connect()

c = lambda: connection
```

```
%reload_ext sql

%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False
%config SqlMagic.autopandas = True
%sql --creator c
```

Results in
```
UsageError: No active connection.
...
```

jupysql==0.5.5
snowflake-connector-python==3.0.0
snowflake-sqlalchemy==1.4.6

**Comment by edublancas** [comment]
hi, thanks for reporting this. let me know if [this guide](https://jupysql.ploomber.io/en/latest/howto.html#connect-to-existing-engine) helps you fix the issue

**Comment by tekumara** [comment]
thanks for looking into this!

i tried following the [connect to existing engine](https://jupysql.ploomber.io/en/latest/howto.html#connect-to-existing-engine) instructions and it worked!
