### ISSUE TITLE
Suppress message "Returning data to local variable"

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#13]
Example:

In:
```
%%sql result <<
select col_name
from table_name
```
Out:

Returning data to local variable result
I don't want this message to clutter my output for the document I am producing. It would be useful to have a setting to suppress this message.

Current workaround for this issue (needs to be applied for each cell):
```
%%capture
%%sql result <<
select col_name
from table_name
```

**Comment by edublancas** [comment]
these are things we got from the original repo, and I've seen a bunch of instances where it prints unnecessary stuff. why don't you just delete the message? An options sounds like too much work

**Comment by idomic** [comment]
> Alternatively, we might want to set a global "verbosity" option, which controls all of these messages.

I don't think we're at that stage yet, let's remove the print and call it done.
