### ISSUE TITLE
`%sqlcmd columns` generates error when querying snowflake database

### ISSUE THREAD

**Issue by prakashperiasamy** [ploomber/jupysql#144]
Hi,
Outset, thank you for the great package and an excellent documentation. Kudos to the team!

I tested all the features and found only one issue so far but rather an important utility for me.
Reg: List columns of a table within a database (snowflake in my case)

Tried %sqlcmd magic extension to list the columns of a table in a database/schema in snowflake
General syntax I used:
%sqlcmd columns --table table_name --schema db_name.schema_name
Error message:
ProgrammingError: (snowflake.connector.errors.ProgrammingError) 090105 (22000): Cannot perform SELECT. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.
Background on this error at: https://sqlalche.me/e/14/f405)

Note: the rest of the %sqlcmd features such as get to list of tables works perfect with snowflake

**Comment by edublancas** [comment]
we're using sqlalchemy to inspect the database (instead of manually generating the SQL). looks like snowflake doesn't know which database to use to list the tables.

we don't have a snowflake instance for testing, so I'd appreciate if you can help us debug this.

what happens if you run this with the name of your database:

```
%%sql
USE DATABASE {name}
```

do calls to `%sqlcmd` work then?

**Comment by prakashperiasamy** [comment]
@edublancas 
Thanks a lot for the response and solution. It worked!!!
Would appreciate for posterity, if the documentation can be updated to reflect this. Please let me know if I can be any assistance! 

For posterity/documentation, detailing the steps:
**Step 1:** Inform snowflake which database it should look up using,
`%%sql
USE DATABASE {name}`

**Step 2:** Then make the call to %sqlcmd --columns like,
`%sqlcmd columns --table {tablename} --schema {schemaname}
`

**Comment by edublancas** [comment]
I'm glad it worked! I'd appreciate it if you could help us update the [documentation.](https://jupysql.ploomber.io/en/latest/user-guide/tables-columns.html)

This is the source file: https://github.com/ploomber/jupysql/blob/master/doc/user-guide/tables-columns.md

Maybe a note at the top describing users might have to run `USE DATABASE first`? or perhaps a troubleshooting section at the bottom. What do you think?
