### ISSUE TITLE
--save `name` and --with `name` is creating an error with the CTE name appearing with double quotes in MySQL

### ISSUE THREAD

**Issue by prakashperiasamy** [ploomber/jupysql#145]
when you use --save `name` and reuse it using --with `name`, it's creating a CTE as it should but generating an error. The error message suggests issue is related to the use of double quotes in the identifier (`name`)

Search suggests, MySQL uses backticks (`) for quoting identifiers rather than double quotes ("). Double quotes are used in some other databases like PostgreSQL, but they are not valid in MySQL.

Following this suggestion, if I use backticks with an explicit CTE it works in MySQL and with a double quote it's generating error in the manual CTE creation. Is there a way to fix this? This is a useful feature and would appreciate a fix to give the users change the quoting between backticks, single quote and double quotes. 

Partial error message: 
(pymysql.err.ProgrammingError) (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'"us_fac" AS ..........

**Comment by edublancas** [comment]
Thanks for reporting this!

The problem is that we're hardcoding the `"` here: https://github.com/ploomber/jupysql/blob/bf9a19501d6a282ffa6632e14a4af0f97116b063/src/sql/store.py#L66

we can modify this and pass the current dialect (postgres, duckdb, MySQL) to the function that generates the CTE so it uses `"` or backticks.



@tonykploomber can you work on this? let's also add an integration test of this replicate the behavior before adding new code

**Comment by tonykploomber** [comment]
Gotcha, thanks for the reporting. Will take a look!

**Comment by edublancas** [comment]
this is currently blocked by https://github.com/ploomber/jupysql/issues/145 - fixing it will fix this one as well

**Comment by tonykploomber** [comment]
This will be handled in https://github.com/ploomber/jupysql/pull/164 directly

**Comment by edublancas** [comment]
This will be out in version 0.7 - which we'll release the first week of April!

**Comment by prakashperiasamy** [comment]
@edublancas Thanks a lot for fixing this. Looking forward for the version 0.7.

**Comment by edublancas** [comment]
sure! if you get a chance, please give it a try by installing it from git and let us know if you have any issues:

```
pip uninstall jupysql
pip install git+https://github.com/ploomber/jupysql
```

**Comment by prakashperiasamy** [comment]
Sure thing! Will keep you posted when I have a chance to test it out.
