### ISSUE TITLE
improving boxplot performance

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#151]
opening an issue so we keep track of progress

initial PR is available here: https://github.com/ploomber/jupysql/pull/81

**Comment by tonykploomber** [comment]
Secondary [PR raised ](https://github.com/ploomber/jupysql/pull/152), we have two goals:
1. Fix original SQL statement
2. Add the test_sqlplot into integration testing

**Comment by tonykploomber** [comment]
Close by https://github.com/ploomber/jupysql/pull/152
