### ISSUE TITLE
Issue: Use sqlplot from existing table 

### ISSUE THREAD

**Issue by tonykploomber** [ploomber/jupysql#153]
The sqlplot works fine when we use `duckdb + static csv file` as data source

However, I am having issue to draw plot with `existing table` as data source

Ways to reproduce the issue:
```
%load_ext sql
import pandas as pd
plot_data = pd.DataFrame({"x": range(0, 5), "y": range(5, 10)})

# Use duckdb & load data
%sql duckdb://
%sql --persist plot_data
```

```
# Verify we do have new table gets loaded
%sql SELECT * FROM plot_data
```

```
%sqlplot histogram --table plot --column x
```

Shows error:
```
ProgrammingError: (duckdb.InvalidInputException) Invalid Input Error: Python Object "plot" of type "module" found on line ".../jupysql/src/sql/magic_plot.py:79" not suitable for replacement scans.
Make sure that "plot" is either a pandas.DataFrame, duckdb.DuckDBPyRelation, pyarrow Table, Dataset, RecordBatchReader, or Scanner
[SQL: 
SELECT
    MIN("x"),
    MAX("x")
FROM "plot"]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

**Comment by tonykploomber** [comment]
@edublancas 
Does this happen on your side as well?

**Comment by edublancas** [comment]
you have a typo here:

> %sqlplot histogram --table plot --column x

it should be the name that you passed in the `--persist` argument:

```
%sqlplot histogram --table plot_data --column x
```

But the error is very confusing. The main challenge is that each database driver will have a different error. I'll open an issue to follow up on this, I think this is important.
