### ISSUE TITLE
Proposal: Add --persist-replace argument if there is existing table 

### ISSUE THREAD

**Issue by tonykploomber** [ploomber/jupysql#154]
Originally we have `--persist` argument to [persist the pandas dataframe](https://jupysql.ploomber.io/en/latest/integrations/pandas.html?highlight=--persist#pandas-integration) to the target database connection.

However, if the user runs the same persist command twice, it will show the error message: `ValueError`

Take example, run this cell twice:

```
plot_data = pd.DataFrame({"x": range(0, 5), "y": range(5, 10)})
%sql --persist plot_data
```

It will produce the error message on second call:

```
ValueError: Table 'plot_data' already exists.
If you need help solving this issue, send us a message: https://ploomber.io/community
```

Which is expected, but I think what we could do better is the providing `--persist-replace` argument to do the replace-if-exists action to the table, since user might re-run the whole jupyter file several times, by using this new argument can prevent such error happens in the middle of the execution

**Comment by tonykploomber** [comment]
@idomic @edublancas What do you guys think?

**Comment by edublancas** [comment]
> since user might re-run the whole jupyter file several times, by using this new argument can prevent such error happens in the middle of execution

yeah, makes sense. it's common to re-run notebooks. I'm ok adding it.

although we should not prioritize this, so let's just keep the issue open and tackle it later
