### ISSUE TITLE
*doc updates due to new polars integration - taken via git

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#170]
We should rename our pandas integration section for "pandas/polars" integration and show how to use it: https://jupysql.ploomber.io/en/latest/integrations/pandas.html

also, we can mention the autopandas/autopolars options. note that we should let users know that autopolars was added in version `0.6`

this also needs to be updated to mention this is new in version `0.6`: https://jupysql.ploomber.io/en/latest/api/configuration.html#autopolars

hey, @jorisroovers - if you get a chance, I'd appreciate your help here!

**Comment by jorisroovers** [comment]
Traveling this week, should have some time next week.

**Comment by edublancas** [comment]
awesome!

**Comment by edublancas** [comment]
i fixed this but forgot to close this, so closing it now
