### ISSUE TITLE
Persist pandas df without the index

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#18]
We should create a flag for users to pass so the index isn't included in the df.
Then we should document this flag.
[Reference](https://github.com/catherinedevlin/ipython-sql/issues/205)

**Comment by edublancas** [comment]
This was already implemented: https://github.com/ploomber/jupysql/blob/master/CHANGELOG.md#042-2022-07-26

**Comment by idomic** [comment]
@bhishanpdl
We just updated the docs and released a new version( [0.5.2 changelog](https://github.com/ploomber/jupysql/blob/0.5.2/CHANGELOG.md)).
Make sure to [join our slack](https://ploomber.io/community/) for more info and support
