### ISSUE TITLE
*Invoke setup on Windows fails - taken via git

### ISSUE THREAD

**Issue by yafimvo** [ploomber/jupysql#180]
When running `invoke setup` on windows (powershell) it fails with the following error:

```
'eval' is not recognized as an internal or external command,
operable program or batch file.
```

We can run it via bash on WSL2 but it's linux and not windows.

This can be easily fixed by running the command without `eval` on windows [here](https://github.com/ploomber/jupysql/blob/master/tasks.py#L18)

```
    if platform.system() == "Windows":
        conda_shell_bash_hook_script = 'conda shell.bash hook '
    else:
        conda_shell_bash_hook_script = 'eval "$(conda shell.bash hook)" '
```

cc: @edublancas @idomic

**Comment by ayushmaanshrotriya** [comment]
will look into
