### ISSUE TITLE
summary of jupysql vs ipython-sql

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#183]
we need to improve this [section](https://jupysql.ploomber.io/en/latest/community/vs.html), it should summarise the core differences between jupysql and ipython-sql and link to the relevant parts of the docs for readers to learn more:

this is the list of things we've added:

* plotting API https://jupysql.ploomber.io/en/latest/plot.html
* CTEs https://jupysql.ploomber.io/en/latest/compose.html
* listing tables and columns https://jupysql.ploomber.io/en/latest/user-guide/tables-columns.html
* polars integration https://jupysql.ploomber.io/en/latest/api/configuration.html#autopolars
* better testing (integration tests with PostgreSQL, mariadb, MySQL, sqlite and duckdb)
* Variable Expansion as {{variable}} https://jupysql.ploomber.io/en/latest/user-guide/template.html?highlight=variable#variable-expansion-as-variable

**Comment by tonykploomber** [comment]
Added - Variable Expansion as {{variable}}

**Comment by edublancas** [comment]
> Variable Expansion as {{variable}} : this point already seems to be present?

right, it's already there so no need to add it.

---

So we'll have two sections, we are currently only listing incompatibilities. The other section (which should be at the top) must be the features that we built that ipython-sql does not have. and that'd be the list I shared minus the variable expansion
