### ISSUE TITLE
apply bugfixes

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#188]
there was a recent PR to ipython-sql which fixed a bunch of things: https://github.com/catherinedevlin/ipython-sql/commit/4c4603c2212514464ec042c8db693b2d3053e673

- sqlalchemy 2 support (we are already working on this)
- support for newer versions of prettytable (we already have an issue) https://github.com/ploomber/jupysql/issues/177

However, there are other things that changed but were no clearly documented, the only mention is in the changelog:

> Bugfixes for DSN, `--close`, others

we should check if there's anything important there that we should bring over here

**Comment by neelasha23** [comment]
1. `self.session` renamed to `self.internal_connection` in `src/sql/connection.py`.
2. Added `try..except` block here:
https://github.com/ploomber/jupysql/blob/de483c86bf0288cac2ac74a6e348faaaaed049bc/src/sql/magic.py#L339
3. `config.autolimit` parameter used to limit results in `src/sql/run.py`. PrettyTable style fetched from config.

@edublancas

**Comment by edublancas** [comment]
1. if it's just variable renaming, let's ignore it
2. can you see why they added the try except? I looked at the code but can't understand the motivation
3. autolimit has been around (we already have it), did anything change?
4. Did you see any fixes related to `DSN` or `--close`? those seem important

**Comment by neelasha23** [comment]
1. `DSN`: I see some changes in tests. `test_dsn_config.ini` formatted to add consistent spacing. And `test_connection_from_dsn_section` function in  `test_parse.py` file modified to replace passwords in URL strings to `***`. (dummy config). 
Previously: assert result == "postgres://goesto11:seentheelephant@my.remote.host:5432/pgmain"
Now: assert str(result) == "postgres://goesto11:***@my.remote.host:5432/pgmain"

2. Internal function `_close` renamed to `close` which is already in our code. They have also added a session close which is also present in our code (they have renamed `self.session` to `self.internal_connection` as mentioned above:

IPython fix:
```
cls.connections.pop(str(conn.url))
conn.internal_connection.close()
```

Our code:
```
if descriptor in cls.connections:
    cls.connections.pop(descriptor)
else:
    cls.connections.pop(
        str(conn.metadata.bind.url) if IS_SQLALCHEMY_ONE else str(conn.url)
    )
    conn.session.close()
```

**Comment by neelasha23** [comment]
2. `try..except` : I wasn't sure either. Will look at this again to see if I can understand. I'm having trouble in finding related open/closed issues. 

3. `autolimit` is already there in our code. I don't see any major differences.

IPython fix:

```
if config.autolimit:
        list.__init__(self, sqlaproxy.fetchmany(size=config.autolimit))
else:
        list.__init__(self, sqlaproxy.fetchall())
```

Our code:

```
          if len(self.keys) > 0:
              if isinstance(config.autolimit, int) and config.autolimit > 0:
                  self._results = sqlaproxy.fetchmany(size=config.autolimit)
              else:
                  self._results = sqlaproxy.fetchall()
```

**Comment by edublancas** [comment]
great. are there any changes you think are worth applying?

**Comment by neelasha23** [comment]
We can add the dsn test changes.

**Comment by edublancas** [comment]
ok, let's do it
