### ISSUE TITLE
Feedback to user in case connection hangs

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#19]
We should probably have a mechanism to timeout or detach the process from the kernel to avoid user frustration.
[Reference](https://github.com/catherinedevlin/ipython-sql/issues/204)

**Comment by edublancas** [comment]
closing since the [duckdb](https://github.com/catherinedevlin/ipython-sql/issues/204#issuecomment-1419979142) problem isn't related to JupySQL and the person who reported this in postgres didn't follow up
