### ISSUE TITLE
adding duckdb + excel tutorial

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#194]
duckdb has an extension to read excel files: https://duckdb.org/docs/extensions/overview.html

as we did we JSON files, we should write a tutorial that shows how to query excel files

**Comment by Mause** [comment]
That extension just has some text formatting functions that resemble those in excel, it can't read Excel files

**Comment by edublancas** [comment]
ah, thanks for letting us know and saving us time! 😃
