### ISSUE TITLE
Proposal: Add MSSQL into integration test

### ISSUE THREAD

**Issue by tonykploomber** [ploomber/jupysql#197]
Probably it's better to add Microsoft SQL Server into our integration test flow, since it's very popular too

https://hub.docker.com/_/microsoft-mssql-server
@edublancas What you think

**Comment by edublancas** [comment]
I didn't know there was a docker image, yeah this makes sense!

**Comment by edublancas** [comment]
I added a tutorial here: https://jupysql.ploomber.io/en/latest/integrations/mssql.html

It'll be useful when tackling this issue as I solved quite some issues to get it working. The most relevant is that there is another Docker image for SQL edge (which looks like a trimmed down version of SQL server), so if the one that @tonykploomber shared in the top comment doesn't work, we can try that one

**Comment by tonykploomber** [comment]
I think adding Oracle is a good idea
