### ISSUE TITLE
Improving `--save/--with` guide and documentation

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#201]
It's a bit unclear from [this guide](https://jupysql.ploomber.io/en/latest/compose.html?highlight=--with#organizing-large-queries) how to use the features and what are the limitations.

For instance a user can try using it as a stored procedure.

i.e:

```
%%sql --save query-tbl --no-execute
select * from tbl;
```

And
```
%sql --with query-tbl
```

The error is also not too clear here.

**Comment by edublancas** [comment]
this feature will be deprecated since we're now inferring the dependencies automatically
