### ISSUE TITLE
deprecation warning incorrectly displayed

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#203]
a warning is displayed even though I'm not using any templated SQL code:

![Screenshot 2023-03-03 at 5 41 40 p m](https://user-images.githubusercontent.com/989250/222855508-d27c3dbc-6558-4dea-bc65-df9bf0a84d5f.png)

**Comment by tonykploomber** [comment]
The root cause was [the line](https://github.com/tonykploomber/jupysql/blob/master/src/sql/command.py#L111)

```has_SQLAlchemy_var_expand = re.search("(?<!://):[^/]+", line) or ":" in cell```

This was meant for detecting `SELECT :variable from table` which is handled by SQLAlchemy engine. Need to better place to handle this, will add the test case to cover it
