### ISSUE TITLE
improve quickstart

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#205]
many people are unfamiliar with magics, so we should describe:

- what Jupyter magics are
- line magics vs cell magics
- %sql vs %%sql

some resources:

https://ipython.readthedocs.io/en/stable/interactive/magics.html
https://jakevdp.github.io/PythonDataScienceHandbook/01.03-magic-commands.html

this is the file that needs editing: https://github.com/ploomber/jupysql/blob/master/doc/quick-start.md

**Comment by chuwpeng123** [comment]
Hi this is Chuwei.

**Comment by edublancas** [comment]
assigned!
