### ISSUE TITLE
validating input parameter when initializing connection

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#21]
When starting a new session, users can connect to a db like this:

```python
%sql connection_string
```

However, the `connection_string` is not validated, and if I pass an invalid object:

```python
%sql "not a connection string"
```

```python
%sql 100
```

The following message shows:

```
Environment variable $DATABASE_URL not set, and no connect string given.
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])
```

This is confusing as it doesn't tell me my input is wrong. It says "no connection string given", but that's incorrect.

**Comment by mehtamohit013** [comment]
AC Criteria:
- Check the validity of connection string for different databases for `SQLAlchemy` backend

**Comment by mehtamohit013** [comment]
@edublancas @idomic 
When running `%sql 100` or `%sql "not a connection string"`, I get:

```
UsageError: No active connection.

To fix it:

Pass a valid connection string:
    Example: %sql postgresql://username:password@hostname/dbname

OR

Set the environment variable $DATABASE_URL

For technical support: https://ploomber.io/community
Documentation: https://jupysql.ploomber.io/en/latest/connecting.html
```

What are the additional changes you want in the error message?

**Comment by edublancas** [comment]
> Probably output that the connection string isn't valid instead of No active connection?

We currently show the "no active connection" always because we don't know if what the user passed is a connection string, some SQL code, an existing or some random stuff. So there's some room for improvement.

But it's also unclear what heuristics we can use without throwing false positives, so some research needs to be done here: collect some input/error pairs, and determine what can be improved.

**Comment by mehtamohit013** [comment]
@idomic @edublancas 
> We currently show the "no active connection" always because we don't know if what the user passed is a connection string, some SQL code, an existing or some random stuff. So there's some room for improvement.

Do you want a parser for sqlalchemy URLs like in case of `MySQL` you get the connection string `"mysql+mysqldb://user:password@127.0.0.1:3306/db"`, so if wrong string is based but contains `MySQL` we can output the error: `Invalid String for MySQL. Please check the SQL Alchemy URL`
