### ISSUE TITLE
`%sqlcmd` table and column commands don't work on `parquet` files

### ISSUE THREAD

**Issue by yafimvo** [ploomber/jupysql#221]
```python
%load_ext sql
%sql duckdb://
```

```python
from pathlib import Path
from urllib.request import urlretrieve

url = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.parquet"

if not Path("yellow_tripdata_2021-01.parquet").is_file():
    urlretrieve(url, "yellow_tripdata_2021-01.parquet")
```

There are no tables to list
```python
%sqlcmd tables
```

`columns` returns `NoSuchTableError`
```python
%sqlcmd columns --table "yellow_tripdata_2021-01.parquet"
```

This might be fixed by running SQL commands with `raw_run`

**Comment by edublancas** [comment]
Good point. This is because we need to register the data as a table (using CREATE TABLE); then it'll work (see the copy of my Jupyter session below). I think we can add this to the DuckDB integration section.



---

```python
! curl -O https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv
```




**Console output (1/1):**

```txt
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13478  100 13478    0     0  74034      0 --:--:-- --:--:-- --:--:-- 76579
```



```python
%load_ext sql
```

```python
%sql duckdb://
```

```python
%%sql
select * from penguins.csv limit 3
```




**Console output (1/2):**

```txt
*  duckdb://
Done.
```

**Console output (2/2):**

<table>
    <thead>
        <tr>
            <th>species</th>
            <th>island</th>
            <th>bill_length_mm</th>
            <th>bill_depth_mm</th>
            <th>flipper_length_mm</th>
            <th>body_mass_g</th>
            <th>sex</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Adelie</td>
            <td>Torgersen</td>
            <td>39.1</td>
            <td>18.7</td>
            <td>181</td>
            <td>3750</td>
            <td>MALE</td>
        </tr>
        <tr>
            <td>Adelie</td>
            <td>Torgersen</td>
            <td>39.5</td>
            <td>17.4</td>
            <td>186</td>
            <td>3800</td>
            <td>FEMALE</td>
        </tr>
        <tr>
            <td>Adelie</td>
            <td>Torgersen</td>
            <td>40.3</td>
            <td>18.0</td>
            <td>195</td>
            <td>3250</td>
            <td>FEMALE</td>
        </tr>
    </tbody>
</table>


```python
%%sql
CREATE TABLE penguins AS SELECT * FROM penguins.csv
```




**Console output (1/2):**

```txt
*  duckdb://
Done.
```

**Console output (2/2):**

<table>
    <thead>
        <tr>
            <th>Count</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>344</td>
        </tr>
    </tbody>
</table>


```python
%%sql
select * from penguins limit 3
```




**Console output (1/2):**

```txt
*  duckdb://
Done.
```

**Console output (2/2):**

<table>
    <thead>
        <tr>
            <th>species</th>
            <th>island</th>
            <th>bill_length_mm</th>
            <th>bill_depth_mm</th>
            <th>flipper_length_mm</th>
            <th>body_mass_g</th>
            <th>sex</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Adelie</td>
            <td>Torgersen</td>
            <td>39.1</td>
            <td>18.7</td>
            <td>181</td>
            <td>3750</td>
            <td>MALE</td>
        </tr>
        <tr>
            <td>Adelie</td>
            <td>Torgersen</td>
            <td>39.5</td>
            <td>17.4</td>
            <td>186</td>
            <td>3800</td>
            <td>FEMALE</td>
        </tr>
        <tr>
            <td>Adelie</td>
            <td>Torgersen</td>
            <td>40.3</td>
            <td>18.0</td>
            <td>195</td>
            <td>3250</td>
            <td>FEMALE</td>
        </tr>
    </tbody>
</table>


```python
%sqlcmd tables
```




**Console output (1/1):**

<table>
    <thead>
        <tr>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>penguins</td>
        </tr>
    </tbody>
</table>


```python
%sqlcmd columns -t penguins
```




**Console output (1/1):**

<table>
    <thead>
        <tr>
            <th>name</th>
            <th>type</th>
            <th>nullable</th>
            <th>default</th>
            <th>autoincrement</th>
            <th>comment</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>species</td>
            <td>VARCHAR</td>
            <td>True</td>
            <td>None</td>
            <td>False</td>
            <td>None</td>
        </tr>
        <tr>
            <td>island</td>
            <td>VARCHAR</td>
            <td>True</td>
            <td>None</td>
            <td>False</td>
            <td>None</td>
        </tr>
        <tr>
            <td>bill_length_mm</td>
            <td>DOUBLE_PRECISION</td>
            <td>True</td>
            <td>None</td>
            <td>False</td>
            <td>None</td>
        </tr>
        <tr>
            <td>bill_depth_mm</td>
            <td>DOUBLE_PRECISION</td>
            <td>True</td>
            <td>None</td>
            <td>False</td>
            <td>None</td>
        </tr>
        <tr>
            <td>flipper_length_mm</td>
            <td>BIGINT</td>
            <td>True</td>
            <td>None</td>
            <td>False</td>
            <td>None</td>
        </tr>
        <tr>
            <td>body_mass_g</td>
            <td>BIGINT</td>
            <td>True</td>
            <td>None</td>
            <td>False</td>
            <td>None</td>
        </tr>
        <tr>
            <td>sex</td>
            <td>VARCHAR</td>
            <td>True</td>
            <td>None</td>
            <td>False</td>
            <td>None</td>
        </tr>
    </tbody>
</table>

**Comment by jpjon** [comment]
Hello this is Jonathan. Please assign me to this issue. Thanks!
