### ISSUE TITLE
Overriding sqlalchemy error handling

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#229]
When running Jupysql with a faulty query for instance (I believe that's the main place it happens), the user is left with a cryptic error message, I believe there are 2 improvements we can take.

1. Show a detailed error message - perhaps even show where the query faulted (analyze it on the fly).
2. Presenting the community link so users know they can get help and follow up on the next step.

<img width="422" alt="Screen Shot 2023-03-12 at 10 38 54 AM" src="https://user-images.githubusercontent.com/11596985/224552204-d358be08-e8b6-4504-83e7-960533d28592.png">

**Comment by edublancas** [comment]
Yeah, I agree this is something important we can fix. The challenge is that each db driver raises different types of errors. But at least we can detect the most common ones for the most popular dbs
