### ISSUE TITLE
CD for jupysql

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#23]
We need to add a [git actions step](https://github.com/marketplace/actions/pypi-publish) to allow publishing after successful CI runs.

**Comment by idomic** [comment]
We can wait until it's well speced.

**Comment by idomic** [comment]
Missing: on what do we run the CD (/src) tagging, changelog/release notes, minor vs major versioning (API breaking changes) - how do we track this? Maybe tags for major/not major, ignore tag.

**Comment by idomic** [comment]
@edublancas what's missing from the spec here?

What do we run the CD on? Only commits that happened to /src at the first stage (ignoring tests/docs).
Tagging - it should tag the release versions on git every time. There are also the versions themselves, which still is an open issue, we can upgrade on the minor, and have a tag for major version updates (X.X.0), mainly for API-breaking changes. We can also take a manual approach of adding tags for major/not major or an to ignore tag (least favorable IMO).
- changelog/release notes - each dev should write the changelog entry for bug fixes/new features. It's also our reviewer's responsibility. Additionally, we can have a shell check as part of our ci to fail/warn if there's an update to the source but not to changelog.

**Comment by edublancas** [comment]
I have a draft with the spec. I'll open a PR soon.

**Comment by idomic** [comment]
Ok so @yafimvo this will be just about reviewing, not implementation.

**Comment by edublancas** [comment]
opened a [PR](https://github.com/ploomber/contributing/pull/14/files), once this is approved. we can work on implementing it.

**Comment by edublancas** [comment]
adding some more details:

in our current (manual process), we use [pkgmt](https://github.com/ploomber/pkgmt) to release new versions. this is a two-step process.

```
pkgmt version
```

this command changes the dev version (e.g., 1.2.0dev -> 1.2.0), creates a new commit, creates a tag and pushes it to the repository.

Then, once the CI for the commit created in the step above passes, we run:

```
pkgmt release {version}
```

In our case, we'd execute:

```
pkgmt release 1.2.0
```

## testing with the dummy package

I've created a dummy package that we can use to test this:

https://github.com/ploomber/dummy


## notes

- in this CD script, we need to pass `pkgmt version --yes` so it doesn't ask for confirmation
- currently `pkgmt release` needs one argument (the version to release), I think we should modify it so it automatically looks at existing tags and releases it, e.g.: `pkgt release` should release the latest tag.
- note that `pkgmt` might change the released version if it's incomplete. e.g., if the changelog says `1.2dev`, pkgmt will complete the missing zero and version as `1.2.0`
- `pkgmt release` uploads to the PyPI test server by default, to upload to production PyPI, you need `--production`

**Comment by edublancas** [comment]
> We need to add a [git actions step](https://github.com/marketplace/actions/pypi-publish) to allow publishing after successful CI runs.

@idomic we shouldn't use that github action, since we already implemented the pushing to PyPI logic in pkgmt

**Comment by edublancas** [comment]
closing since we're tracking progress here: https://github.com/ploomber/dummy/issues/36
