### ISSUE TITLE
customizing results output

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#230]
from a user on Slack:

> As a data analyst doing ad-hoc SQL analysis I often times find myself creating SQL results in a notebook which contain URL values for a given column -- a bit of a "df as a dashboard" .
> Is there any easy way to enable these URLs in the result set to be clickable?  Maybe via a SqlMagic config?
> Currently I have a bit of a hack to do this by (1) returning the query results to a df, then (2) calling method to style it if it looks like a URI (see this notebook), but a simpler way seems desirable and a feature others may find useful as well.

https://gist.github.com/gregrahn/2a1196d6a6588a7c04c52b5970895937
https://github.com/softhints/Pandas-Tutorials/blob/master/styling/create-clickable-link-pandas-dataframe-jupyterlab.ipynb

I think we have two options: either we provide a style API like pandas do or we parse the results automatically.

I think it's fine to parse them automatically; at the beginning, I was concerned about performance but users only display small tables in the results. Alternatively, we might setup a threshold: if the table has more than X cells, do not apply the styling.

**Comment by AnirudhVIyer** [comment]
Good issue

**Comment by edublancas** [comment]
the feature should be implemented for our ResultSet object: https://github.com/ploomber/jupysql/blob/e52dda065a109bf7714c1b69c8fcaff1233742a5/src/sql/run.py#L98
