### ISSUE TITLE
compatibility with SQLAlchemy 2

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#24]
Connect throws

MetaData.init() got an unexpected keyword argument 'bind'

For now specifying SQLAlchemy version better, but should actually fix

**Comment by yafimvo** [comment]
I tried to play with SQLAlchemy 2, ipython-sql, and jupysql. Besides the [incompatibility of ipython-sql with SQLAlchemy 2](https://github.com/catherinedevlin/ipython-sql/commit/cc4633cd3367cc0eecc48e48c9430c988cd11eac), duckdb-engine also requires sqlalchemy<2.0.0.

[Added PR with version fix](https://github.com/ploomber/jupysql/pull/55)

**Comment by idomic** [comment]
I think given that it's [currently a beta](https://www.sqlalchemy.org/blog/2022/12/28/sqlalchemy-2.0.0rc1-released/), limiting the version is enough until there's a stable release and then we can worry on this. We can close the issue and once a user reopens this we can tackle it. @edublancas fyi
