### ISSUE TITLE
add deprecation warning when argument passed to `--with` contains hyphens (`-`)

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#245]
in #164 we no longer allow hyphens passed to `--with`, instead, users should use underscores.

to give them time to update their code, we should throw a FutureWarning whenever they pass an argument that contains hyphens and tell them to use underscores instead

**Comment by edublancas** [comment]
cc @tonykploomber

**Comment by Palashio** [comment]
Is this for all places where the `with` parameter is used? In `SqlPlotMagic`, `RenderMagic`, and `SqlMagic`.

**Comment by edublancas** [comment]
they all use the same underlying mechanism so it's better to add it there https://github.com/ploomber/jupysql/blob/master/src/sql/store.py

**Comment by tonykploomber** [comment]
@Palashio 
For the Futurewarning, you can refer how we did to the `var expand` 
Code: https://github.com/ploomber/jupysql/pull/137/files#diff-769097f5e36be57ddec10c78df0900db8c1e254f5485bc94367aa7fcb07991c5R114
Test: https://github.com/ploomber/jupysql/pull/137/files#diff-9aed7fd5fd841447ef03fafe06253743be39cb1363c953da27c5e04350191794R173

**Comment by tonykploomber** [comment]
@edublancas 
Gotcha, since we are giving user some time to update their code. 
I guess the timeline will be like this:
Merge #245 -> Wait for 1 month -> Merge #164 ?

Also, in #164, we should show some error message when the argument passed to --with contains hyphens (-)

**Comment by edublancas** [comment]
> Merge https://github.com/ploomber/jupysql/issues/245 -> Wait for 1 month -> Merge https://github.com/ploomber/jupysql/pull/164 ?

as soon as #245 if fixed, I'll make a release. Then we merge #164 but wait for two weeks to make a release

> Also, in https://github.com/ploomber/jupysql/pull/164, we should show some error message when the argument passed to --with contains hyphens (-)

yes, please update it so we throw an error, ensure that the error suggests how to fix it (by replacing - with _)
