### ISSUE TITLE
opengraph improvements

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#253]
to improve SEO, we recently added html_meta to the sections in our docs. [example](https://raw.githubusercontent.com/ploomber/jupysql/master/doc/integrations/duckdb.md)

However, we are not displaying any [images](https://www.opengraph.xyz/url/https%3A%2F%2Fjupysql.ploomber.io%2Fen%2Flatest%2Fintegrations%2Fduckdb.html).

![image](https://user-images.githubusercontent.com/989250/225402574-7683d279-d722-4d87-8003-ee5057e10d4c.png)

The other weird thing is that it says "Python documentation" instead of "JupySQL documentation"

There are a few things to do here:

- [ ] investigate how to modify the Python documentation so it shows JupySQL documentation
- [ ] investigate how to display an image (most likely, we need to modify the html_meta)
- [ ] check if it's possible to display one image by default (so we are not missing anything, we can later customize them)
- [ ] create a sample image, you can use this [template](https://github.com/ploomber/contributing/blob/main/templates/opengraph.drawio) - note that this requires the [draw.io app](https://www.diagrams.net/)
- [ ] add it to a sample article, let's start with [duckdb's one](https://github.com/ploomber/jupysql/blob/master/doc/integrations/duckdb.md)

**Comment by edublancas** [comment]
note: we use jupyter-book so we might wanna check out their docs

**Comment by lfunderburk** [comment]
Thank you Eduardo
Taking a peek

**Comment by lfunderburk** [comment]
Hello @edublancas 

Tackled the following items:

1. investigate how to display an image (most likely, we need to modify the html_meta)
2. check if it's possible to display one image by default (so we are not missing anything, we can later customize them)
3. create a sample image, you can use this 
4. add it to a sample article, let's start with [duckdb's one](https://github.com/ploomber/jupysql/blob/master/doc/integrations/duckdb.md)

Solutions explored:

Added a property=og:image: option to the `html_meta`

```
myst:
  html_meta:
    description lang=en: Use DuckDB from Jupyter using JupySQL
    keywords: jupyter, sql, jupysql, duckdb, plotting
    property=og:locale: en_US
    property=og:image: ./img/html-meta-template.png
```

Created a template in both .drawio and .jpeg formats and added it to the DuckDB tutorial. PR here https://github.com/ploomber/jupysql/pull/398

**Comment by lfunderburk** [comment]
For this item
 investigate how to modify the Python documentation so it shows JupySQL documentation
 
 I am not sure what you mean as I couldn't find in the rendered doc the phrase "Python documentation". Do you mean find a way to link our docs with the official Python docs? or did you mean something else?

**Comment by edublancas** [comment]
> I am not sure what you mean as I couldn't find in the rendered doc the phrase "Python documentation". Do you mean find a way to link our docs with the official Python docs? or did you mean something else?

The title in the browser tab says: `{section name} - Python documentation`

![image](https://user-images.githubusercontent.com/989250/231587623-605b14c5-268c-418e-a34e-025e61683eed.png)

**Comment by edublancas** [comment]
@lfunderburk: I assigned this to @anupam-tiwari 

@anupam-tiwari: please go over the existing issue to get the context, there is also a related (unfinished PR): https://github.com/ploomber/jupysql/pull/398

**Comment by edublancas** [comment]
any updates here? @anupam-tiwari

**Comment by anupam-tiwari** [comment]
Apologies for missing this one. I'm working on it right now!

**Comment by edublancas** [comment]
great!
