### ISSUE TITLE
Mysql connection lost

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#265]
In some scenarios when running with the MySQL driver, especially when running a long big query, the connection can get lost while executing the query.

Reference:
```
(pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')(Background on this error at: https://sqlalche.me/e/14/e3q8)
--


<br class="Apple-interchange-newline">
```

**Comment by edublancas** [comment]
this can happen with any client-server database; I did a quick [search](https://stackoverflow.com/q/35640726/709975) and it seems like this parameter is db-dependent, what we can do is set a config setting, example:

```
%config SqlMagic.timeout_minutes = 30
```

And under the hood, pass the appropriate parameter name

**Comment by edublancas** [comment]
all drivers have a default value, that can be the default

**Comment by gtduncan** [comment]
My plan for this feature is to add a `timeout_minutes` config setting to `%config` that allows a user to pass in a `float` time limit in minutes for database queries. The default will be `30` and will be added as `{'timeout': timeout_value*60}` (value must be in seconds) to the dict of connection arguments to pass to the SQL driver under the hood. I will then add tests and ensure this setting is made clear in the documentation in `configuration.md`

**Comment by edublancas** [comment]
also, since this is DB-dependent, we can start with some databases.

For testing, I guess we can set a pretty short timeout and see if the db is effectively disconnected.
