### ISSUE TITLE
fixes to `%sqlcmd test`

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#275]
the `%sqlcmd test` needs improvements in terms of docs and user experience

notebook for context: [sql-test.ipynb.zip](https://github.com/ploomber/jupysql/files/11023256/sql-test.ipynb.zip)

**Comment by edublancas** [comment]
notes: we're missing the changelog entry and also the notice in the docs that states in which version this was added

**Comment by edublancas** [comment]
and this feature deserves its own tutorial, instead of embedding if in the listing tables/columns one

**Comment by gtduncan** [comment]
Just to clarify, the contents of that `.ipynb` should be put/paraphrased in the standalone `%sqlcmd` tutorial right?

**Comment by edublancas** [comment]
so there are two things here: one is fixing the logic in `%sqlcmd test` according to the comments in the attached notebook.

Once that's done, we need to write a tutorial showing how to use it.
