### ISSUE TITLE
vendor agnostic ggplot code 

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#278]
We're closer to adding the new ggplot plotting API (https://github.com/ploomber/jupysql/pull/164); however, the SQL queries are hardcoded and they might not work with particular SQL dialects. In #164 we incorporated sqlglot, which allows us to vendor-agnostic SQL queries so the next iteration for the ggplot feature is to use sqlglot to generate the SQL queries.

Note that this is blocked by https://github.com/ploomber/jupysql/issues/277 since we're missing documentation on how to use sqlglot

**Comment by yafimvo** [comment]
I just want to make sure I understand it correctly.

`ggplot API` draws charts with the [histogram ](https://github.com/ploomber/jupysql/blob/8ce3334182733145dbea6ece9e3d59e30237788c/src/sql/plot.py#L328) and [boxplot](https://github.com/ploomber/jupysql/blob/8ce3334182733145dbea6ece9e3d59e30237788c/src/sql/plot.py#L213) functions.

These functions are running SQL.

Acceptance criteria:
1. Build the same SQL queries with `sqlglot`.
2. Current tests should pass (boxplot, histogram, and ggplot)

@edublancas

**Comment by edublancas** [comment]
you're right, we're already using transpile.

the first step is to understand for which databases the boxplot and histogram work and for which ones it doesn't. this is because transpiling isn't a perfect process so we might need to do some manual fixes: e.g., skip the transpiling process and just write another query. another reason could be that a database doesn't support a function that we need for creating the plot e.g., computing percentiles. in such case, there's nothing we can do.

I'm assuming we have some missing tests in our integration testing suite. so first we need to add those tests, and find out where we're failing (once we know, we can mark the tests with xfail)

then, we can decide which ones we fix and which ones we don't. e.g., we should prioritize databases that are heavily used and we're ok not supporting some functionality for some databases.

we should also update the compatibility table: https://jupysql.ploomber.io/en/latest/integrations/compatibility.html#postgresql
