### ISSUE TITLE
fixing CI on windows

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#28]
When adding windows to the CI, it fails. We have to fix the tests, often it's just incompatibilities in the tests, but there might be cases where there's an actual incompatibility.

**Comment by edublancas** [comment]
most test cases are passing, there just three that fail on windows: https://github.com/ploomber/jupysql/blob/cf023ed8070a84f1d1bb82bf7253ec9f655783b5/src/tests/test_magic.py#L158

**Comment by edublancas** [comment]
makes sense. I'll unassign it

**Comment by yafimvo** [comment]
Tested it on windows.

When we are passing double quoted args on windows it strips them out and it fails on `json.loads` with `JSONDecodeError` :

e.g :
```
%sql --connection_arguments {"timeout":10} sqlite:///:memory:
```

will try to parse this string:
```
{timeout:10}
```

But it expects to parse the following string:
```
{"timeout":10}
```

Error:
```
JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

So, to fix the test on windows we need to add another `\`. something like this: 

```
def test_connection_args_in_connection(ip, capsys):
    ip.run_cell('%sql --connection_arguments {\\"timeout\\":10} sqlite:///:memory:')
    result = ip.run_cell("%sql --connections")
    assert "timeout" in result.result["sqlite:///:memory:"].connect_args
```
Note - it won't work on linux.

I tried to run it also via jupyter notebook. 
To make it work on jupyter notebook we should use only one `\`.

```
%sql --connection_arguments {\"timeout\":10} sqlite:///:memory:
```

@edublancas 
How do we want to handle it? we can keep skipping the current tests on windows, add another test for windows, and document it.

We can add a better error handler for `JSONDecodeError`.

Another possible solution on windows is to use regex and modify the string but I'm not sure how reliable it will be.

**Comment by edublancas** [comment]
thanks for digging into this, it's weird that windows behaves in this way.

does this also break anywhere?

```
%sql --connection_arguments '{"timeout":10}' sqlite:///:memory:
```

as a first step, I think let's remove the decorators I added to the failing tests so we verify that the error that you've found is the same as in the CI. if we are unable to find a solution that works across all OSs I think we can add an if statement inside the test so the input changes depending on it

if that's the case, we should update the docs to hint to the user

**Comment by edublancas** [comment]
this is proving a bit challenging to reproduce (see #179)

I don't think many people are using this and our new feature to pass existing engines is a better way to pass arguments anyway: https://jupysql.ploomber.io/en/latest/connecting.html?highlight=existing%20engine#using-an-existing-sqlalchemy-engine-engine

so I'm closing this
