### ISSUE TITLE
curly brackets are converted to round brackets and lead to parser error in DuckDB

### ISSUE THREAD

**Issue by Dtenwolde** [ploomber/jupysql#292]
Hi there, 

Thanks for this nice project!
I am working on a DuckDB extension that introduces some new SQL syntax for path-finding so queries like these are accepted (the path-finding part is: {1,4}): 
```sql
    SELECT pg.firstname, pg.id, count(pg.reachable_people)
    FROM GRAPH_TABLE (social_network,
    MATCH (p:Person)-[k:Person_knows_Person]->{1,4}(p2:person)
    WHERE p.firstname = 'Bob'
    COLUMNS (p.firstName as firstname, p.id as id, p2.firstName as reachable_people) 
    ) pg
    GROUP BY ALL
```

I was using your package which works for other queries. But in the query example above, it fails because of a parser error in DuckDB. This is because when DuckDB receives the query, the {1,4} has already been converted to (1,4), which in this case does not mean the same thing and hence leads to a parser error. 

I am unsure whether this is an issue related to jupysql or DuckDB. The query does work in DuckDB using their python API (`duckdb.sql(f"{query}")`). Also, I don't know of a SQL query outside of my extension in which the () and {} are supposed to be interpreted differently, but I'd be happy to provide you with a minimal reproducible example if you believe this to be a jupysql issue and not a DuckDB issue :)

**Comment by edublancas** [comment]
thanks for your feedback!

I believe this is related to some old behavior we inherited from ipython-sql (the project we forked) since it allowed the `{variable}` format for variable substitution, the good news is that we already fixed it.

Ran a quick test with the current stable version and got this error:

```
*  duckdb://
(duckdb.ParserException) Parser Error: syntax error at or near ":"
LINE 3: MATCH (p:Person)-[k:Person_knows_Person]->(1, 4)(p2:person)
WHERE p.firstname = 'Bob'
COLUMNS (p.firstName as firstname, p.id as id, p2.firstName as reachable_people) 
) pg
GROUP BY ALL...
                ^
[SQL: SELECT pg.firstname, pg.id, count(pg.reachable_people)
FROM GRAPH_TABLE (social_network,
MATCH (p:Person)-[k:Person_knows_Person]->(1, 4)(p2:person)
WHERE p.firstname = 'Bob'
COLUMNS (p.firstName as firstname, p.id as id, p2.firstName as reachable_people) 
) pg
GROUP BY ALL]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

Which confirms what you found: {1,4} became (1,4)

Then, I tried with the latest version from github and got a different error:

```
*  duckdb://
(duckdb.ParserException) Parser Error: syntax error at or near ":"
LINE 3: MATCH (p:Person)-[k:Person_knows_Person]->{1,4}(p2:person)
WHERE p.firstname = 'Bob'
COLUMNS (p.firstName as firstname, p.id as id, p2.firstName as reachable_people) 
) pg
GROUP BY ALL...
                ^
[SQL: SELECT pg.firstname, pg.id, count(pg.reachable_people)
FROM GRAPH_TABLE (social_network,
MATCH (p:Person)-[k:Person_knows_Person]->{1,4}(p2:person)
WHERE p.firstname = 'Bob'
COLUMNS (p.firstName as firstname, p.id as id, p2.firstName as reachable_people) 
) pg
GROUP BY ALL]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

The `{1, 4}` isn't changed anymore but we still have a syntax error.

Can you try this with the development version and let me know if there are any other problems?

```
pip uninstall jupysql
pip install git+https://github.com/ploomber/jupysql
```

**Comment by Dtenwolde** [comment]
Indeed it now works with the latest version! I should have probably tried that before opening an issue, apologies for that! I looked through your issues but was unable to find anything related. Thank you :)

**Comment by edublancas** [comment]
no problem, we're aiming to release 0.7 next week so I appreciate it if you can take some time for testing it and report any issues!
