### ISSUE TITLE
Improving connecting UX

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#294]
A lot of the times when trying to connect to DBs, the user gets a generic message. We can adjust the message based on their connection string, for instance, we can tailor a message for someone who's trying to connect to a snowflake.
`'snowflake://<user_login_name>:<password>@<account_identifier>/<database_name>/<schema_name>?warehouse=<warehouse_name>&role=<role_name>'`

Once we detected the keyword we can alert that something's off and output the expected connection string structure, or what next steps to take to fix it.

**Comment by edublancas** [comment]
I believe the connection is established when calling [`connect`](https://github.com/ploomber/jupysql/blob/6e53a0048c038c84683c2bff6df37f45815b542b/src/sql/connection.py#L205) (but we have to double check)

in the constructor we already have a dialect variable, which we can use to tailor the error mesage
