### ISSUE TITLE
experiment: showing our community page on errors

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#30]
We want to incentivize our users to talk to us when they encounter problems by showing them our link to Slack in the exception message.

In ploomber-core 0.1, I added some custom exceptions, so we do that. Essentially, we want to replace some errors with their customized counterparts:

`ValueError` -> `PloomberValueError`
`TypeError` -> `PloomberTypeError`

see [documentation here](https://ploomber-core.readthedocs.io/en/latest/exceptions.html)

**Comment by edublancas** [comment]
> see [documentation here](https://ploomber-core.readthedocs.io/en/latest/exceptions.html)

i think we need to experiment a bit here because jupysql is mostly used through the magics (`%%sql`) and errors there are handled differently, we should ensure the community link is actually visible

**Comment by tonykploomber** [comment]
I'll start to work on all places use `ValueError` or `TypeError` to see if those could be replaced with our custom exceptions and shows the community link properly

**Comment by edublancas** [comment]
sounds good!
