### ISSUE TITLE
interactive plots

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#304]
We've recently build two features:

A new plot API based on ggplot: https://jupysql.ploomber.io/en/latest/user-guide/ggplot.html
And a command to enable interactivity for SQL queries: https://jupysql.ploomber.io/en/latest/user-guide/interactive.html

The next natural step is to enable interactive plots. The use case is this: I create a plot but I want to interactively subselect rows from the table that feed the plot. Following the example that we have in the interactive [tutorial](https://jupysql.ploomber.io/en/latest/user-guide/interactive.html#complete-example); we can allow users to define widgets:

![image](https://user-images.githubusercontent.com/989250/227298784-50b57548-2de0-43db-a5a5-d5916aec8f48.png)

And then update the plot according to the rows that match the criteria. Ideally, we should allow users to break the pre-processing logic in multiple cells so the code becomes modular:

## Example

cell 1: creates the widgets

```python
body_mass_lower_bound = 3600
show_limit = (0, 50, 1)
sex_selection = widgets.RadioButtons(
    options=["MALE", "FEMALE"], description="Sex", disabled=False
)
species_selections = widgets.SelectMultiple(
    options=["Adelie", "Chinstrap", "Gentoo"],
    value=["Adelie", "Chinstrap"],
    # rows=10,
    description="Species",
    disabled=False,
)
```

cell 2 defines the pre-processing logic (note that I'm passing `--save my_interactive query`)

```sql
%%sql --interact show_limit --interact body_mass_lower_bound --interact species_selections --interact sex_selection --save my_interactive query
SELECT * FROM penguins.csv 
WHERE species IN{{species_selections}} AND 
body_mass_g > {{body_mass_lower_bound}} AND 
sex == '{{sex_selection}}'
LIMIT {{show_limit}} 
```

cell 3: creates the plot

```python
(
    ggplot(
        table="my_interactive",
        with_="my_interactive",
        mapping=aes(x="some_column", fill="#69f0ae", color="#fff"),
    )
    + geom_histogram(bins=10)
)
```

I ran this example and it didn't work (the plot doesn't get update). I don't know much about ipywidgets but it seems like the challenge here is to connect the widget to the plot so it knows that it has to update whenever the widget changes. Ideally this should be automated since we know from the code that it should be connected: widget -> SQL query -> plot

**Comment by edublancas** [comment]
great, please post your updates if you find how to do this.

the other thing we can try (that sounds doable) is to embed the parameters in the ggplot call:

```python
(
    ggplot(
        table="SELECT * FROM penguins.csv LIMIT {{limit}}",
        with_="my_interactive",
        mapping=aes(x="some_column", fill="#69f0ae", color="#fff"),
        interact=dict(interact=interact)
    )
    + geom_histogram(bins=10)
)
```

But it isn't an ideal API.

**Comment by edublancas** [comment]
I'm starting to think that this isn't straightforward, since we cannot trigger execution of arbitrary cells. So users will have to run the plotting cell again if they want to update it.

I think this might be possible to do with [Voila](https://github.com/voila-dashboards/voila), since it runs the entire notebook before displaying the plots? So maybe we don't have to build this ourselves and just delegate it to Voila.

@tonykploomber: let me know what you think. seems like we're investing too much time into this.

**Comment by tonykploomber** [comment]
After some research I think this might be difficult to implement at this moment.

From the technical perspective: 
We have to access the local namespace to get the widget instance and apply to gglot function, however, our (gglot + geom_histogram) is class-based design, that's hard to add the `@interact` decorator in the class method.

**Comment by tonykploomber** [comment]
@yafimvo , might need your help to check this

This is the normal way to have interactive matplot:

https://user-images.githubusercontent.com/123580782/233895562-8de146f7-04ee-4736-8085-a29ef69f95d4.mov

Code:
```
import ipywidgets
import numpy as np
import matplotlib.pyplot as plt
X = np.random. uniform(0, 5, size=100)

@ipywidgets.interact(W=1)
def plot_fct(w=1):
    y = 2 * X + w * np. random. normal (size=100)
    plt.scatter (X, y)
```

We need to find the way to add the @interact decorator in the ggplot class, do you think we can do this?

**Comment by yafimvo** [comment]
> We need to find the way to add the @interact decorator in the ggplot class, do you think we can do this?

@tonykploomber I think we can some kind of create an "interactive wrapper" to manipulate the inputs.

This is a simple example of how we can change the bar color using a slider

https://user-images.githubusercontent.com/103026689/233998838-3f622c74-8f50-42b9-9b5f-1f65b12622c0.mp4

Code:

```
%load_ext sql
%sql duckdb://
```

```
%%sql --save short_trips --no-execute
select * from "yellow_tripdata_2021-01.parquet"
WHERE trip_distance < 6.3
```

```
import ipywidgets
import numpy as np
import matplotlib.pyplot as plt
X = np.random. uniform(0, 3, size=100)
from sql.ggplot import ggplot, aes, geom_histogram

colors = ['red', 'blue', 'green', 'magenta']

@ipywidgets.interact(W=(0, 3, 1))
def plot_fct(W=0):
    color = colors[W]
    (ggplot(table="short_trips", with_="short_trips", mapping=aes(x="trip_distance", fill=color))
    + geom_histogram(bins=10))
```

**Comment by edublancas** [comment]
I played around with ipywidgets these last few days, I think the solution that @yafimvo is good.

Since this doesn't require any code changes, the deliverable for this issue will be a tutorial showing how to manipulate some dataset (e.g., perform some cleaning), and then use the clean dataset and add some widgets to generate some interactive plots.

**Comment by tonykploomber** [comment]
That's the same conclusion as Yafim and I discuss yesterday, let's just add the tutorial to cover this
