### ISSUE TITLE
Drop sqlglot for generating CTEs

### ISSUE THREAD

**Issue by tonykploomber** [ploomber/jupysql#307]
Since using sqlglot will parse the user's query in `--with`, which is not ideal since parsing user's query isn't necessary and might introduce [some additional errors](https://github.com/ploomber/jupysql/issues/297#issuecomment-1481461249).

Our plans:

- [ ] Need some research to see what dialects support backticks, and make a list
- [ ] Remove the sqlglot & add condition on using non-backticks or backticks jinja template

**Comment by edublancas** [comment]
note: we'll only drop it when generating CTEs, while keeping it in other places for transpiling our queries
