### ISSUE TITLE
Make sure we support ipython 8.0+

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#31]
We should also [validate 7.0](https://github.com/catherinedevlin/ipython-sql/issues/178) while we're at it

**Comment by edublancas** [comment]
We're testing with the latest version of IPython, so we support 8. The CI runs pretty fast so maybe we can add an extra task with IPython 7, or add another step in one of the existing tasks

**Comment by idomic** [comment]
Yeah I think it should be on it's own given older versions tend to break faster. But sounds like a plan.

**Comment by idomic** [comment]
cc: @dangshazi

**Comment by edublancas** [comment]
closing since we're testing with ipython 8
