### ISSUE TITLE
Issue on page /api/magic-sql.html

### ISSUE THREAD

**Issue by dominijk** [ploomber/jupysql#311]
Many thanks for the work putting this together, suggestion on tutorials with alias (coming from ipython-sql).

````py 
%%sql some_alias 
df_result <<
SELECT a_thing
FROM a_place
LIMIT 100;
````

I'd been trying to figure out how did the old ipython-sql of the below and it took a bit of trial and error to understand  why it wasn't working

```py 
%%sql $connection << df_result
SELECT a_thing
FROM a_place
LIMIT 100;
```

**Comment by edublancas** [comment]
thanks for your feedback!

just to ensure I understood this, the first snippet is the one that works and the second one is what you tried first and didn't work?

sounds like adding more sample queries to the `--alias` documentation will fix this

**Comment by edublancas** [comment]
Updated the docs, added a few more details here: https://jupysql.ploomber.io/en/latest/api/magic-sql.html#connect-to-database

and linked from there to a longer tutorials that better explains how to manage connections

**Comment by dominijk** [comment]
Thanks, why are both the following discouraged? - is this just on the platform 

1. Switching and querying in one cell 
2. Switching, querying and storing result

**Comment by edublancas** [comment]
we discourage switching the connection and querying in the same cell because it might lead to errors like the one you found (we inherited this parsing behavior from ipython-sql and want to keep backward compatibility, so we haven't changed it). Splitting the switching and querying is more understandable.
