### ISSUE TITLE
Searching "<<" returns 0 results

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#316]
This is part of the syntax but it doesn't show anywhere in the docs search.

**Comment by tonykploomber** [comment]
Is it because "<<" is the reserved keyword in readmedoc? Need some research

**Comment by edublancas** [comment]
I'm guessing the readthedocs search feature ignores nonalphanumeric characters.

I don't think we should work on this since we're thinking of replacing it with algolia anyway: https://github.com/ploomber/jupysql/issues/64
