### ISSUE TITLE
Fix errors around variable substition with cell magic

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#32]
We need to [reproduce the errors the users reported](https://github.com/catherinedevlin/ipython-sql/issues/177) either via colab or the specific version and make sure that doesn't happens in the new version.

**Comment by edublancas** [comment]
This has been fixed already. The traceback reported:

```
/python3.7/site-packages/sql/magic.py in execute(self, line, cell, local_ns) 
     149         cell_params = {}
     150         for variable in cell_variables:
 --> 151         cell_params[variable] = local_ns[variable]
     152         cell = cell.format(**cell_params)

KeyError: 'tuple(myids)'
````

Does not match the existing source code in ipython-sql.

[This commit from June 2022](https://github.com/catherinedevlin/ipython-sql/commit/bb648623030214a476ea75f2a5135d1c8eb1768e) modified that part of the source code and replaced it by an IPython function call, this most likely fixed the bug.

**Comment by idomic** [comment]
cc: @duncandewhurst @rxm @melanopsis  @fa-ahmad
This was fixed, tested, and merged. Expect a release with this in it.
