### ISSUE TITLE
check-for-broken-links CI fails on CONTRIBUTING.md link

### ISSUE THREAD

**Issue by yafimvo** [ploomber/jupysql#334]
CI fails on missing contributing file. 
The broken link : https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md

[CI error](https://github.com/ploomber/jupysql/actions/runs/4552149607/jobs/8027127038?pr=324)

cc: @edublancas

**Comment by edublancas** [comment]
fixed in https://github.com/ploomber/jupysql/commit/86b03c74909b2ebf3c1c94434f3818e75e0abf4a
