### ISSUE TITLE
explicitly document the difference between %sql and %%sql (maybe adding an FAQ section)

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#34]
This comes from [this user question](https://github.com/catherinedevlin/ipython-sql/issues/174)

**Comment by idomic** [comment]
@NimJ @techtonik @EminUZUN feel free to open a PR if you're up for it!

**Comment by edublancas** [comment]
I think we should also add a section on the things we've seen are asked by users on ipython-sql, so google indexes them

**Comment by idomic** [comment]
Yeah that's the next step!

**Comment by edublancas** [comment]
closing in favor of #205
