### ISSUE TITLE
delete stalled branches

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#346]
we have lots of stalled branches, we should remove them as it makes hard to track which ones are active and which ones are not:

![image](https://user-images.githubusercontent.com/989250/229192344-bba997eb-1769-4e78-bd10-2d93986870ec.png)

**Comment by tonykploomber** [comment]
I'll check...mostly I created those

**Comment by tonykploomber** [comment]
I've created all stalled branches I & Palash created, the rest are created by @edublancas 
Probably you can take a look and remove

**Comment by edublancas** [comment]
great, I deleted the rest.
