### ISSUE TITLE
Document local sqllite connection with spaces on windows

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#35]
The spaces probably will break the engine connection string. We need to [reproduce](https://github.com/catherinedevlin/ipython-sql/issues/172) and document a way of doing so.

**Comment by idomic** [comment]
@mglatz @bhishanpdl if you found a solution and up for a pull-request go ahead!

**Comment by edublancas** [comment]
tip: the problem is the input parsing logic. In our fork, we moved that [to here](https://github.com/ploomber/jupysql/blob/master/src/sql/command.py).

My guess is that the parsing is interpreting any spaces as the end of the connection string.

**Comment by edublancas** [comment]
Re-opening this one. We have a [workaround here](https://jupysql.readthedocs.io/en/latest/howto.html#connect-to-a-sqlite-database-with-spaces)

but we need to implement a full fix.
