### ISSUE TITLE
error when validating if a table exists

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#355]
I found an error when validating if a table exists, because it doesn't check if a CTE has been stored:

```sql
%%sql --save many_passengers --no-execute
SELECT *
FROM taxi
WHERE passenger_count > 3
-- remove top 1% outliers for better visualization
AND trip_distance < 18.93
```

Then, using:

```sql
%sqlplot histogram --table many_passengers --column trip_distance --with many_passengers
```

Throws this error:

```
ValueError: There is no table with name 'many_passengers' in the default schema
If you need help solving this issue, send us a message: https://ploomber.io/community
```

Even though I already stored `many_passengers` using `--save`

Note: this is blocking the release

cc @idomic @yafimvo

**Comment by edublancas** [comment]
for more context: we can validate if the user has stored a snippet with:

```python
from sql.store import store

"something" in store
```

https://github.com/ploomber/jupysql/blob/6ae9641bdb080c9c301ed79cfb07297e48320d07/src/sql/store.py#L145

An added improvement can suggest the user a missing `--with` argument. e.g., if I execute:

```
%sqlplot histogram --table many_passengers --column trip_distance
```

we could check if `many_passengers` exist, and if so, the error can be: There is no table many_passenegrs, but there is a stored query. Did you miss passing `--with many_passengers`?

**Comment by yafimvo** [comment]
Since this case is being tested, I tried to run this notebook without checking if the table exists and it failed with this TypeError message:

```
TypeError: %o format: an integer is required, not dict
```

on this line:
```
min_, max_ = con.execute(query).fetchone()
```

I think it happens due to this line: `-- remove top 1% outliers for better visualization` because if I run this code cell without it, it works.

```
%%sql --save many_passengers --no-execute
SELECT *
FROM taxi
WHERE passenger_count > 3
AND trip_distance < 18.93
```

for the same reason, `_is_table_exists` failed and returned `False`. I'm not sure that we need to handle this error in this method, perhaps we need to create another validation i.e : `is_valid_sql` to make sure user's SQL is formatted correctly - but it might be difficult to anticipate invalid SQL formats.

@edublancas @idomic

**Comment by edublancas** [comment]
I'm unable to reproduce this:

> TypeError: %o format: an integer is required, not dict

can you provide more details?

**Comment by edublancas** [comment]
alright, I found the issue (and discovered another issue along the way):

![image](https://user-images.githubusercontent.com/989250/229955494-9f21cd0b-536e-437a-b4bc-d6f27a6e27b8.png)

I'll open a PR explaining what I found.


@yafimvo: I'll take over this, but please share the steps to reproduce the `TypeError: %o format: an integer is required, not dict` error as I was unable to reproduce it and I wanna ensure I'm not missing any other edge cases.

**Comment by yafimvo** [comment]
> I'm unable to reproduce this:
> 
> > TypeError: %o format: an integer is required, not dict
> 
> can you provide more details?


Yes. In the same notebook, you can run this code:

```
from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://user:password@127.0.0.1:3306/db")

query_with_line = "WITH many_passengers AS (SELECT * FROM taxi/* remove top 1% outliers for better visualization */  WHERE passenger_count > 3 AND trip_distance < 18.93) SELECT MIN(`trip_distance`), MAX(`trip_distance`) FROM `many_passengers`"

query_without_line = "WITH many_passengers AS (SELECT * FROM taxi WHERE passenger_count > 3 AND trip_distance < 18.93) SELECT MIN(`trip_distance`), MAX(`trip_distance`) FROM `many_passengers`"
with engine.connect() as cur:
    r = cur.execute(query_with_line).fetchone()
    print(r)
```
