### ISSUE TITLE
cockroachdb integration

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#36]
[Following this issue](https://github.com/catherinedevlin/ipython-sql/issues/168), we should check what fixes are needed to support the db.

We should also write a guide on connecting to it, and add it to the DB's documentation

**Comment by idomic** [comment]
@dbist if you have a workaround feel free to submit a PR.

**Comment by edublancas** [comment]
ideally, we should only test that the right connection string is received, since it'd be an overkill to add a cockroachdb instance to our CI

**Comment by idomic** [comment]
+1
