### ISSUE TITLE
Issue on page /user-guide/tables-columns.html

### ISSUE THREAD

**Issue by dominijk** [ploomber/jupysql#366]
Your issue content here.

`%sqlcmd tables` is that in place of duckdb `SHOW TABLES;` or `%%sql select * from duckdb_tables`

**Comment by edublancas** [comment]
Good point, `%sql cmd tables` is compatible across databases since it relies on SQLAlchemy, but perhaps we should be more explicit and say so?

Actually, I'm unsure if there's *any* database that doesn't support `SHOW TABLES`.
