### ISSUE TITLE
mssql+pyodbc connection issue, MARS_Connection=Yes variable

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#38]
We should allow an easier workaround for [this parameter](https://github.com/catherinedevlin/ipython-sql/issues/54).
The current workaround for users is setting `MARS_Connection=Yes`

**Comment by edublancas** [comment]
since there are so many databases, there might be ones that need these kinds of workarounds. I agree that we should support them without hassle; but a good first step would be to document this tricks in our documentation, while we work on supporting them
