### ISSUE TITLE
integration tests getting stuck on windows

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#382]
context: https://github.com/ploomber/jupysql/pull/380#pullrequestreview-1374183804

**Comment by tonykploomber** [comment]
@yafimvo 
Can you try to do:
1. Delete all download Images in docker
<img width="633" alt="Screenshot 2023-04-05 at 4 12 54 PM" src="https://user-images.githubusercontent.com/123580782/230417730-b301d8e1-7008-4fab-957d-1ec3de1b8864.png">
2. Delete all Volumes in docker
<img width="899" alt="Screenshot 2023-04-05 at 4 12 59 PM" src="https://user-images.githubusercontent.com/123580782/230417786-8f3c88fa-1f4a-4bc8-9198-43ae49476be2.png">
3. Kill all existing or running containers & execute `pytest src/tests/integration` again

If any containers fail, can you paste the logs on that container so we can identify the issue
<img width="1488" alt="Screenshot 2023-04-06 at 10 55 36 AM" src="https://user-images.githubusercontent.com/123580782/230418046-52f4f161-07c7-40fd-baf5-340bbfa22f08.png">
