### ISSUE TITLE
Backtick issue we should fix

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#383]
Check out [this TODO](https://github.com/ploomber/jupysql/pull/362#discussion_r1158655916)

**Comment by edublancas** [comment]
So this is pretty much the same problem as: https://github.com/ploomber/jupysql/issues/386

it can be fixed by making `is_use_backtick_template` an instance method

**Comment by edublancas** [comment]
yes, I updated https://github.com/ploomber/jupysql/issues/386
