### ISSUE TITLE
`_transpile_query` should not be a `@classmethod`

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#386]
`_transpile_query` is a classmethod that uses the current connection's dialect and transpiles it into a target dialect. However, in some cases, we might not want to use the currently active connection, but a different one, and transpile the query.

Here's an [example](https://github.com/ploomber/jupysql/blame/dc034e95edc62513b3a28e39e4fb95dcb2f06086/src/sql/plot.py#L485). In the `_historgam` function, we can take an optional `conn` argument (a sqlalchemy engine); however, the [transpilation step](https://github.com/ploomber/jupysql/blame/dc034e95edc62513b3a28e39e4fb95dcb2f06086/src/sql/plot.py#L548) uses the dialect from the currently active connection. If the passed `conn` argument and the active connection do not have the same dialect, this will produce [problems](https://github.com/ploomber/jupysql/pull/152#discussion_r1160177549)

Instead, we should use the information from the `conn` argument, if any.

Example:

```python
def some_function(conn=None):
    if conn is None:
        conn = # get current active connection
    else:
       # Connection objects can be initialized with sqlalchemy engines
       conn = Connection(engine=conn)
     
    # transpile should be an instance method that uses the dialect from the `conn` engine
     query = conn.transpile()
```

**Update**: per  @idomic suggestion. Let's tackle this: https://github.com/ploomber/jupysql/issues/383 in this issue too

**Comment by tonykploomber** [comment]
To apply this logic, I think we need to change the `_get_curr_sqlalchemy_connection_info, _get_curr_sqlglot_dialect, get_curr_identifiers, is_use_backtick_template` to instance methods too.

**Comment by tonykploomber** [comment]
Since currently in [_transpile_query](https://github.com/ploomber/jupysql/blob/master/src/sql/connection.py#L425-L429)(), we use `_get_curr_sqlglot_dialect` classmethod to get the current sqlglot dialect info

Probably it's better we can fix those together?
```
        write_dialect = cls._get_curr_sqlglot_dialect()
        try:
            query = sqlglot.parse_one(query).sql(dialect=write_dialect)
        finally:
            return query```

**Comment by tonykploomber** [comment]
Yeah, for me is clear to understand the purpose of this ticket.
Just need to confirm if we need to apply the same logic to other functions. I think so

**Comment by edublancas** [comment]
yes, let's apply the changes to the other methods. I'm unsure if there are ones that make sense to keep as classmethods but I'll leave it up to you @tonykploomber

**Comment by edublancas** [comment]
@tonykploomber: I updated the top comment in this issue. we'll tackle https://github.com/ploomber/jupysql/issues/383 here too, since it's closely related
