### ISSUE TITLE
Plotting functions are ignoring the dialect in the `conn` argument

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#387]
We have functions (I believe they're all in the `plot.py` module) that optionally take a connection object in a `conn` argument. By default, `conn` is `None`, which implies using the currently active connection in the session.

The problem is that when a user passes a `conn` object, we're ignoring the information and using the current active connection (which might not be the same).

The solution is to convert the `conn` argument into a Connection object and extract information from there. Note that this is blocked by: https://github.com/ploomber/jupysql/issues/386 and https://github.com/ploomber/jupysql/issues/383

there might be other class methods that need to become instance methods as well.

**Comment by tonykploomber** [comment]
Trying to understand problem:
1. What information we are ignoring for? Do you mean actually we always use the current active connection?
2. I guess we need to finish https://github.com/ploomber/jupysql/issues/383 before handling this?

> The problem is that when a user passes a conn object, we're ignoring the information and using the current active connection (which might not be the same).

**Comment by edublancas** [comment]
I think this has been fixed since some class methods are now instance methods.

This was before: https://github.com/ploomber/jupysql/blob/7692407ac94820ef0bc181cd0095bbd6750fc258/src/sql/plot.py#L247
Now: https://github.com/ploomber/jupysql/blob/2aad8bee5424791a5c45dc64881b4a3a915bb160/src/sql/plot.py#L262

@tonykploomber: let me know if we can close this

**Comment by tonykploomber** [comment]
Yeah now `_get_curr_sqlalchemy_connection_info` is associate with connection instance, now it should be good
