### ISSUE TITLE
fix Python examples

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#388]
In https://github.com/ploomber/jupysql/pull/339, we modified some Python examples and now they require this line:

```
conn = Connection.from_connect_str("duckdb://").session
```

instead of:

```
conn = create_engine(...)
```

This is because of the problems I described in: https://github.com/ploomber/jupysql/issues/386 and https://github.com/ploomber/jupysql/issues/383

So once those are merged, we should ensure we revert back the examples to:

```
conn = create_engine(...)
```

**Comment by tonykploomber** [comment]
I think this will be tackled and fixed by https://github.com/ploomber/jupysql/pull/389
