### ISSUE TITLE
Allowing sql highlighting

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#39]
[This](https://github.com/catherinedevlin/ipython-sql/issues/41) currently doesn't work in jupyterlab.
We should tackle this issue to make the code more readable for users.

**Comment by edublancas** [comment]
I did some research on this a while ago. It's pretty complex to add support to syntax highlighting in the current version of JupyterLab. I remember reading this it is possible installing the language protocol, and that the upcoming major release will simplify things; but still worth investigating and summarizing what's the status now.

**Comment by edublancas** [comment]
[Here's a link with more information](https://stackoverflow.com/questions/68340216/any-way-to-bring-back-sql-magic-syntax-highlighting-to-jupyterlab-notebook). tl;dr; it isn't trivial to bring back syntax color to JupyterLab. The answer suggests using an external package that implements language server protocol. We could add a guide to our docs.

**Comment by idomic** [comment]
I agree on the original issue. but I think #43 is for the syntax, this issue was more to color the result cell, you don't think it's a valuable feature?

**Comment by edublancas** [comment]
closing in favor of https://github.com/ploomber/jupysql/issues/6
