### ISSUE TITLE
Document how to secure the connection credentials

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#40]
[This](https://github.com/catherinedevlin/ipython-sql/issues/36) is implemented but not well documented.
We should add a section about security best practices to tell the users how to pass their connection string in a secure way vs raw user/pass in their notebooks.

**Comment by edublancas** [comment]
agree: we should refactor [this section](https://jupysql.readthedocs.io/en/latest/connecting.html) - still contains the same docs as ipython-sql and replace it with best practices: one option is to use getpass, [keyring](https://pypi.org/project/keyring/) is another option we can explain

**Comment by idomic** [comment]
@christophlingg @invisiblefunnel @AndreaCrotti @mottalrd @eshilts @tosolveit
We just updated the docs and released a new version( [0.5.2 changelog](https://github.com/ploomber/jupysql/blob/0.5.2/CHANGELOG.md)). 
Make sure to [join our slack](https://ploomber.io/community/) for more info and support
