### ISSUE TITLE
Adding Impala support

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#41]
[Currently](https://github.com/catherinedevlin/ipython-sql/issues/57) there's no support. [Similar reference](https://github.com/catherinedevlin/ipython-sql/issues/111)
We need to merge Luca's fix.

**Comment by idomic** [comment]
cc: @Tagar @LucaCanali

**Comment by edublancas** [comment]
I think this has been fixed already (but I have no way of testing it), [the docs](https://jupysql.readthedocs.io/en/latest/connecting.html#connecting) indicate that you only need to disable autocommit.

```
%config SqlMagic.autocommit=False
%sql impala://hserverhost:port/default?kerberos_service_name=hive&auth_mechanism=GSSAPI

```

**Comment by idomic** [comment]
To mark as done we have to test this. I think also we can do it automatically (if needed in the future, since I don't know how many impala users are using it). i.e. detect impala from the connection string, automatically set `SqlMagic.autocommit=False`.

There are 2 ways I'm seeing of testing this issue:
[Start locally a cluster via script](https://cwiki.apache.org/confluence/display/IMPALA/How+to+start+a+Ranger-enabled+Impala+minicluster)
[Start a cluster via docker](https://github.com/apache/impala/blob/master/docker/README.md)
[Start a cluster on the cloud](https://aws.amazon.com/about-aws/whats-new/2013/12/12/announcing-support-for-impala-with-amazon-elastic-mapreduce/) which is probably the easiest.
