### ISSUE TITLE
Syntactic sugar for outputting capture variable

### ISSUE THREAD

**Issue by jorisroovers** [ploomber/jupysql#418]
A common pattern we use is storing the result of a `%%sql` cell in a variable using the `<<` operator so it can be used for further processing later, but then also immediately outputting that variable in the cell below to look at the results.

```bash
[1] %%sql MYRESULT <<
    SELECT * FROM MYTABLE WHERE x = "y"
[1] (No cell output)

[2] MYRESULT # display result
[2] <result output>
```

It would be nice if jupysql would support some syntactic sugar so this could be done in a single cell:

```bash
[1] %%sql MYRESULT= <<
    SELECT * FROM MYTABLE WHERE x = "y"
[2] <result output>
```

Notice the use of the `=` sign after the variable name (so `MYRESULT=` instead of `MYRESULT`). This is just a suggested syntax, [inspired by similar python f-strings expressions](https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging).

Alternative ways could be:

1. Using a global config flag:
    
    ```bash
    %config SqlMagic.outputVariables = False  # Probably use a better config name?
    ```
    
2. Use a cell-magic flag, e.g. `--print` (more verbose, but less esoteric than using the `=` syntax)
    
    ```bash
    %%sql --print MYRESULT= <<
    SELECT * FROM MYTABLE WHERE x = "y"
    ```
    
 3. Other?

I'm not sure whether the `%sql` (single `%`) magic would benefit from a similar capability?

I had a quick look at the code, and I think the logic here just needs to be changed to return `result` in case the variable outputting is enabled.

https://github.com/ploomber/jupysql/blob/a456c3a66477b7ddd8967b8353b95d3c99d3739f/src/sql/magic.py#L399-L401

In case we we want to use special syntax with `=` (as opposed to `%%sql` flags or global config options), I think that detection of whether variable outputting is enabled would happen here:

https://github.com/ploomber/jupysql/blob/a456c3a66477b7ddd8967b8353b95d3c99d3739f/src/sql/parse.py#L53-L54

Thanks for considering!

**Comment by edublancas** [comment]
This makes sense, although I'm unsure if the `= <<` or the config is better.

@jorisroovers: have you encountered cases where you *do not* want to display the data preview? I think a config makes sense if you always want to show it, and the `= <<` makes sense if in a given notebook, there's a high chance that users want the preview in some cells  but not in others

One consideration is how many rows we should display, but I think those are separate issues: https://github.com/ploomber/jupysql/issues/419

**Comment by jorisroovers** [comment]
> @jorisroovers: have you encountered cases where you _do not_ want to display the data preview? I think a config makes sense if you always want to show it, and the `= <<` makes sense if in a given notebook, there's a high chance that users want the preview in some cells but not in others

Yes, I think there use-cases for both scenarios.

I personally like the `= <<` syntax as it allows me the choice and quickly enable/disable output formatting while working on a specific query while not "poluting" the notebook with output of variables I don't want.

I can look into submitting PR(s) for either or both approaches if you want (might take a bit, depending on how quickly I can make the time).

**Comment by jorisroovers** [comment]
Have not forgotten! Hopefully this week :)
