### ISSUE TITLE
limiting the number of displayed rows

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#419]
Using [`displaylimit`](https://jupysql.ploomber.io/en/latest/api/configuration.html#displaylimit), users can limit the number of displayed rows. So, even if the query they're running returns 1M rows, we can limit how many of them are displayed. Note that this doesn't affect when autopandas or autopolars are enabled.

Currently, the default value sets no limit, but this isn't a sensible default. Since more often than not, retrieve results are in the order of thousands of observations. I think we should set a default value, but still allow users to set no limit if they want

For example,  pandas  has a default limit of 60: https://pandas.pydata.org/docs/user_guide/options.html#overview

**Comment by tonykploomber** [comment]
Working on this, let's set the `displaylimit = 60` as default for now, LMK you want to change

**Comment by edublancas** [comment]
let's go ahead with 60

**Comment by edublancas** [comment]
this  needs a bit more investgation. I just realized that even though pandas default says 60, it's only displaying: 10 - so let's check out pandas documentation to understand how it works.

![image](https://user-images.githubusercontent.com/989250/234410422-db9dd369-5467-41e9-9b45-0cdff0ba607f.png)

**Comment by tonykploomber** [comment]
In pandas, it's controlled by `display.max_rows`

The default value of max_rows is 10. If set to ‘None‘ then it means all rows of the data frame. Set value of display.max_rows to None and pass it to set_option and this will display all rows from the data frame.

Something like this:

`pandas.set_option('display.max_rows', None)` -> display all rows
`pandas.set_option('display.max_rows', 20)` -> display 20 rows

I think we can update the AC:

1. By default, the `displaylimit` is 60
2. If `displaylimit` is set to `None`, we display all 
3. If `displaylimit` is set to any positive integer, we display the number of that
