### ISSUE TITLE
Allow sql kernel as part of the package

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#42]
[This is](https://github.com/catherinedevlin/ipython-sql/issues/59) an interesting idea of having a sql-only notebook

**Comment by edublancas** [comment]
Writing a new kernel is a project on its own, and there's [already](https://blog.jupyter.org/an-sql-solution-for-jupyter-ef4a00a0d925). I definitely see the value, but I don't think this is the right time. My guess is that most people still need to combine Python and SQL in the same notebook, and for the ones who do not, adding the magic is a minor annoyance.
