### ISSUE TITLE
error when detecting is connection is custom

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#433]
(Note that this error can only be reproduced with https://github.com/ploomber/jupysql/pull/431, which hasn't been merged yet)

while improving some error messages, I encountered this:

![image](https://user-images.githubusercontent.com/989250/233754280-328dda08-ec54-402d-98e9-5a17e8f2fc37.png)

Note that the error message doesn't accurately display the error in the `df` variable. Instead, if shows `''`

I tracked down the error to this method:

https://github.com/ploomber/jupysql/blob/fcc74b0f56c007d04f1f0997373c79cba342f23f/src/sql/connection.py#L362

Since `int` is not part of the list of checks:

https://github.com/ploomber/jupysql/blob/fcc74b0f56c007d04f1f0997373c79cba342f23f/src/sql/connection.py#L381

It fails. Which breaks the `SQLCommand` logic (the `is_custom_connection` is called there).

We need a more robust way to check whether a connection is custom or not. A better approach is to check if the connection object has all the attributes expected from the DB API: close, commit, rollback and cursor (https://peps.python.org/pep-0249/)

**Comment by tonykploomber** [comment]
I am trying to reproduce the error.
Do you mind to share how you make `duckdb://` connection as custom?


<img width="1112" alt="Screenshot 2023-04-24 at 4 18 08 PM" src="https://user-images.githubusercontent.com/123580782/233939494-d2a5a55b-02f2-49fe-92d3-115091472f78.png">

**Comment by edublancas** [comment]
@tonykploomber: I just realized this could not be reproduced with the code in master. Let's wait until https://github.com/ploomber/jupysql/pull/431 is merged - I reproduced it while working on that PR
