### ISSUE TITLE
Presto DB integration guide

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#435]
We need to add a guide on how to connect to presto and visualize it.

**Comment by duke8585** [comment]
okay, got it. it was as simple as this:
```
%config SqlMagic.autocommit=False
```

**Comment by edublancas** [comment]
@neelasha23 have you started working on this already? If not, I'll unassign it and assign something else

**Comment by neelasha23** [comment]
started looking at local setup, not coded yet. Please assign me something else.

**Comment by edublancas** [comment]
cool, unassigned
