### ISSUE TITLE
Documenting dumping to csv and other formats

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#443]
This feature is inheritted from ipython-sql, we should document how to use it, which formats it works with etc. Probably the next step we can take is adding a flag, `--to-csv` `--to-parquet` or `--to-file` `format` (`--to-file csv`)etc.

```
result = %sql SELECT species FROM penguins.csv LIMIT 3
result.csv(filename='species.csv')
```
<img width="533" alt="Screen Shot 2023-04-24 at 10 14 59 AM" src="https://user-images.githubusercontent.com/11596985/234024161-244fdeab-25a7-4877-b791-603ab0921af5.png">

**Comment by edublancas** [comment]
we have a section dedicated to it: https://jupysql.ploomber.io/en/latest/howto/csv.html

do you think we should change its contents?

I agree that exporting to other formats is valuable

**Comment by edublancas** [comment]
ok, so I think these are the changes:

1. Support export to parquet via `result.parquet` (we an use pyarrow for this)
2. Create a new "Exporting data" section in the User Guide
