### ISSUE TITLE
Add benchmarking capabilities

### ISSUE THREAD

**Issue by lfunderburk** [ploomber/jupysql#448]
One member approached me during PyCon asking about benchmarking capabilities. During the discussion, they mentioned they want to improve query performance and they wanted the ability to run tests across different databases:

Example:

1. SQL server on prem vs connecting via JupySQL
2. Testing query speed on different database access points

Others in the group asked if it was possible to include a mechanism to track how long it takes to complete a query.

**Comment by edublancas** [comment]
I think we can start by adding a quick cookbook in our docs recommending to use this [extension](https://github.com/deshaw/jupyterlab-execute-time), it records the time it takes to run a cell. then, we can decide if we add some extra capabilities.
