### ISSUE TITLE
Add capability to embed SQL queries inside .py scripts

### ISSUE THREAD

**Issue by lfunderburk** [ploomber/jupysql#449]
This question came up in two scenarios:

1. From a SQL user who is looking for ways to easily integrate SQL queries using .py scripts. They don't work with Jupyter notebooks in their applications and they want the ability to execute queries with a similar ease.
2. For the deepset tutorial, the devrel I am working with also wondered whether it was possible to script the queries within .py files

If not possible, can you advise of an alternative approach we can take?

**Comment by edublancas** [comment]
Yes, they can use .py scripts using the percent format. VSCode and Spyder support this:

![image](https://user-images.githubusercontent.com/989250/234417061-63409b97-6c94-445a-b8b7-009192a30805.png)

Let's keep this open, I think we should have a tutorial about this.

---

If they don't want to use the .py percent format, it's also possible to use JupySQL using the Python API, we should document that as well. But that's gonna take more time as we might need to make some changes to the codebase.

**Comment by edublancas** [comment]
we can create a new user guide showing how to use jupySQL with .py files. VSCode should work just fine (as I showed in the screenshot) but I believe JupyterLab might need some tweaks.


Users can open .py as notebooks in JupyterLab using jupytext; however, I remember having some issues so we need to check if they're still happening:

- create a notebook and include some SQL cells with arguments example`%%sql --save`
- convert the notebook to py:percent format using jupysql
- open the new .py file as a notebook (this should be enabled once jupytext is activated)
- add a new cell with arguments `%%sql --save`, save the .py file, close it
- re-open the file again, check if the arguments still appear in the right place
