### ISSUE TITLE
color coding cell status - green for successful and red for errored result

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#45]
We can follow [this issue](https://github.com/catherinedevlin/ipython-sql/issues/85) to allow users easily distinct between cells that are executed successfully vs ones that didn't.

**Comment by idomic** [comment]
cc: @max-sixty

@crawles feel free to submit a PR.

**Comment by edublancas** [comment]
The original issue does not refer to coloring green/red on success/fail. It says that syntax solor stops working after the query fails. This is a duplicate of https://github.com/ploomber/jupysql/issues/39

**Comment by idomic** [comment]
I agree on the original issue. but I think https://github.com/ploomber/jupysql/issues/43 is for the syntax, this issue was more to color the result cell, you don't think it's a valuable feature?
