### ISSUE TITLE
close all connections when shutting down the kernel

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#458]
currently, users have to manually close connectios via `--close`. But in most cases, it'd be better to close them automatically. for example, when they restart the kernel or they shut down jupyterlab

we can use the atexit module to do that: https://docs.python.org/3/library/atexit.html and close all connections right before the kernel shuts down.

**Comment by TegveerG** [comment]
AC:

1. Add new method `close_all_connections(cls)` inside class Connection to close all connections
2. Use `atexit.register(Connection.close_all_connections)` after Connection class definition. This is called automatically when the program exits, ensuring that all connections are closed before the kernel shuts down.
