### ISSUE TITLE
sqlcmd profile improvements

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#459]
So the table profiling is a bit unclear on how to read the output and what to do with nan values.
For instance, running on the table below, it could be `nan` for many reasons, wrong datatypes, db doesn't support the unique functions (STDEV function), confusing values (`2.456e+01`) etc.

We should improve the guide and the functionality of it, and produce a result that's similar in essence to the pandas profiling report.
<img width="1043" alt="Screen Shot 2023-04-26 at 3 57 46 PM" src="https://user-images.githubusercontent.com/11596985/234688977-e0a626e5-8275-41a1-9aab-713cea010a61.png">

@edublancas feel free to add more context.

**Comment by edublancas** [comment]
hey @yafimvo: did you start working on this? I can assign it to somebody else

**Comment by edublancas** [comment]
cool. I'll assign it to someone else.

**Comment by AnirudhVIyer** [comment]
On it!
