### ISSUE TITLE
resultset are indistinguishable from pandas data frames

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#468]
ResultSet (the data structure we use by default to store db results), is currently indistinguishable from pandas data frames:

![image](https://user-images.githubusercontent.com/989250/235201469-14c5b7ee-6f4a-4094-a8de-5a07292feee9.png)

this can confuse users, as they might think the're data frames. we should ensure they look different. perhaps add result set at the bottom.

maybe we should also detect when they try do perform pandas-like operations? e.g.,

```
df.head()
```

Error should be: `head is not a valid operation, you can convert this into a pandas data frame by calling .DataFrame() or a polars data frame by calling .PolarsDataFrame()`

**Comment by bbeat2782** [comment]
Sorry for working on the problem before describing the AC

Acceptance Criteria:
1. Add string below ResultSet representation indicating it is a ResultSet object and not pd.DataFrame
2. Add "to convert to pandas, call `.DataFrame()`" next to the string created above
3. Raise an AttributeError with the error message (`head is not a valid operation, you can convert this into pandas data frame by calling .DataFrame() or a polars data frame by calling .PolarsDataFrame()`) when an invalid operation is performed on the ResultSet object


About the 3rd criterion, do I show the same error message when non pandas-like operations (either by typo such as hea() or by intention) are performed?

**Comment by edublancas** [comment]
for 2) we can also mention they can call `.PolarsDataFrame()` to convert to polars

> About the 3rd criterion, do I show the same error message when non pandas-like operations (either by typo such as hea() or by intention) are performed?

No, no need to cover typos.
