### ISSUE TITLE
pgspecial integration to jupysql

### ISSUE THREAD

**Issue by lfunderburk** [ploomber/jupysql#479]
Explore current functionality and successful connection to [pgspecial](https://github.com/dbcli/pgspecial) (Python implementation of postgres meta commands (backslash commands))

Item suggested by Catherine Devlin

Things to explore:

1. What pgspecial does and how it works
2. Ways to incorporate it into jupysql
3. Areas of difficulty/challenges
4. Ways to engage users

**Comment by edublancas** [comment]
we already have an integration and are currently working on better support
