### ISSUE TITLE
PostgreSQL meta commands support

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#48]
There's some [issue](https://github.com/catherinedevlin/ipython-sql/issues/128) with `pgspecial`, this only happens in magics.
We should reproduce and solve this in a manner that doesn't require the users to restart the kernel.

cc: @mayankkaizen @lawalogunfowora @joreyolo @mrlevitas @vioxcd @is-wschumacher @brazacz
@trunksio @henrymei @o-rayer @marcelokuadro @SimarKareer @ep3data-admin

**Comment by yafimvo** [comment]
I've installed `postgresql`, `psycopg2`, and `pgspecial` in jupysql env; and was able to run PostgreSQL meta commands using magic without restarting the kernel.

(tested on windows, wsl2 with ubunutu 22.04)

![image](https://user-images.githubusercontent.com/103026689/210766068-0f4cc4f9-97b8-4e99-a088-8ba0a16f965f.png)


is it possible the user's env was messy?

**Comment by idomic** [comment]
Probably that's what happened.
Can you test with:
1. Bigger data/tables? (10K rows+)
2. On a mac/linux machine.

If those two works well I think we can close this.

**Comment by yafimvo** [comment]
I ran some queries on a 10K rows table ('items') - it also worked.

Please try it on your mac as well using the following connection string

```
%sql postgresql+psycopg2://tsdbadmin:ezuimn0s5g2vjle6@wye53gottl.a9laynscgf.tsdb.cloud.timescale.com:36527/tsdb
```
jupysql env installation:
1. (You might need to install PostgreSQL on your machine)
2. pip install psycopg2-binary (or pip install psycopg2)
3. pip install pgspecial

example queries and commands to run:
```
%sql select * from items
```

```
%sql \d
```

```
%%sql 
\dt
```

```
%sql \l
```

**Comment by edublancas** [comment]
I was able to reproduce the issue reported. I ran `pip install psycopg2 pgspecial`

Running this:

> %sql \d

Led to this: `ImportError: pgspecial not installed`

Whatt was weird is that running this works:

```
import pgspecial
from pgspecial.main import PGSpecial
```

I restarted the kernel and it didn't fix the issue. I uninstalled psycopg2-bin and pgspecial, reinstalled via conda:

```
conda install psycopg2 pgspecial -c conda-forge
```

And it worked. So at the very least we should document this. It'd be better if we find a way to "verify" pgspecial installation because as we saw, a successful `pip install pgspecial` and successful imports is not enough.

> Please try it on your mac as well using the following connection string

let's change the credentials for that database, please share new credentials privately on slack

**Comment by idomic** [comment]
Was also able to recreate, like above, this is what solved the issue:
`conda install psycopg2 pgspecial -c conda-forge`
I don't think it works well with `psycopg-binary`.

@yafimvo Given it's external packages that out of our control, the best resolution is documenting it - or if we want to spend time on it (I don't think we should) - diving and understanding why it happens.

**Comment by edublancas** [comment]
agree with @idomic - documenting this is enough for now

**Comment by edublancas** [comment]
A final note: we should also include in the documentation that users need pgspecial 1.x since pgspecial 2.x migrated to psycopg3 (and the error messages are not helpful):

```
conda install "pgspecial<2" -c conda-forge
```
