### ISSUE TITLE
UDF support

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#49]
Currently the package doesn't [support](https://github.com/catherinedevlin/ipython-sql/issues/134) it.
We should add a feature to accept it and execute it via the engine.

**Comment by idomic** [comment]
cc: @jonnickerson

**Comment by idomic** [comment]
Reopening this as an easier solution can be made here

**Comment by edublancas** [comment]
I think this should be a separate issue with more details (the proposed API)

**Comment by idomic** [comment]
Proposed API:

```python
# Load the extension and connect to the database
%load_ext sql
%sql postgresql://username:password@localhost:5432/mydatabase

# Define a function that takes in a value and returns its square
def my_square_function(x):
    return x * x

# Use the func module to define the UDF as a SQL expression
from sqlalchemy import func
square_udf = func.my_square_function(column)

# Use the UDF in a SELECT statement
result = %sql SELECT *, :square_udf AS squared_value FROM mytable

# Print the result set
print(result)
```

We might want to even create a tighter integration to the func part, maybe something like:

```python
# Define the UDF as a SQL expression
%sql --udf square_udf=my_square_function

# And then consume it
%sql SELECT *, :square_udf AS squared_value FROM mytable
```

**Comment by edublancas** [comment]
this is highly db dependent, I think we should close it

**Comment by edublancas** [comment]
ok, then let's start with a single one, the one that has the most users.

**Comment by edublancas** [comment]
each db has its own mechanism for defining UDFs so it'll take a lot of effort to unify them in a single API
