### ISSUE TITLE
CI - DB Integration - Live  is not running tests

### ISSUE THREAD

**Issue by yafimvo** [ploomber/jupysql#491]
I just noticed our CI integration is not running the actual tests but just prints the sqlachemy version (live and local)

![image](https://github.com/ploomber/jupysql/assets/103026689/6b908d42-ae6f-4bac-9ec4-7bcd28957afb)

It should be something like this (see the running time and the output)

![image](https://github.com/ploomber/jupysql/assets/103026689/8e27b551-8e66-467e-8182-17506b259fb9)

My guess is it's something with the syntax which runs only the first part and ignores the second

```
python -c "import sqlalchemy; print('Sqlalchemy version ', sqlalchemy.__version__)"
pytest src/tests/integration --verbose
```

cc: @idomic @edublancas

**Comment by edublancas** [comment]
thanks for spotting this! looks like @tonykploomber already started working on a fix

**Comment by tonykploomber** [comment]
We need to run SQLAlchemy 1.4 to perform snowflake integration testing
