### ISSUE TITLE
Fix Parameterizing SQL queries in docs

### ISSUE THREAD

**Issue by tonykploomber** [ploomber/jupysql#497]
Context:
@neelasha23 found there are syntax issues with parameterizing SQL queries in some docs
For example:
https://jupysql.ploomber.io/en/latest/api/magic-sql.html#programmatic-sql-queries

<img width="828" alt="Screenshot 2023-05-19 at 4 44 45 PM" src="https://github.com/ploomber/jupysql/assets/123580782/fed1a49a-532c-42ef-9fb5-82cbf104d5de">

Root cause:
We no longer support `{variable}` or `$variable` fashion, we should use `{{variable}}` instead

AC:
Change all docs' section use {variable}` or `$variable` part to  `{{variable}}`

**Comment by edublancas** [comment]
looks like this has been fixed in #496? @neelasha23

**Comment by neelasha23** [comment]
It was fixed. This issue was in place to do a final check and confirm that no other tutorial contains `$` expansion
