### ISSUE TITLE
DuckDB version pinned

### ISSUE THREAD

**Issue by neelasha23** [ploomber/jupysql#498]
With DuckDB 0.8.0 version we are facing some issues like order of tuples in query result getting changed, thus affecting the downstream tasks. 
Pinning version to 0.7.1 for now till this gets fixed.

**Comment by tonykploomber** [comment]
I guess this is the same issue as https://github.com/ploomber/jupysql/issues/495

Thanks @neelasha23 for more context on this

**Comment by edublancas** [comment]
let's check if the tests still break with newer versions. if so, we should update our tests (since we should aim to run with the most recent duckdb release)
