### ISSUE TITLE
empty table should show its columns like pandas

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#50]
According [to this](https://github.com/catherinedevlin/ipython-sql/issues/125), we should support a similar structure to pandas when it comes to an empty response, show an empty table with the headers (column names).

**Comment by edublancas** [comment]
Agree. In general, the current output format and style have a lot of room for improvement. We can inspire by pandas since many practitioners are already familiar with it.

**Comment by idomic** [comment]
There's a pending PR for documenting this.

**Comment by idomic** [comment]
@psychemedia
We just updated the docs and released a new version( [0.5.2 changelog](https://github.com/ploomber/jupysql/blob/0.5.2/CHANGELOG.md)).
Make sure to [join our slack](https://ploomber.io/community/) for more info and support
