### ISSUE TITLE
check commands where we have `--table`

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#519]
(this is blocked by https://github.com/ploomber/jupysql/issues/518)

- there are a few commands that take `--table` as an argument, however, some of them don't expose a `--schema`, we need to add it
- users might inadvertently pass something like `--table schema.table`, which should work as well (just like passing `--schema schema --table table`)

my guess is that the underlying functions already expose a schema argument so it's just exposing `--schema` and then passing it to the underlying function. but we'll have to check

**Comment by bbeat2782** [comment]
Acceptance Criteria
1. Ensure `%sqlcmd` arguments that take `--table` also accepts `--schema`
2. For those arguments, ensure `--table schema.table` also works
3. Add test function
4. Modify documentation
