### ISSUE TITLE
Init connections once per session for testing

### ISSUE THREAD

**Issue by mehtamohit013** [ploomber/jupysql#534]
Currently, when testing  jupysql, there are many tests, which initialize their own connections for every single test case like [`src/tests/test_magic_plot.py::test_sqlplot`](https://github.com/ploomber/jupysql/blob/26e3a074d815ba998769a279c24dc143729e9999/src/tests/test_magic_plot.py#L115) at [this](https://github.com/ploomber/jupysql/blob/26e3a074d815ba998769a279c24dc143729e9999/src/tests/test_magic_plot.py#L154), even though a connection to the database has already been made in a test earlier

Even though `pytest.parametrize` parallelize the tests, I think one way it might be improved is by using `pytest.fixture` in conjunction with the `scope` argument. Most probable `session` or `module` (may be `package`) level will do(needs more research)

@edublancas

**Comment by edublancas** [comment]
I think the tests you're showing are only using DuckDB. Since DuckDB is a local database, it's OK to open a new connection (we're creating an entirely new database) because that ensures better isolation.

Unless this is causing any issues, we can keep it.
