### ISSUE TITLE
update docs to use `--alias`

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#538]
the intro guide: https://jupysql.ploomber.io/en/latest/intro.html#assignment

still shows the old way to switch connections via `user@db` (`%%sql will@shakes`)

we should update this to use the new `--alias` feature: https://jupysql.ploomber.io/en/latest/howto.html#switch-connections

**Comment by tl3119** [comment]
I have updated the document and submitted a pull request. Please check!

**Comment by edublancas** [comment]
can you share the link to the PR? I cannot find it

**Comment by tl3119** [comment]
The PR is the same with https://github.com/ploomber/jupysql/pull/561 this one. Sorry, I don't know why it automatically goes to the same PR after I push it.

**Comment by edublancas** [comment]
you need to create separate branches, then open PRs from those separate branches

**Comment by tl3119** [comment]
> you need to create separate branches, then open PRs from those separate branches

Please check here: https://github.com/ploomber/jupysql/pull/574

**Comment by edublancas** [comment]
fixed by https://github.com/ploomber/jupysql/pull/574
