### ISSUE TITLE
buggy behavior in `%config SqlMagic.style`

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#54]
I was testing the `%config SqlMagic.style` and realized it doesn't work well:

![image](https://user-images.githubusercontent.com/989250/210159423-e52665d2-f0e3-437f-9324-cce084fa49bb.png)

sometimes the text representation is empty, and changing the style does not affect it.

sample code:

```python
%sql sqlite://
```

```python
%%sql
CREATE TABLE languages (name, rating, change);
INSERT INTO languages VALUES ('Python', 14.44, 2.48);
INSERT INTO languages VALUES ('C', 13.13, 1.50);
INSERT INTO languages VALUES ('Java', 11.59, 0.40);
INSERT INTO languages VALUES ('C++', 10.00, 1.98);
```

```python
%config SqlMagic.style = "PLAIN_COLUMNS"
%config SqlMagic.style = "RANDOM"
%config SqlMagic.style = "DEFAULT"
result = %sql SELECT * FROM languages LIMIT 2
print(result.pretty.get_string())
```

**Comment by edublancas** [comment]
note that this is code we inherited from [ipython-sql](https://github.com/catherinedevlin/ipython-sql) so we don't even know what the purpose is or how it should work.

**Comment by AnirudhVIyer** [comment]
On it!
