### ISSUE TITLE
add padding to table explorer

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#540]
the buttons in the table explorer (https://github.com/ploomber/jupysql/pull/420) are hidden by the horizontal scrollbar, making it difficult to click, we need to add some padding:

![Screenshot 2023-05-29 at 2 57 52 p m](https://github.com/ploomber/jupysql/assets/989250/af6c2eb6-419a-4893-b40b-a10b7f5d5910)

**Comment by edublancas** [comment]
@yafimvo: it the CSS logic implemented here or in the jupysql-plugin repo?

**Comment by yafimvo** [comment]
@edublancas [here](https://github.com/yafimvo/jupysql/blob/table_explorer/src/sql/widgets/table_widget/css/tableWidget.css). 
Everything related to the `TableExplorer` widget is in this project (jupysql).
