### ISSUE TITLE
jupyterlab check not working

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#541]
---

TO DO:

- [ ] remove this if statement: https://github.com/ploomber/jupysql/blob/461a5b5783735817189d77cd3378c8c23aa38403/src/sql/widgets/table_widget/table_widget.py#L158
- [ ] remove the is_jupyterlab_session function
- [ ] remove psutil from setup.py

---

I test it on binder and my local JupyterLab and I found that the method isn't working as expected.

Local (doesn't recognize jupyterlab):

![image](https://github.com/ploomber/jupysql/assets/989250/d50fdc39-ce51-4857-8496-03196c346900)

Binder (recognizes JupyterLab but via the env variables, not due to psutil):

![image](https://github.com/ploomber/jupysql/assets/989250/16994be1-93e8-47d2-bf00-83c036d7971b)

Is the JupyterLab check only required to tell the user they need jupysql-plugin? If so (and given that the method isn't working), maybe we can require all users to install jupysql-plugin (even if not required for jupyter notebook users), doing so will help us remove psutil

PR: https://github.com/ploomber/jupysql/pull/420

**Comment by edublancas** [comment]
@yafimvo: thoughts?  if we require jupysql-plugin even for jupyter notebook users, would that break it for them?

**Comment by yafimvo** [comment]
interesting. I guess it's something with the OS since it's working on my environment.

> Is the JupyterLab check only required to tell the user they need jupysql-plugin? If so (and given that the method isn't working), maybe we can require all users to install jupysql-plugin (even if not required for jupyter notebook users), doing so will help us remove psutil

Yes, we need it for the message.
I think it's a good idea. Instead of showing `ModuleNotFoundError` we can show a message (using HTML) to install jupysql-plugin. Then, we can check if it's JupyterLab and if the plugin is installed using javascript. If it's not JupyterLab we can hide the message.

**Comment by edublancas** [comment]
wouldn't just removing the conditional `is_jupyterlab` be easier? we'll force jupyter notebook users to install jupyter-plugin but sounds like nothing would break
