### ISSUE TITLE
migrate user feedback to use display module

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#548]
we might still have some print statements to display user feedback, we should migrate them to use the new display module: https://github.com/ploomber/jupysql/pull/432

**Comment by anupam-tiwari** [comment]
For this one, should I replace all print statements with display module?

**Comment by edublancas** [comment]
yes, all print statements which are meant to the end-user should be replaced (I think it's all of them but open an PR and I can provide feedback in case there are any exceptions)

**Comment by edublancas** [comment]
any progress here? @anupam-tiwari

**Comment by anupam-tiwari** [comment]
working on it!
