### ISSUE TITLE
Deprecating SQL in the line cell

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#550]
We keep finding issues when validating the user's input in the line cell. The problem is that the line cell needs to parse arguments, but it might also contain SQL code: e.g.,:

```
%sql SELECT * FROM table --some-arg --another-arg
```

There are two problems with this:

1) The above cell is ambiguous because `--some-arg` and `--another-arg` can be interpreted as either a) arguments for `%sql` or b) comments in a SQL query. So we have to be cautious in terms of validation. Which leads to problems like this: https://github.com/ploomber/jupysql/issues/531

2) The second problem is the SQL query itself, the parsing logic becomes a bit tricky because the SQL query might be at the beginning, end, contain spaces, etc.

I personally never use `%sql` for running SQL, I only use it for running commands like listing connections `%sql --connections`. So I propose no longer accepting SQL code in `%sql`. This is a big change so we should discuss it internally and ask the community what they think.

A not-so-drastic solution would be to fix 1 (but not 2) by always interpreting `--something` as an argument (essentially disallowing SQL comments in the line cell `%sql`)

**Comment by edublancas** [comment]
let me know what you think: @idomic @yafimvo @neelasha23 @tonykploomber

**Comment by neelasha23** [comment]
I personally find the cell magic `%%sql` more convenient than the line magic.
Is there a way to find out how many times the `%sql` has been used? I guess users would usually be running more complex multiline queries more often than single line ones

**Comment by yafimvo** [comment]
I agree with @idomic and @neelasha23. I use `%sql` for simple queries ("one line queries" e.g. select * from table), but for more complex (e.g. create and insert, conditions, join etc...) `%%sql` is easier.

**Comment by edublancas** [comment]
thanks for your feedback! sounds like this change is too much. Maybe we can implement only the second point (assume everything that looks like `--something`) is a CLI argument, not at SQL comment. I'll ask for feedback from our community and then we can decide.
