### ISSUE TITLE
modify CI to skip tests if only doc has been modified

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#575]
follow up for: https://github.com/ploomber/pkgmt/issues/47I released pkgmt 0.6 with the functionality from such PR. Now we need to modify the [CI](https://github.com/ploomber/jupysql/blob/master/.github/workflows/ci.yaml) so the tests are skipped if only the `doc/` directory has been modified. We should implement it between the lint and installation step: https://github.com/ploomber/jupysql/blob/0fae02a1985c10c95300586e9110ae51b2db2165/.github/workflows/ci.yaml#L40 (note that there are two similar steps since we are testing against sqlalchemy 1 and 2)

**Comment by edublancas** [comment]
https://github.com/ploomber/jupysql/pull/577 did not work

I opened a PR that only modified doc and the tests were still executed: https://github.com/ploomber/jupysql/pull/580

https://github.com/ploomber/jupysql/actions/runs/5192405560/jobs/9361521351

**Comment by edublancas** [comment]
@mehtamohit013: please test this in the dummy repo (I think you have admin permissions), let's ensure it works there before testing it here

**Comment by mehtamohit013** [comment]
I have tested it, it works; [Link](https://github.com/ploomber/pkgmt/pull/49#issuecomment-1576797242). Let me check what has gone wrong.

**Comment by edublancas** [comment]
we shouldn't be using `fetch-depth: 0` as it'll copy the entire git history. and we only need access to the latest commit in the master/main branch. there must be a way to do it without copying the entire repository
