### ISSUE TITLE
Issue on page /howto/format-sql.html: Format SQL” button does not appear in JupyterLab

### ISSUE THREAD

**Issue by rickiesmooth** [ploomber/jupysql#611]
I'm not sure what I'm doing wrong, but I'm unable to format sql after I installed the `jupysql-plugin`.

I've installed the package and restarted my kernel:

![Screenshot 2023-06-12 at 11 22 28](https://github.com/ploomber/jupysql/assets/7207783/fac1d8c9-6c96-4e5b-8c45-dddea9c244a4)

**Comment by tonykploomber** [comment]
After installing the `jupysql-plugin`, can you kill the current Jupyter process and restart?

```
pip install jupysql-plugin
jupyter-lab
```

**Comment by rickiesmooth** [comment]
I'm not very handy with jupyter, how do I kill the Jupyter process and restart?

**Comment by edublancas** [comment]
can you check which version of jupyter you're running? I think there are some compatibility issues with jupyterlab 4.

in your terminal you can do:

```
pip freeze
```

and look up jupyterlab

I think you can also do it from jupyterlab's menu. in the top bar: help -> about jupyterlab

---


this looks useful: https://learn.microsoft.com/en-us/answers/questions/46614/azure-machine-learning-and-jupyterlab-git-extensio

the comment at the bottom shows how to restart jupyterlab

**Comment by edublancas** [comment]
This might be a problem with how Azure notebooks work. jupysql-plugin must be installed in the Jupyter server, not in the kernel. Unfortunately, I don't have experience with Azure notebooks so I'm unsure how to fix it.

We've had similar problems with the ploomber plugin (another library we develop), so you might wanna check the documentation: https://docs.ploomber.io/en/latest/user-guide/jupyter.html#activating-the-jupyter-extension
