### ISSUE TITLE
Integration Testing Issue - Mariadb

### ISSUE THREAD

**Issue by tonykploomber** [ploomber/jupysql#614]
[Source](https://github.com/ploomber/jupysql/pull/607)

We are seeing the integration testing is failing on that PR, I tested on local and it showed 
```
 (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")
```
when connecting to mariadb.

This happened since yesterday (or few a days ago?). I tested on normal mysql and it works fine.

What I tried:
- Tried to downgrade the mariadb container version to 10.4, failed
- Tried to downgrade the sqlalchemy version to 2.0.15, failed

Need to investigate more

**Comment by edublancas** [comment]
if we find out that it's a docker image version problem, let's pin one that's working so we don't have this issue again

**Comment by tonykploomber** [comment]
I suspect the issue is they (mariadb docker) released recently:
https://github.com/MariaDB/mariadb-docker/pull/510

**Comment by edublancas** [comment]
then switching to an old image should fix it.

**Comment by grooverdan** [comment]
Hi, I'm trying to work out the MariaDB issue you had with the Docker Official Images. I assume its something that happened on `:latest` / `11.0.2`? Was it the removed `mysql*` named executable or something else?

I found https://github.com/ploomber/jupysql/actions/runs/5248219154/jobs/9479419853 as connection errors. Is the container failing to start or are the tests starting before the container is ready?

If the later there is a `healthcheck.sh` script in the container that can help with this ([docs](https://mariadb.com/kb/en/using-healthcheck-sh-script/)).  If you need help [just ask](https://github.com/mariaDB/mariadb-docker/issues).
