### ISSUE TITLE
move feature from `%sqlrender`  -> `%sqlcmd snippets`

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#647]
we're going to deprecate `%sqlrender`, we should move the logic to `%sqlcmd snippets`

currently, this is how it works:

```
%%sql --save penguins
select * from penguins.csv limit 10
```

```
%%sql --save subset
select * from penguins where island is not null
```

```
cte = %sqlrender subset
print(cte)
```

prints:

```
WITH penguins AS (
select * from penguins.csv limit 10
)
select * from penguins where island is not null
```

Now, with the change, we should get the same when executing: `%sqlcmd snippets subset`

i.e., 

```
cte = %sqlcmd snippets subset
print(cte)
```

should print:

```
WITH penguins AS (
select * from penguins.csv limit 10
)
select * from penguins where island is not null
```

**Comment by bbeat2782** [comment]
Acceptance Criteria:
1. Make `%sqlcmd snippets {name}` gives the same output as `%sqlrender {name}`
2. Add FutureWarning to `%sqlrender {name}` that includes a link to `%sqlcmd snippets` documentation
3. Update `%sqlcmd snippets` documentation under API Reference tab to include explanation and behavior of `%sqlcmd snippets {name}`
4. Add test functions for testing `%sqlcmd snippets {name}`

**Comment by edublancas** [comment]
> Add FutureWarning to %sqlrender {name} that includes a link to %sqlcmd snippets documentation

should also include the equivalent command. e.g., if user ran `%sqlrender stuff`, then the warning should tell the user to migrate to `%sqlcmd snippets stuff`

**Comment by bbeat2782** [comment]
> 

Okay. I will include that in the error message that the FutureWarning shows.
