### ISSUE TITLE
use display module when generrating CTE

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#649]
when generating a CTE, we mention the user which snippets we're using:

![image](https://github.com/ploomber/jupysql/assets/989250/b2d9487a-b04c-418e-8030-ba51e0ee3c2b)

`Generating CTE with ...`

we should change the message so it uses the display.py module

**Comment by tonykploomber** [comment]
Maybe I missing something, but why `Generating CTE using display.py module` message will be more informative?

**Comment by tonykploomber** [comment]
@edublancas Can you confirm with the requirement for this one?

**Comment by edublancas** [comment]
@tonykploomber: https://github.com/ploomber/jupysql/pull/683#pullrequestreview-1504279363
