### ISSUE TITLE
proposal: `%sqlcmd test`

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#65]
Often, practitioners need to evaluate the quality of their data (e.g., no NULLs, values within range, etc.). We could create a new magic for rapid testing:

```
%sqlcmd test --table data --column numbers --within 0,100 --type float
%sqlcmd test --table data --column names --no-nulls
%sqlcmd test --table data --column birth_date --strictly-greater-than 0
```

**Comment by edublancas** [comment]
this issue also involves some preliminary research to know what API makes sense and what tests we should implement. package such as dbt and great expectations can help here to get some inspiration

**Comment by Palashio** [comment]
what does the current `sqlcmdmagic` do? loading it doesn't work locally for me.

**Comment by tonykploomber** [comment]
This is closed by https://github.com/ploomber/jupysql/pull/266
