### ISSUE TITLE
error when using create table

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#651]
when using `--save` and then executing a CREATE table statement, I get an error.

more context: [create-table-bug.ipynb.zip](https://github.com/ploomber/jupysql/files/11841951/create-table-bug.ipynb.zip)

**Comment by anupam-tiwari** [comment]
on it!

**Comment by edublancas** [comment]
@anupam-tiwari please work on this

**Comment by edublancas** [comment]
please post your thoughts/progress so we can share our feedback @anupam-tiwari

**Comment by nooodle-soup** [comment]
I have made a fix for this but have a few ideas that can make it possible to run the CREATE queries with the snippets. Should I implement them here or open a new issue for it?
