### ISSUE TITLE
error when using `--save` and writing a CTE

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#652]
(similar to https://github.com/ploomber/jupysql/issues/651, let's work on that one first)

more context: [create-table-bug-2.ipynb.zip](https://github.com/ploomber/jupysql/files/11841977/create-table-bug-2.ipynb.zip)

**Comment by nooodle-soup** [comment]
Hey @edublancas 
I checked out the file and only the last cell is still creating an error when I ran it. Please confirm if it is the same for you. The last second cell error seems to have been resolved by a previous update.

**Comment by edublancas** [comment]
if the first example has been fixed, just make sure we have a unit test for it (it might be in the test_magic.py file. And then focus on fixing the second case

**Comment by nooodle-soup** [comment]
Still working on the first one
Unsure where to start
#651 brought me here so thought to check it if I can find a lead

**Comment by nooodle-soup** [comment]
@edublancas Do we want to show a warning or an raise an error if we are disabling the CTE when a saved snippet is used in the expression?

**Comment by edublancas** [comment]
we show a warning
