### ISSUE TITLE
exporting `--save name` to `jupysql-snipptets/name.sql`

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#653]
context: [notebooks-and-sql.ipynb.zip](https://github.com/ploomber/jupysql/files/11842021/notebooks-and-sql.ipynb.zip)

**Comment by edublancas** [comment]
> Add --persist_snippets config to SqlMagic

should be `--persist-snippets`, not `--persist_snippets`

> Edit SqlMagic such that if args.save and --persist_snippets is True, snippet is saved in a new directory jupysql-snippets/ for the users to access.

Should be `%condif SqlMagic.persist_snippets` not `args.save`

**Comment by AnirudhVIyer** [comment]
> > Add --persist_snippets config to SqlMagic
> 
> should be `--persist-snippets`, not `--persist_snippets`
> 
> > Edit SqlMagic such that if args.save and --persist_snippets is True, snippet is saved in a new directory jupysql-snippets/ for the users to access.
> 
> Should be `%condif SqlMagic.persist_snippets` not `args.save`

Hey, 
- So in SqlMagic, persists_snippets is a variable, so cannot have hyphen in the name, it is throwing an error. 
- if `%config SqlMagic.persist_snippets = True` and then a user uses the `--save ` argument we are saving the snippet in an sql file. Is this right or there is something else that we want to do?

**Comment by edublancas** [comment]
> So in SqlMagic, persists_snippets is a variable, so cannot have hyphen in the name, it is throwing an error.

you're right. this is a config setting, underscores are fine

> if %config SqlMagic.persist_snippets = True and then a user uses the --save argument we are saving the snippet in an sql file. Is this right or there is something else that we want to do?

you're correct. that's what we want to do
