### ISSUE TITLE
tasks triggered when only modifying changelog and doc/

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#661]
I realized that unit tests are triggered even though I only modified doc/ and CHANGELOG.md: https://github.com/ploomber/jupysql/pull/660

my understanding is that if my PR only modifies the CHANGELOG.md or files within doc/ tests should not run

![image](https://github.com/ploomber/jupysql/assets/989250/258054a0-00fc-478d-806f-ac43599fcd18)

seem like this line (https://github.com/ploomber/jupysql/blob/aa360f9505c7b0e3ad8968cf38b2ccfc9df9d4a1/.github/workflows/ci.yaml#L77) which appears in a few places is not correctly getting the exit code from the step that determines if only doc/ or changelog.md have been modified

**Comment by anupam-tiwari** [comment]
does this work?: 

```
    if: needs.preliminary.outputs.check_doc_modified == 'failure' && !contains(github.event.head_commit.modified, 'CHANGELOG.md') && !contains(github.event.head_commit.modified, 'docs/')
```

**Comment by mehtamohit013** [comment]
@edublancas 
Ths test shouldn't give a failure as excluding `doc` and `CHANGELOG.md` nothing has been modified. I will look into it and check it out on dummy repo.

**Comment by mehtamohit013** [comment]
Can i get access to create a branch in the repo? It will be easier for me to debug, because pkgmt tests are working.

**Comment by edublancas** [comment]
jupysql repo? you have write access. I think that will allow you to push new branches. but let me know
