### ISSUE TITLE
Disable tracking analytics

### ISSUE THREAD

**Issue by tekumara** [ploomber/jupysql#664]
Whilst using jupysql I was surprised to see tracking analytics being sent to posthog.com:
```
INFO:backoff:Backing off send_request(...) for 0.8s (requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='app.posthog.com', port=443): Read timed out. (read timeout=15))
```

Can this be disabled?

**Comment by neelasha23** [comment]
Please try this: https://docs.ploomber.io/en/latest/community/user-stats.html
