### ISSUE TITLE
Loss of :a functionality from ipython-sql

### ISSUE THREAD

**Issue by ccrook** [ploomber/jupysql#671]
I am just migrating from ipython-sql and find that the change in variable substitution appears to have reduced simplicity and usability of the sql extension.  The notes in #137 state:

> Please aware the variable substition as {a}, $a, and :a format has been deprecated.  Use {{a}} instead.

But {{a}} appears to be a simple string substitution, which is a very different functionality to that provided by :a, which ensures that the variable is safely quoted for insertion into SQL.  Using {{a}} instead does not seem to work.

For users using the sql extension to created SQL focussed notebooks with minimal python (essentially documenting queries) this now means that the simple variable substitution must be replaced with code to quote and escape strings.  For example the following code breaks:

```
id=42
name='arthur'
%sql create table test(id integer, name varchar(30));
%sql insert into test values (:id,:name)
```

Is there something I have missed in the documentation that handles this common use case.

**Comment by edublancas** [comment]
thanks for your feedback!

We deprecated the old behavior because having three ways of doing parameter interpolation was confusing. Furthermore, the `:variable` syntax was causing issues with some DuckDB queries.

Honestly, I never thought about the use case you're mentioning, and I considered it confusing that `:variable` would quote strings while the others passed the value as is.

But we can work on bringing this feature back. Do you have any recommendations?

I think we could do something like:

- `{{variable}}`: substitute the variable as is
- `[[variable]]`: quotes and escapes if needed

thoughts?

**Comment by ccrook** [comment]
@edublancas Thanks for looking at this.  

I'm not familiar with DuckDB so not sure what constraints that might impose on implementation.  I'm a long time fan of SQLite but looks like DuckDB may be a good option for some of my work, so very interesting pointer!

In terms syntax, that may be a bit harder.  I think [] is probably not suitable as it is extensively used in PostgreSQL arrays and would conflict with nested arrays in SQL.  That said, there probably are not many escape sequences that are not used in some variant of SQL.  

Since jupysql is already processing {{ }} I wonder if the best solution might be to use something within the {{ }} expansion.  Possibly this could borrow from ipython and use {{:variable}} - though given it is going to change in any case maybe something like {{$variable}} would be appropriate?

**Comment by rnarkk** [comment]
Please de-deprecated `:variable` substitution, as this is the most beautiful notation of the four `:variable`, `{a}`, `{{a}}` and `$a`, and widely used across various DBs and APIs ecosystem. This hinders our migration from `ipython-sql` to `jupysql`.

**Comment by edublancas** [comment]
hi all, many thanks for your feedback. we keep getting observations around this so we've decided to get this back

**Comment by ellipticview** [comment]
Glad this will be brought back. I want to emphasize that bind variables are different from substitution:

1. The SQL statement is sent to the server with bind variable placeholders, and the values for the placeholder
2. The _database server_ performs the replacement

Why is this a recommended pattern?
- It protects against sql injection
- If the same SQL statement is sent to the server again, it does not need to be parsed. The server recognizes it, gets it from the cache, replaces the bind variables and executes it. This is a performance benefit.

Then there is the syntax of the bind variables. This differs somewhat per database, but both Oracle and Postgresql use :varname.

This makes it possible to simply cut & paste a query with bind variables from the notebook into an Oracle or Postgresql SQL execution tool to test/debug/optimize.

So I'll be happy to see the previous syntax restored.

**Comment by edublancas** [comment]
the `:variable` feature is back! It'll be part of the next release 0.9 which will be out during the week!

**Comment by ccrook** [comment]
That is brilliant news!  Thankyou!!

**Comment by edublancas** [comment]
JupySQL 0.9 is out now! Here's how to use the `:variable` feature https://jupysql.ploomber.io/en/latest/user-guide/template.html#id1

I'd greatly appreciate if you can share our page https://github.com/ploomber/jupysql in your social channels so we get to 400 ⭐️!

feel free to open more issues if you have feedback and thanks for using JupySQL!
