### ISSUE TITLE
Unable to run DuckDB queries using FILTER clause on aggregates

### ISSUE THREAD

**Issue by robhawkes** [ploomber/jupysql#684]
I've recently started using jupysql alongside DuckDB to speed up and tidy up my data exploration workflows, which has been great. However, I've recently hit what I think is a bug that's preventing me from using it much more.

If I use a DuckDB query with a [`FILTER` clause](https://duckdb.org/docs/sql/query_syntax/filter) on an aggregate function then jupysql fails to produce a valid final SQL statement and complains about a missing table.

```
CatalogException: Catalog Error: Table with name first_cte does not exist!
Did you mean "pg_type"?
```

Here's an example of a very simple query that reproduced the issue for me on jupysql=0.7.9

```
import duckdb

%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

%sql duckdb:///:memory:

%%sql --save first_cte --no-execute
SELECT 1 AS column1, 2 AS column2

%%sql --save second_cte --no-execute
SELECT
  sum(column1),
  sum(column2) FILTER (column2 = 2)
FROM first_cte

%%sql
SELECT * FROM second_cte
```

If I run that in a notebook then I get the catalog error above, but if I run the same query in DBeaver then it returns the correct results

<img width="676" alt="CleanShot 2023-06-28 at 10 32 18@2x" src="https://github.com/ploomber/jupysql/assets/22612/0ed130c6-711b-469f-abf9-5356b133766d">

Here is the final query that is output by jupysql, which is missing the CTE due to the `FILTER`:

```
final = %sqlrender second_cte
print(final)

WITH
SELECT
  sum(column1),
  sum(column2) FILTER (column2 = 2)
FROM first_cte
```

If I remove the `FILTER` clause then the SQL is generated correctly, though obviously now missing the filter:

```
WITH first_cte AS (
SELECT 1 AS column1, 2 AS column2)
SELECT
  sum(column1),
  sum(column2)
FROM first_cte
```

**Comment by edublancas** [comment]
@neelasha23 can you look at this? looks like we have an issue with the parsing. Let's add this test case + some others and see if we can find a robust solution. If not, then we might consider bringing back `--with` for cases where the parsing fails.
