### ISSUE TITLE
auto-loading settings

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#689]
we have a bunch of [configuration settings](https://jupysql.ploomber.io/en/latest/api/configuration.html) that users can tweak. However, to change them, users have to put them in all their notebooks.

A better alternative would be to let them define the config project-wide in a pyproject.toml file (which is becoming standard in the Python ecosystem).

Example, a sample pyproject.toml could look like this:

```toml
[tool.jupysql.SqlMagic]
feedback = true
autopandas = true
```

Note that we should recursively look for the `pyproject.toml`, you can copy [this function](https://github.com/ploomber/pkgmt/blob/9b77f352438fb3c2d9f49267ce49b1bdfea3be8d/src/pkgmt/hook.py#L20).

This behavior should be triggered when loading the extension. e.g., running `%load_ext sql` should display a message if a `pyproject.toml` is found and it should print the loaded settings and its values.

Some edge cases:

- if the option doesn't exist, we should display a message when loading the settings
- if there's a typo, we should provide a `did you mean {x}?` hint in the message (e.g., `fedback` instead of `feedback`)
- if assigning the value throws an error, we should show a message and tell the user, the default value will be used

e.g., the user has `autopandas="not-a-valid-value"`

**Comment by bbeat2782** [comment]
Acceptance Criteria
1. Running `%load_ext sql` triggers `pyproject.toml` file and displays a message that it found the file, prints out loaded settings, and changes configuration settings
2. If `pyproject.toml` does not exist, it displays a message
3. If there's a typo on one of the settings, it displays a message hinting at what a user might intend
4. If an invalid value for setting is provided, it displays a message that it is not a valid value and uses the default value instead.
5. Add documentation for explaining setting up `pyproject.toml`
6. Add test functions

**Comment by edublancas** [comment]
A few observations:


    >Running %load_ext sql triggers pyproject.toml file and displays a message that it found the file, prints out loaded settings, and changes configuration settings

This should trigger loading the file and notify the user if it found it. it should also look up in parent directories (in case the notebook is in project/notebooks/mynotebook.ipynb but the config file is in project/pyproject.toml)

  >  If pyproject.toml does not exist, it displays a message

No need to do anything if the file doesn't exist

> If there's a typo on one of the settings, it displays a message hinting at what a user might intend
> If an invalid value for setting is provided, it displays a message that it is not a valid value and uses the default value instead.

these two are highly related. you can use [difflib](https://docs.python.org/3/library/difflib.html#difflib.get_close_matches) if there's something in the config file (under the tool.jupysql.SqlMagic section) that doesn't exist, you check if there are close matches. if so, the error message should suggest the fixed version. if there are no close matches, you simply return the value in the config file and tell the user that those are invalid, and show a link to the docs

**Comment by neelasha23** [comment]
A few observations:
1. I changed `jupysql` -> `jupySql` and `%load_ext sql` worked without any error (we can add some validations on the key)
2. 
<img width="616" alt="Screenshot 2023-07-13 at 4 29 11 PM" src="https://github.com/ploomber/jupysql/assets/29096135/18239182-066f-4c4f-8185-fe11ced71539">

Here, `Setting 'feedback' into 'True'` -> `Setting 'feedback' to 'True'` or `Setting 'feedback' = 'True'`. `Setting` is getting repeated in every line. It would also be good if we can display this in the form of a table with 2 columns : `Config` and `value`.

3. If there's typo in one setting, do we allow setting the others? Currently it does.

<img width="636" alt="Screenshot 2023-07-13 at 4 33 41 PM" src="https://github.com/ploomber/jupysql/assets/29096135/261dc367-4187-435e-b566-65407c800859">

Also, should this raise an error instead of print message?

4. If duplicate keys present it shows the entire stack trace:

```
[tool.jupysql.SqlMagic]
feedback = true
autopandas = true
feedback = false
```

Stacktrace:
```

File ~/miniforge3/envs/jupysql/lib/python3.10/site-packages/sql/magic.py:664, in load_configs(ip)
    662 file_path = find_toml_path()
    663 if file_path:
--> 664     configs = get_configs(file_path)
    665     config_vars = get_config_variables(SqlMagic)
    666     for config, value in configs.items():

File ~/miniforge3/envs/jupysql/lib/python3.10/site-packages/sql/magic.py:645, in get_configs(file_path)
    643 with open(file_path, "r") as file:
    644     content = file.read()
--> 645     data = toml.loads(content)
    646 try:
    647     return data["tool"]["jupysql"]["SqlMagic"]

File ~/miniforge3/envs/jupysql/lib/python3.10/site-packages/toml/decoder.py:514, in loads(s, _dict, decoder)
    511     ret = decoder.load_line(line, currentlevel, multikey,
    512                             multibackslash)
    513 except ValueError as err:
--> 514     raise TomlDecodeError(str(err), original, pos)
    515 if ret is not None:
    516     multikey, multilinestr, multibackslash = ret

TomlDecodeError: Duplicate keys! (line 4 column 1 char 58)
```

We can add some validation here.

5. We can add error here also :  
```
[tool.jupysql.SqlMagic]
autopandas = TRUE
feedback = false
```

Stacktrace:
```
File ~/miniforge3/envs/jupysql/lib/python3.10/site-packages/toml/decoder.py:514, in loads(s, _dict, decoder)
    511     ret = decoder.load_line(line, currentlevel, multikey,
    512                             multibackslash)
    513 except ValueError as err:
--> 514     raise TomlDecodeError(str(err), original, pos)
    515 if ret is not None:
    516     multikey, multilinestr, multibackslash = ret

TomlDecodeError: Only all lowercase booleans allowed (line 2 column 1 char 24)
```

6. Another one:

```
[tool.jupysql.SqlMagic]
autopandas = invalid
feedback = false
```

Stacktrace:

```
File ~/miniforge3/envs/jupysql/lib/python3.10/site-packages/toml/decoder.py:514, in loads(s, _dict, decoder)
    511     ret = decoder.load_line(line, currentlevel, multikey,
    512                             multibackslash)
    513 except ValueError as err:
--> 514     raise TomlDecodeError(str(err), original, pos)
    515 if ret is not None:
    516     multikey, multilinestr, multibackslash = ret

TomlDecodeError: invalid literal for int() with base 0: 'random' (line 2 column 1 char 24)
```
