### ISSUE TITLE
Searching for a term in the PR preview (Algolia search) redirects to the master branch docs

### ISSUE THREAD

**Issue by yafimvo** [ploomber/jupysql#692]
Searchin for a term in PR preview, i.e: https://jupysql--662.org.readthedocs.build/en/662/quick-start.html

![image](https://github.com/ploomber/jupysql/assets/103026689/edb1a8e1-c32b-4aa0-a794-ea5d03d3fa21)

Redirects to the master branch docs (https://jupysql.ploomber.io/) instead of the current PR preview docs.

**Comment by edublancas** [comment]
maybe a better alternative is to disable algolia search for PRs (and just provide the default search experience)? we can automatically add a banner saying that so users are not confused. how difficult would that be?
