### ISSUE TITLE
Variable expansion outside queries

### ISSUE THREAD

**Issue by DavideRossi** [ploomber/jupysql#699]
This is a feature request.

Use case:
```
foo = 'bar'
```
```
%%sql --save {{foo}} --no-execute
SELECT 1
```
```
result = %sql SELECT * from {{foo}}
```

**Comment by edublancas** [comment]
thanks for the feedback! I think we've gotten this request before (but can't remember if there's already an open issue), and I think it'd be pretty useful.

@ploomber/ploomber-devs any thoughts? I cannot think of any edge cases/weird scenarios we might encounter, sounds like a reasonable and useful feature
