### ISSUE TITLE
Custom connections get reset after connecting Jupysql

### ISSUE THREAD

**Issue by mehtamohit013** [ploomber/jupysql#710]
```ipython
%load_ext sql
```

```python
import duckdb
conn = duckdb.connect()

import pandas as pd
df = pd.DataFrame({"x": range(0, 5), "y": range(5, 10)})
conn.register("plot", df)
conn.sql("SELECT * FROM plot")
```
Output: 
```
┌───────┬───────┐
│   x   │   y   │
│ int64 │ int64 │
├───────┼───────┤
│     0 │     5 │
│     1 │     6 │
│     2 │     7 │
│     3 │     8 │
│     4 │     9 │
└───────┴───────┘
```

```ipython
%sql conn
%sql SELECT * FROM plot
```

Output: ` CatalogException: Catalog Error: Table with name plot does not exist!`

**Comment by edublancas** [comment]
ok, we need to investigate more because skipping `register` and querying `df` works:

```
In [1]: import duckdb
   ...: conn = duckdb.connect()
   ...:
   ...: import pandas as pd
   ...: df = pd.DataFrame({"x": range(0, 5), "y": range(5, 10)})

In [2]: %sql conn
UsageError: Line magic function `%sql` not found.

In [3]: %load_ext sql
Found pyproject.toml from '/Users/eduardo/dev/jupysql'

In [4]: %sql conn

In [5]: %sql SELECT * FROM df
Running query in 'DuckDBPyConnection'

Out[5]:
+---+---+
| x | y |
+---+---+
| 0 | 5 |
| 1 | 6 |
| 2 | 7 |
| 3 | 8 |
| 4 | 9 |
+---+---+
```

**Comment by mehtamohit013** [comment]
@edublancas 
In the above snippet, you are querying the `df` after initializing the connection. 

The issue pertains to the scenario when the user already has some table loaded into `duckdb` connection object and then use the same connection to `%sql` like `%sql conn`, then the table got deleted, but ideally it should not.

**Comment by edublancas** [comment]
ok, please check what's going on!

**Comment by mehtamohit013** [comment]
AC Criteria:

- Investigate more about the custom connection and how Jupysql handles it
- Testcases
- Documentation
- Chagelog

**Comment by edublancas** [comment]
I looked at DuckDB's docs, the docs for `register` [disappeared](https://duckdb.org/docs/api/python/overview.html). Version 0.6.1 is the latest one that has a [reference.](https://duckdb.org/docs/archive/0.6.1/api/python/overview#efficient-transfer) 

Perhaps they're deprecating this, and thus, we should ignore this problem. Can you open an issue in DuckdDB's repository? If they're thinking of deprecating this API, then we can ignore this. Otherwise, we'd have to dig further into this.

**Comment by mehtamohit013** [comment]
@edublancas 
You are right, it seems like they are no longer supporting register and using SQL commands to create table works:

```python
import duckdb
import pandas as pd

df = pd.DataFrame({"x": range(0, 5), "y": range(5, 10)})
conn = duckdb.connect(database=':memory:', read_only=False)

conn.register("plot", df)
conn.sql("SELECT * FROM plot")
conn.sql('CREATE TABLE test(i INTEGER)')
conn.sql('INSERT INTO test VALUES (42)')
new_conn = conn.cursor()

print(conn.sql('SHOW TABLES'))
print(new_conn.sql('SHOW TABLES'))
```

Output: 
```bash
┌─────────┐
│  name   │
│ varchar │
├─────────┤
│ plot    │
│ test    │
└─────────┘

┌─────────┐
│  name   │
│ varchar │
├─────────┤
│ test    │
└─────────┘
```

I have also tested with `jupysql`, it works fine

Feel free to close the issue. 
Thanks

**Comment by edublancas** [comment]
did you get a response from the duckdb team? if so, please post the issue URL so we have a record.

**Comment by mehtamohit013** [comment]
> did you get a response from the duckdb team? if so, please post the issue URL so we have a record.

So, a couple of open Duckdb issues are centered around the same `register` and `cursor` format. Their philosophy differs slightly on cursor from Python DB-API specification: [Ref-1](https://github.com/jwills/dbt-duckdb/issues/2#issuecomment-9065799590), [Ref -2](https://github.com/duckdb/duckdb/issues/1848#issuecomment-857595403)

Related issue: https://github.com/duckdb/duckdb/issues/1736 (Also, #1848, #3980, #4723)

@edublancas
