### ISSUE TITLE
show clear error when using DBAPI driver and `--persist`

### ISSUE THREAD

**Issue by mehtamohit013** [ploomber/jupysql#712]
Recently, we are trying to use native DuckDB Python API, instead of SQLalchemy. But `--persist` doesn't support custom drivers

**Comment by mehtamohit013** [comment]
Relevant PR:#707 and [comment](https://github.com/ploomber/jupysql/pull/707#issuecomment-1622050698)

**Comment by edublancas** [comment]
this makes sense because we're relying on pandas.to_sql. instead of supporting it, we can just show an error for now

> `--persist` isn't available when using a DBAPI driver

**Comment by edublancas** [comment]
this has been fixed already: DBAPI and SQLAlchemy connections implement a `to_table` method, in the DBAPI's case, it raises an exception.
