### ISSUE TITLE
Parse engine from dictionary object 

### ISSUE THREAD

**Issue by bevanj** [ploomber/jupysql#714]
I use credential manager and keyring to store and access connection details. Previously with ipython-sql, I used f strings and keyring to create my connection strings. I have created a helper library that has the connection strings in a Box (dict with ability to access via dot notation). Then I can just
`import sql_help`
`%load_ext sql`
`%sql $sql_help.PostgreSQL.host.database.user`

I understand that the expanding string method is not longer supported (#576) and I happy to use the `create_engine()` approach. 
However, I am looking for a way to add my engines to a helper library that I can just call, rather than `create_engine()` in every notebook.

`from sqlalchemy import create_engine`
`db_url = "postgresql://user:password@host/db"`
`engine = create_engine(db_url)`
`sql_eng = {"test": engine}`

then
`%sql engine`
works but this doesn't
`%sql sql_eng["test"]`
Currently, I have created the helper library and import the object and then with one extra line get it to work via
`con = sql_eng["test"]`
`%sql con`

Thanks

**Comment by edublancas** [comment]
hi, thanks for your feedback.

I'm glad you found a workaround. this is a limitation of how we parse the argument passed to `%sql`. I thin at the very least, we should show a clear error message so users know that they must pass a variable name (e.g.,  `con`)

**Comment by edublancas** [comment]
we fixed this in https://github.com/ploomber/jupysql/pull/821
