### ISSUE TITLE
implement `breaks` in histogram's ggplot

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#719]
once we close #711

we can implement breaks: https://github.com/ploomber/jupysql/pull/711#issuecomment-1626033214

**Comment by bbeat2782** [comment]
Acceptance Criteria
1. Implement `breaks` like in ggplot in R (Default should be `None`. Thus, `bins` should be used by default and use `breaks` only if a user specifies one.)
2. Add [documentation](https://jupysql--754.org.readthedocs.build/en/754/api/magic-plot.html) to explain how to use `breaks`
3. Add test functions


I have one question about the implementation. In R, when both `bins` and `breaks` are provided, `breaks` takes precedence over `bins`, so `breaks` argument is used. Do we want to replicate this or do you think raising an error is more appropriate?

**Comment by edublancas** [comment]
> I have one question about the implementation. In R, when both bins and breaks are provided, breaks takes precedence over bins, so breaks argument is used. Do we want to replicate this or do you think raising an error is more appropriate?

An error when both bins and breaks are passed is better.

**Comment by bbeat2782** [comment]
okay I will raise an error
