### ISSUE TITLE
possible autocommit failure on duckdb

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#740]
reported by a user on slack:

> is there a way to persist the duckdb table i create using jupysql

<img width="647" alt="image" src="https://github.com/ploomber/jupysql/assets/989250/bcdbfded-07a1-4403-aafc-ec1f1210ee32">

after restarting the kernel:

<img width="780" alt="image" src="https://github.com/ploomber/jupysql/assets/989250/9f6abb6f-460f-491f-aa75-a915ab8acaa8">

the user fixed it by adding a COMMIT.

**Comment by edublancas** [comment]
the autocommit feature is ON by default so we need to check what happened: https://jupysql.ploomber.io/en/latest/api/configuration.html#options

**Comment by edublancas** [comment]
sounds good!

**Comment by mehtamohit013** [comment]
Hi @edublancas,
Is this issue fixed by #725 ?

**Comment by edublancas** [comment]
good catch. yes
