### ISSUE TITLE
add support for `%sqlcmd profile` with DBAPI drivers

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#743]
`%sqlcmd profile` should work with DBAPIConnections: https://github.com/ploomber/jupysql/blob/7c1b5eaed0a7a7b787adecd2c91388146efda6e3/src/sql/connection/connection.py#L564

![image](https://github.com/ploomber/jupysql/assets/989250/1b5695d8-cf08-4a9b-a741-8edc3987cb32)

**Comment by bbeat2782** [comment]
Acceptance Criteria
1. Modify code so that `%sqlcmd profile` also works with DBAPIConnections (should show the same behavior as working with SQLAlchemy connections)
2. Add test functions for testing `%sqlcmd profile` with DBAPIConnections

**Comment by edublancas** [comment]
go ahead!
