### ISSUE TITLE
unclear logic when handling errors

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#749]
it is unclear what the logic should be in `error_message.py`.

there is a `_is_syntax_error` function that's supposedly capturing syntax errors, but it also captures things like "catalog error", "not found", and "does not exist", which doesn't seem syntax errors, but rather seem like errors displayed when the user tries to query a non-existent table (which is different than a SQL syntax error).

Since `_is_syntax_error` is used to determine whether to show the "If using snippets, you may pass the --with argument..." error message suggestion, it seems that the purpose of the function is to capture "missing table errors" as opposed to "syntax errors". In such a scenario, we shouldn't be capturing syntax errors.

I modified `test_sql_error_suggests_using_cte` in https://github.com/ploomber/jupysql/pull/746 to reflect this. some tests are marked as xfail because I'm unsure what the purpose of this code is.

**Comment by neelasha23** [comment]
These were specifically added for this testcase 
```
 %%sql --save second_cte --no-execute
SELECT
  sum(column1),
  sum(column2) FILTER (column2 = 2)
FROM first_cte
```  which was reported in [this issue](https://github.com/ploomber/jupysql/issues/684).

@edublancas

**Comment by edublancas** [comment]
yeah, I understand what the code is doing but the names of the functions is confusing. I wanted to modify the code to include other cases but I didn't since it wasn't clear where I should put certain test cases.

> there is a _is_syntax_error function that's supposedly capturing syntax errors, but it also captures things like "catalog error", "not found", and "does not exist", which doesn't seem syntax errors,

**Comment by neelasha23** [comment]
Ok. so should I just create 2 different functions for `syntax errors` and `table not found` errors?
`some tests are marked as xfail` : these also needs to be fixed as part of the issue right?
