### ISSUE TITLE
debug histograms in ggplot API

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#751]
we need to ensure that we're correctly computing the histograms. I noticed that that shapes differ vs what we see in R: https://github.com/ploomber/jupysql/pull/711#pullrequestreview-1531817150

**Comment by bbeat2782** [comment]
Acceptance Criteria
1. Modify sql query code to mimic how ggplot in R divides continuous variables into bins when plotting histogram.
2. Compare and make sure we are getting the same histograms from R and jupysql.
3. Update histogram test images.

**Comment by edublancas** [comment]
> Modify sql query code to mimic how ggplot in R divides continuous variables into bins when plotting histogram.

there's no need to ensure that our histograms match R's histograms 100%, instead we should ensure that our histograms are accurate (they plot what they're supposed to plot). It's fine if there are small differences with respect to R, but those differences should be methodical (i.e., how we compute bins), but still produce accurate histograms
