### ISSUE TITLE
improve error message when passing a non-identifier to start a connection

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#764]
we allow users to pass a connection variable to connect to a db. example:

```python
%load_ext sql

import duckdb
conn = duckdb.connect()

%sql conn
```

however, in some cases, the connection object might be part of a dictionary, list or object. examples:

```python
%sql object.property
%sql dictionary["key"]
%sql some_list[0]
```

Trying any of the above throws an error because our parser thinks it's SQL code. Instead, we should provide a more informative error:

```
"object.property" is not a valid connection identifier. Please pass the variable's name directly, as passing object attributes, dictionaries `some_dict[key]` or lists `some_list[0]` won't work. Example: `%sql connection`
```

so we need a way to identity such cases, we can use the following heuristics:

- the magic gets a single argument (no spaces between characters) - because valid SQL code will always have spaces
- we can check if the argument is not a valid identifier using `argument.isidentifier()` but it is valid Python code (using ast.parse)

if those conditions hold, then we can raise the error.

**Comment by bbeat2782** [comment]
Acceptance Criteria
1. Raise a more informative error when a connection object that is a part of object, dictionary, or list (eg. `%sql object.property`, `%sql dictionary["key"]`, `%sql some_list[0]`) is passed
a. error example : 
```
"object.property" is not a valid connection identifier. Please pass the variable's name directly, as passing object attributes, dictionaries `some_dict[key]` or lists `some_list[0]` won't work. Example: `%sql connection`
```
2. Add test functions
