### ISSUE TITLE
Issue on page /plot.html

### ISSUE THREAD

**Issue by RodolfoFerro** [ploomber/jupysql#77]
In the histogram section, the following content is shown:
<img width="664" alt="Screen Shot 2023-01-11 at 7 44 01" src="https://user-images.githubusercontent.com/8453749/211821656-0ea4eb49-f9b8-407c-8ea2-8aa957346912.png">

Since this is the _histogram_ section, the instruction must be "call `%sqlplot histogram`" instead of "call `%sqlplot boxplot`".

**Comment by edublancas** [comment]
thanks for spotting this. this is a quick change, please open a PR
