### ISSUE TITLE
add binwidth to histogram

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#784]
should work just like R's ggplot: https://ggplot2.tidyverse.org/reference/geom_histogram.html

**Comment by edublancas** [comment]
assigning it now so I don't forget but feel free to finish the existing tasks first

**Comment by bbeat2782** [comment]
Acceptance Criteria
1. Add `binwidth` argument to `geom_histogram()`. It should mimic binwidth in R ggplot.
2. Add test images
3. Add documentation

**Comment by edublancas** [comment]
sounds good!
