### ISSUE TITLE
update example to use local db

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#8]
[this example](https://jupysql.readthedocs.io/en/latest/plot.html) is connecting to a remote database; if users download it, they won't be able to run it; so we should update it to use local data.

we can use the same data as here: https://jupysql.readthedocs.io/en/latest/compose.html

**Comment by edublancas** [comment]
looks like the build is failing:  https://readthedocs.org/projects/jupysql/builds/18184333/

**Comment by RodolfoFerro** [comment]
I've opened an issue for failing builds. ( #11 )
