### ISSUE TITLE
count not displated when displaylimit=None

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#801]
### What happens?

when running a count statement, the result isn't displayed if `displaylimit=0`

### To Reproduce

notebook: [count-error.ipynb.zip](https://github.com/ploomber/jupysql/files/12340668/count-error.ipynb.zip)

session:

```python
%load_ext sql
```

```python
%sql duckdb://
```

```sql
%%sql
create table penguins as
select * from
'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv'
```

<span style="None">Running query in &#x27;duckdb://&#x27;</span>

<table>
    <thead>
        <tr>
            <th>Count</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

```sql
%%sql
select * from penguins
```

<span style="None">Running query in &#x27;duckdb://&#x27;</span>

<table>
    <thead>
        <tr>
            <th>species</th>
            <th>island</th>
            <th>bill_length_mm</th>
            <th>bill_depth_mm</th>
            <th>flipper_length_mm</th>
            <th>body_mass_g</th>
            <th>sex</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Adelie</td>
            <td>Torgersen</td>
            <td>39.1</td>
            <td>18.7</td>
            <td>181</td>
            <td>3750</td>
            <td>MALE</td>
        </tr>
        <tr>
            <td>Adelie</td>
            <td>Torgersen</td>
            <td>39.5</td>
            <td>17.4</td>
            <td>186</td>
            <td>3800</td>
            <td>FEMALE</td>
        </tr>
        <tr>
            <td>Adelie</td>
            <td>Torgersen</td>
            <td>40.3</td>
            <td>18.0</td>
            <td>195</td>
            <td>3250</td>
            <td>FEMALE</td>
        </tr>
        <tr>
            <td>Adelie</td>
            <td>Torgersen</td>
            <td>None</td>
            <td>None</td>
            <td>None</td>
            <td>None</td>
            <td>None</td>
        </tr>
        <tr>
            <td>Adelie</td>
            <td>Torgersen</td>
            <td>36.7</td>
            <td>19.3</td>
            <td>193</td>
            <td>3450</td>
            <td>FEMALE</td>
        </tr>
        <tr>
            <td>Adelie</td>
            <td>Torgersen</td>
            <td>39.3</td>
            <td>20.6</td>
            <td>190</td>
            <td>3650</td>
            <td>MALE</td>
        </tr>
        <tr>
            <td>Adelie</td>
            <td>Torgersen</td>
            <td>38.9</td>
            <td>17.8</td>
            <td>181</td>
            <td>3625</td>
            <td>FEMALE</td>
        </tr>
        <tr>
            <td>Adelie</td>
            <td>Torgersen</td>
            <td>39.2</td>
            <td>19.6</td>
            <td>195</td>
            <td>4675</td>
            <td>MALE</td>
        </tr>
        <tr>
            <td>Adelie</td>
            <td>Torgersen</td>
            <td>34.1</td>
            <td>18.1</td>
            <td>193</td>
            <td>3475</td>
            <td>None</td>
        </tr>
        <tr>
            <td>Adelie</td>
            <td>Torgersen</td>
            <td>42.0</td>
            <td>20.2</td>
            <td>190</td>
            <td>4250</td>
            <td>None</td>
        </tr>
    </tbody>
</table>
<span style="font-style:italic;text-align:center;">Truncated to <a href="https://jupysql.ploomber.io/en/latest/api/configuration.html#displaylimit">displaylimit</a> of 10.</span>

```sql
%%sql
select count(*) from penguins
```

<span style="None">Running query in &#x27;duckdb://&#x27;</span>

<table>
    <thead>
        <tr>
            <th>count_star()</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>344</td>
        </tr>
    </tbody>
</table>

```python
%config SqlMagic.displaylimit = 1
```

```sql
%%sql
select count(*) from penguins
```

<span style="None">Running query in &#x27;duckdb://&#x27;</span>

<table>
    <thead>
        <tr>
            <th>count_star()</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>344</td>
        </tr>
    </tbody>
</table>

```sql
%%sql
select * from penguins
```

<span style="None">Running query in &#x27;duckdb://&#x27;</span>

<table>
    <thead>
        <tr>
            <th>species</th>
            <th>island</th>
            <th>bill_length_mm</th>
            <th>bill_depth_mm</th>
            <th>flipper_length_mm</th>
            <th>body_mass_g</th>
            <th>sex</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Adelie</td>
            <td>Torgersen</td>
            <td>39.1</td>
            <td>18.7</td>
            <td>181</td>
            <td>3750</td>
            <td>MALE</td>
        </tr>
    </tbody>
</table>
<span style="font-style:italic;text-align:center;">Truncated to <a href="https://jupysql.ploomber.io/en/latest/api/configuration.html#displaylimit">displaylimit</a> of 1.</span>

```python
%config SqlMagic.displaylimit = None
```

<span style="None">displaylimit: Value None will be treated as 0 (no limit)</span>

```sql
%%sql
select count(*) from penguins
```

<span style="None">Running query in &#x27;duckdb://&#x27;</span>

<table>
    <thead>
        <tr>
            <th>count_star()</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

```python
%config SqlMagic.displaylimit = 0
```

```sql
%%sql
select count(*) from penguins
```

<span style="None">Running query in &#x27;duckdb://&#x27;</span>

<table>
    <thead>
        <tr>
            <th>count_star()</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

```python
%config SqlMagic.displaylimit = 1
```

```sql
%%sql
select count(*) from penguins
```

<span style="None">Running query in &#x27;duckdb://&#x27;</span>

<table>
    <thead>
        <tr>
            <th>count_star()</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>344</td>
        </tr>
    </tbody>
</table>

### OS:

macOS

### JupySQL Version:

0.10.0dev

### Full Name:

Eduardo Blancas

### Affiliation:

Ploomber

**Comment by bbeat2782** [comment]
Acceptance Criteria
1. Setting `%config SqlMagic.displaylimit = 0` or `%config SqlMagic.displaylimit = None` should display all rows when a user runs the following
```
%%sql
select count(*)
```
2. Add test functions

**Comment by edublancas** [comment]
go ahead!
