### ISSUE TITLE
showing feedback when starting a new connection

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#807]
we're currently not displaying any feedback when creating a new connection, but we should display something like "Connected to {alias}". This should be configurable and turned off when `feedback=0`

Likewise, the "switching to connection" messages should be turned off when `feedback=0`

you can get the current feedback level with: https://github.com/ploomber/jupysql/blob/master/src/sql/_current.py

**Comment by bbeat2782** [comment]
Acceptance Criteria
1. Display a `Connected to {alias}` message that is configurable with `feedback=0` when starting the first connection
2. Add test functions
