### ISSUE TITLE
Clickhouse: issue in CTE

### ISSUE THREAD

**Issue by neelasha23** [ploomber/jupysql#812]
select query failing on saved snippet.

<img width="966" alt="Screenshot 2023-08-18 at 3 45 20 PM" src="https://github.com/ploomber/jupysql/assets/29096135/437931df-17d2-4eaa-adc9-4547f4b23763">

The below query fails:
```
%%sql
SELECT * from plot_something_subset;
```

Error:

```
DatabaseException: Orig exception: Code: 62.
DB::Exception: Syntax error: failed at position 33 (line 1, col 33): (
SELECT * from plot_something_79c5bc LIMIT 3)
SELECT * from plot_something_subset;. Expected identifier. Stack trace:
```

**Comment by nooodle-soup** [comment]
Hey @neelasha23, I was unable to reproduce the error.

I used the code from jupysql docs for [clickhouse](https://jupysql.ploomber.io/en/latest/integrations/clickhouse.html) to load the `taxi` table.

I used the following sequence of queries to check the whether I am able to reproduce the error or not.

```
%sql SELECT * FROM taxi;
```
```
%%sql --save taxi_subset
SELECT * FROM taxi LIMIT 3;
```
```
%%sql
SELECT * from taxi_subset LIMIT 3;
```

I used these to mirror your queries and they seemed to work fine. Please check on your end and let me know if you get the same result.

**Comment by neelasha23** [comment]
The clickhouse CTE tests were failing : Please check this file: https://github.com/ploomber/jupysql/blob/master/src/tests/integration/test_clickhouse.py

Remove the `@pytest.mark.xfail(reason="issue with plotting from snippet #811")` line and check if tests are passing now

**Comment by nooodle-soup** [comment]
@neelasha23 I checked the tests and they all passed
You can look at the pull request I drafted for the tests #885
