### ISSUE TITLE
make toml optional

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#825]
### What happens?

if there is a pyproject.toml file but the toml package isn't installed. initializing jupysql fails:

```
[... long traceback]

ModuleNotFoundError: 'toml' is required to use 'load_toml'. Install with: pip install 'toml'
```

Instead we should display a message saying that a pyproject.toml was found but that the toml dependency isn't installed.so if the user wants to load the settings, they must install the toml package

### To Reproduce

create  pyproject.toml and start the extension, ensure the toml package is not installed

### OS:

macOS

### JupySQL Version:

0.10.0dev

### Full Name:

Eduardo Blancas

### Affiliation:

Ploomber

**Comment by bbeat2782** [comment]
Acceptance Criteria
1. If pyproject.toml file is found but the toml package isn't installed, a message should show up instead of the ModuleNotFoundError.

**Comment by edublancas** [comment]
go ahead!
