### ISSUE TITLE
Filterting/sorting on output iframe

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#83]
If we put the output into an iframe or dataframe, we can sort on different columns, and filtering can come next.

**Comment by idomic** [comment]
[This tool](https://github.com/mwouts/itables) can allow us those abilities pretty easily

**Comment by edublancas** [comment]
I think this feature would be very limiting if it only filters and sorts based on the query output, example, if I run:

```sql
select * from table limit 10
```

would sorting/filtering only work on such 10 rows?

It'd be better to have something that looks at the entire table, maybe like:

```
%%sqlexplore --table table
```

this can display a widget to allow me to filter, sort, etc. but in the whole table

**Comment by idomic** [comment]
How do you run complex queries with this?

```
%%sqlexplore --table table
```

**Comment by edublancas** [comment]
> I think those interactive tables should be embedded to all outputs tbh.

that's my original point. If my query has a `LIMIT 5`, would it only filter based on those five rows?

**Comment by idomic** [comment]
That's an edge case we should deal with.

What are you suggesting?

**Comment by edublancas** [comment]
I wouldn't consider this an edge; it'll always happen. A query might not have a `LIMIT`, but when querying data from a database, you often only retrieve a handful of rows (say, 1000); I won't see much benefit in filtering in such small subset.

It'd be better if the filtering mechanism would search in the full table, by programmatically writing the queries.

**Comment by idomic** [comment]
> It'd be better if the filtering mechanism would search in the full table, by programmatically writing the queries.

I agree, I think we're mixing here 2 different things, filtering can be a SQL text box, and there should also be quick buttons like this package allows, for sorting, showing X number of rows etc. I'm not sure if a filtering box is part of this package, and that's probably the next level of this issue to keep it small.

**Comment by idomic** [comment]
Looks like they do have this search box. (top right)
<img width="869" alt="Screen Shot 2023-01-24 at 8 36 51 AM" src="https://user-images.githubusercontent.com/11596985/214309044-cbdf013c-75b5-4a0b-97e7-974cb175b092.png">

**Comment by edublancas** [comment]
closing in favor of https://github.com/ploomber/jupysql/issues/330
