### ISSUE TITLE
[duckdb] SUMMARIZE tbl; doesn't return anything

### ISSUE THREAD

**Issue by alejandrob17** [ploomber/jupysql#836]
### What happens?

When the following command is executed:

`%sql SUMMARIZE tbl;` 

using DuckDB, no results are being returned. Unlike previous versions, where the expected results were returned as outlined in the documentation https://duckdb.org/docs/guides/meta/summarize, the current version displays a progress bar and yields an empty dataset with a column named "Success".  

### To Reproduce

```
import duckdb
import pandas as pd

%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

%sql duckdb:///:default:
```
```
%%sql 
CREATE OR REPLACE TABLE t1(
    id INTEGER,
    x INTEGER);

```
```
%%sql
INSERT INTO t1 VALUES (1, 5), (2, -1), (3, 101);

```
`%sql SUMMARIZE t1;`

### OS:

wsl2

### JupySQL Version:

0.10.0

### Full Name:

Alejandro Bolaños

### Affiliation:

Universidad Buenos Aires

**Comment by edublancas** [comment]
@bbeat2782 can you check this? I think this might be related to some scenarios where we have to check the type of statement the user is running, we might not be correctly handling the `SUMMARIZE` command. see: https://github.com/search?q=repo%3Aploomber%2Fjupysql%20is_select&type=code

**Comment by edublancas** [comment]
hey @alejandrob17 we've merged a PR that fixes it, if you get a chance, please install JupySQL from the master branch and try it out. we'll release this next week!
