### ISSUE TITLE
update outdated documentation page

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#838]
we're recommending using string.Template for parametrizing queries: https://jupysql.ploomber.io/en/latest/api/magic-sql.html#templated-sql-queries we should update it similar to this: https://jupysql.ploomber.io/en/latest/user-guide/template.html

here, we're using `--with`: https://jupysql.ploomber.io/en/latest/api/magic-sql.html#compose-large-queries but that's optional now. the example should work if we remove it

**Comment by bbeat2782** [comment]
Acceptance Criteria
1. Replace example using `{{variable}}` to use `string.Template`
2. Remove `--with` and ensure it still works
