### ISSUE TITLE
Invalid Input Error

### ISSUE THREAD

**Issue by neelasha23** [ploomber/jupysql#840]
When running a select query without running the dataset download step I get error that file not found. 

<img width="1018" alt="Screenshot 2023-08-28 at 4 56 25 PM" src="https://github.com/ploomber/jupysql/assets/29096135/555ab0ac-f3d1-4c36-8248-7df98b759564">

However, even after running the download step and rerunning I get the below error:

<img width="1181" alt="Screenshot 2023-08-28 at 4 56 47 PM" src="https://github.com/ploomber/jupysql/assets/29096135/ccfad48c-cb37-4f63-a5e1-155949bc98b2">

(I have repeated the steps by opening a clean notebook session and got the same set of errors)

**Comment by edublancas** [comment]
this isn't a bug per-se, but it'd be better if jupysql automatically performed the rollback.

we are already covering this for some PostgreSQL errors and we could handle this DuckDB edge case: https://github.com/ploomber/jupysql/blob/b538512dfda13be8acbd3df2ff29ad4c6523610d/src/sql/connection/connection.py#L836

**Comment by bbeat2782** [comment]
Acceptance Criteria
1. Ensure downloading and rerunning the select statement works as expected
2. Add a test case for duckdb

**Comment by bbeat2782** [comment]
https://github.com/ploomber/jupysql/assets/43221691/2ad72200-abd6-4d50-aeaa-3d36a5a5785f

I tried to replicate the error, but it works as expected on my local setting.
