### ISSUE TITLE
consolidate store_utils.py into store.py

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#843]
looks like we're having some issues when moving stuff around.

from @neelasha23:

```
yes when we add these functions in store.py the tests fail. In isolate_tests fixture the store is being cleared: store.store = store.SQLStore(). This is causing the store to become empty when running each test, although we are creating snippets again in the test.
I'm not sure exactly why this is happening but moving to a separate file solves the issue.
```

source: https://github.com/ploomber/jupysql/pull/787/files#r1305308401

@neelasha23 can you share the error that happens when we put everything into a single file?

**Comment by neelasha23** [comment]
We are creating some snippets in this [fixture](https://github.com/ploomber/jupysql/blob/02085858158714ad09e2cb521c1b57e87e423fca/src/tests/test_magic_cmd.py#L38). When all snippet util functions are put into `store.py` these snippets are not getting created.

These are the cases that fail:

<img width="824" alt="Screenshot 2023-08-29 at 1 02 46 PM" src="https://github.com/ploomber/jupysql/assets/29096135/b8ac167e-674d-4cd8-ac66-6b14c181f21d">

While debugging it seems the `get_all_keys()` is returning empty list:

<img width="447" alt="Screenshot 2023-08-29 at 1 03 30 PM" src="https://github.com/ploomber/jupysql/assets/29096135/180fef03-f95f-4a90-9a8c-741bccb28748">

**Comment by bbeat2782** [comment]
Acceptance Criteria
1. Move functions in store_utils.py to store.py
2. Ensure all test functions pass

I think this [PR](https://github.com/ploomber/jupysql/pull/837) fixes the problem. I ran it roughly and worked locally. Once that PR is merged, I will test it.
