### ISSUE TITLE
improvements to the `display.py` module

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#846]
we added a `display.py` module to centralize the way to show feedback to the user because we have to support two frontends: Jupyter (which supports displaying HTML) and the terminal (only supports plain text)

the `Message` class allows creating an object that correctly displays its value in HTML if it's running in Jupyter or in plain text if running in the terminal, and it allows adding an optional CSS style (which is only visible in Jupyter).

The limitation happens when we want to display a link in the message. this happens when we want to point users to certain sections in our docs: if we add the HTML link to a Message instance, it'll display correctly in Jupyter but it won't in the terminal.

We can do something like this:

```python
# to keep backward compatibility
Message("some plain text message")

# new API
Message(["go to our", Link("home", "https://ploomber.io"), "page"])
```

then, internally, the plain text representation can resolve to:

```
go to our home (https://ploomber.io) page
```

and the HTML one to:

```
go to our <a href="[url](https://ploomber.io)">home</a> page
```

**Comment by bbeat2782** [comment]
Acceptance Criteria
1. Modify code so that `Message` class takes both str and list of str as input and decides the form of text representation depending on jupyter notebook / terminal.
2. Ensure all previous test cases pass and add test function for testing `Message(["go to our", Link("home", "https://ploomber.io"), "page"])` this kind of input

**Comment by edublancas** [comment]
I forgot to mention something: let's update our developer docs as well, there is a section that talks about the display.py module so let's put some examples of this new API!

**Comment by bbeat2782** [comment]
Are you referring to this [part](https://jupysql.ploomber.io/en/latest/community/developer-guide.html#displaying-messages)?

**Comment by edublancas** [comment]
yes!
