### ISSUE TITLE
pyproject.toml vs connections.ini

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#850]
from a user:

> Could someone supply an example of a pyproject.toml file that connects to a remote postgresql database and how the connection  gets loaded correctly?  I've got it working using an ini file but the toml file equivalent has been a bust. No rush.

seems like there is some confusion between using a pyproject.toml vs a connections.ini, so we should ensure that the purpose of each is clear from the docs so users are not confused

**Comment by bbeat2782** [comment]
Acceptance Criteria
1. Make sure the purpose of pyproject.toml and connections.ini is clear in the doc
