### ISSUE TITLE
improvements to mutually exclusive arguments

### ISSUE THREAD

**Issue by neelasha23** [ploomber/jupysql#853]
There are some validations to check that arguments from mutually exclusive groups shouldn't be passed, e.g., `breaks` and `binwidth` in histogram plot:

https://github.com/ploomber/jupysql/blob/1a090c16e8029861324bf0f17027582152343db8/src/sql/util.py#L318

I think we can use the argparse mutual exclusion [feature](https://docs.python.org/3/library/argparse.html#mutual-exclusion) directly instead of writing custom functions.

**Comment by edublancas** [comment]
@bbeat2782 some thoughts: IPython uses argparse under the hood to provide argument validation to magics. however, it seems like they only expose a subset of the API so I'm unsure if we can use the mutually exclusive groups from argparse for the magics. so some investigation is needed

**Comment by bbeat2782** [comment]
Ad @edublancas noted, it seems like `parser.add_mutually_exclusive_group` isn't implemented in IPython magic arguments (IPython magic arguments [code](https://github.com/ipython/ipython/blob/main/IPython/core/magic_arguments.py#L309))

**Comment by edublancas** [comment]
ok, closing this
