### ISSUE TITLE
Can't denote DuckDB table with custom schema using %sqlplot

### ISSUE THREAD

**Issue by alexlmartin** [ploomber/jupysql#854]
I've not been able to execute %sqlplot referencing  a DuckDB table or view with a custom schema.

Ideally tables and views within a custom schemas could be referenced either automatically with schema_name.table_name syntax or with the addition of a --schema argument. (Or both)

Table with custom schema:
![image](https://github.com/ploomber/jupysql/assets/28570222/396bfcac-ea08-4ee4-843e-ac49cba3e34d)

**Comment by edublancas** [comment]
hey @bbeat2782 this is similar to the PR we just merged, essentially `--table  schema.table` should work, and `--table table --schema schema` as well

**Comment by bbeat2782** [comment]
Acceptance Criteria
1. Make sure `--table schema.table` and `--schema schema --table table` works for all plots in `%sqlplot`
2. Add test functions
