### ISSUE TITLE
improvements to CTE feature

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#87]
When creating CTEs, we have to carry all of them, it'd be better that the user only indicated one and we figure out the rest. Example:

```sql
%%sql --save positive_x
SELECT * FROM numbers
WHRE x > 0
````

```sql
%%sql --save positive_x_and_y --with positive_x
SELECT * FROM positive_x
WHRE y > 0
````

If I want to use `positive_x_and_y`, I need:

```sql
%%sql  --with positive_x_and_y --with positive_x
SELECT * FROM numbers
WHRE x > 0
````

But having `--with positive_x_and_y` should be enough, and JupySQL should figure out that it also needs `positive_x`

**Comment by tonykploomber** [comment]
Per my test, I think our current implementation already this support. If I don't misunderstand the description

```
my_data = pd.DataFrame(np.random.randint(-5,5,size=(100, 2)), columns=list('xy'))
%sql duckdb://
%sql --append my_data
```

<img width="120" alt="Screenshot 2023-02-16 at 6 07 05 PM" src="https://user-images.githubusercontent.com/123580782/219508460-6c9e98cc-69e2-4d21-acff-45af8156f23f.png">

`%sql --save positive_x SELECT * FROM my_data WHERE x > 0`
<img width="102" alt="Screenshot 2023-02-16 at 6 08 58 PM" src="https://user-images.githubusercontent.com/123580782/219508543-4d3008e0-13e3-4f48-ad61-4885a2015aff.png">

`%sql --save positive_x_and_y --with positive_x SELECT * FROM positive_x WHERE y > 0`
<img width="103" alt="Screenshot 2023-02-16 at 6 09 41 PM" src="https://user-images.githubusercontent.com/123580782/219508723-a77f6d4a-8de8-4707-b749-5ee37eb43acf.png">

Finally, looks okay from my side without carrying `--with positive_x`?
`%sql --with positive_x_and_y SELECT * FROM positive_x_and_y`
<img width="117" alt="Screenshot 2023-02-16 at 6 11 35 PM" src="https://user-images.githubusercontent.com/123580782/219508891-bd1d30ee-f179-4e7e-b292-052f9a499093.png">

**Comment by edublancas** [comment]
I think you're right. I opened this after encountering an issue while using jupysql but it looks like I did something wrong. I'll see if I can replicate it an update this or close it if I cannot

**Comment by edublancas** [comment]
I was able to replicate it. @tonykploomber can you add a unit test so we ensure this works? I couldn't find any

**Comment by tonykploomber** [comment]
[Test case added in here](https://github.com/ploomber/jupysql/issues/87)
