### ISSUE TITLE
Parentheses cause issue with CTE queries

### ISSUE THREAD

**Issue by nooodle-soup** [ploomber/jupysql#876]
### What happens?

Leading parentheses before CTE queries causes them to break

Acceptance Criteria:
Parentheses around queries should not affect the query itself

### To Reproduce

```
%sql sqlite://
```
```
%%sql
CREATE TABLE languages (name, rating, change);
INSERT INTO languages VALUES ('Python', 14.44, 2.48);
INSERT INTO languages VALUES ('C', 13.13, 1.50);
INSERT INTO languages VALUES ('Java', 11.59, 0.40);
INSERT INTO languages VALUES ('C++', 10.00, 1.98);
```
```
%%sql
(WITH langs as (
    select * from languages
) select * from langs)
```

### OS:

Linux

### JupySQL Version:

0.10.2dev

### Full Name:

Vineet Agarwal

### Affiliation:

Ploomber

**Comment by edublancas** [comment]
I'm not following why this is considered a bug. AFAIK, leading parenthesis are not valid in SQL CTEs. I just verified this:

```python
In [1]: import sqlite3

In [2]: conn=sqlite3.connect("")

In [3]: conn.execute("""CREATE TABLE languages (name, rating, change);""")
Out[3]: <sqlite3.Cursor at 0x103aa2440>

In [5]: conn.execute("""INSERT INTO languages VALUES ('Python', 14.44, 2.48);""")
Out[5]: <sqlite3.Cursor at 0x103b0e140>

In [6]: conn.execute("select * from languages").fetchall()
Out[6]: [('Python', 14.44, 2.48)]

In [7]: conn.execute("""(WITH langs as (
   ...:     select * from languages
   ...: ) select * from langs)""").fetchall()
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
Cell In[7], line 1
----> 1 conn.execute("""(WITH langs as (
      2     select * from languages
      3 ) select * from langs)""").fetchall()

OperationalError: near "(": syntax error

In [8]:
```

am I missing anything?

**Comment by nooodle-soup** [comment]
My bad. I did not look into that. In that case, we should not be storing the snippets that start with a parentheses right? We do not disallow that as of now.

**Comment by edublancas** [comment]
> we should not be storing the snippets that start with a parentheses right? We do not disallow that as of now.

can you provide more details? I'm unsure what you mean

**Comment by nooodle-soup** [comment]
If we pass the following to a cell, it will run but the contents of the run itself are empty.
```
%%sql --save my_penguins
(select * from penguins.csv)
```

Do we want to be allowing this to be saved as a snippet? Or should we not care about it as long as it is valid SQL syntax?

**Comment by nooodle-soup** [comment]
```
%%sql --save test
(WITH test as (
    select * from penguins.csv
)
select * from test)
```

Just checked this, the above gets saved into a snippet event though it is not a valid SQL CTE.

**Comment by edublancas** [comment]
> ```
> %%sql --save test
> (WITH test as (
>     select * from penguins.csv
> )
> select * from test)
> ```
> 
> Just checked this, the above gets saved into a snippet event though it is not a valid SQL CTE.

this is actually valid SQL CTE (at least in duckdb)

**Comment by nooodle-soup** [comment]
> please open a new issue so we discuss it there. we need to do more research because I don't know what the behavior of this sql query is in other sql engines (I only tested duckdb)

Will do!
