### ISSUE TITLE
Issue on page /integrations/mindsdb.html

### ISSUE THREAD

**Issue by RodolfoFerro** [ploomber/jupysql#88]
The displayed dataframe/table is too long and it escapes from the margins:
![2023-01-24 13 01 41](https://user-images.githubusercontent.com/8453749/214384615-e255f15f-aabb-48f8-80ed-3787545abdba.gif)

**Comment by edublancas** [comment]
this is an error with the sphinx theme we're using. I'll leave it open since we can patch it by changing the query and only displaying a few of the columns
