### ISSUE TITLE
adding SQL comments breaks jupysql

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#892]
From [Slack](https://ploomber-io.slack.com/archives/C028KJCJDRT/p1694819634024439): 

> Did something change with how jupysql handles SQL comments either before or after the %%sql command?  I used to have commented code beforehand which now just errors (fairly certain it didn't before).
If I have commented code one line below the %%sql I get a Success message but no query output (unless I have a something like: %%sql --with first_part --with second_part and then a comment line below.
Thx.

![image](https://github.com/ploomber/jupysql/assets/989250/af9ff504-2980-4f29-9db9-bb3e6cb29a08)

**Comment by edublancas** [comment]
hey @marshallwhiteorg: @neelasha23 fixed a similar problem in https://github.com/ploomber/jupysql/pull/894

she's now deleting comments before storing them as snippets. it might be a sensible approach for this problem, too. if there isn't a cleaner option. we might wanna remove comments before running the query.

**Comment by marshallwhiteorg** [comment]
@edublancas let me know if this is still relevant given that my code is now passing the checks
