### ISSUE TITLE
DuckDB 0.9.0 is breaking the CI

### ISSUE THREAD

**Issue by neelasha23** [ploomber/jupysql#897]
Reference: https://duckdb.org/2023/09/26/announcing-duckdb-090.html

**Comment by edublancas** [comment]
can you share the traceback?

**Comment by edublancas** [comment]
(re-opening this because pinning duckdb is a temporary solution, we want to test with 0.9.0)

**Comment by edublancas** [comment]
@marshallwhiteorg it might not be matplotlib what's breaking your PR, it might be duckdb. regardless, merging from main will fix it

**Comment by edublancas** [comment]
this has been fixed in https://github.com/ploomber/jupysql/pull/953
