### ISSUE TITLE
installation of jupysql-plugin with jupysql by default breaks jupyterlab 4 setups

### ISSUE THREAD

**Issue by flaviomartins** [ploomber/jupysql#900]
### What happens?

Maybe we should reconsider adding jupysql-plugin a hard requirement of jupysql. I need to use jupyterlab 4 with jupyterlab-lsp.

### To Reproduce

1. Upgrade to jupysql >10.1
2. jupysql-plugin installs even though jupyterlab<4 is violated
3. [Format SQL] button throws an error

### OS:

macOS

### JupySQL Version:

10.2

### Full Name:

Flavio Martins

### Affiliation:

Instituto Superior Técnico

**Comment by edublancas** [comment]
is jupysql-plugin breaking anything? (besides the "format SQL" not working on jupyterlab 4)

we're working on a jupysql-plugin update that will work with jupyterlab 4

**Comment by flaviomartins** [comment]
no, i think it is not breaking anything. thanks for replying so quickly.

@edublancas I also found the settings i needed to set to hide the Deploy and Format SQL buttons. I added a custom `jupysql-plugin/settings.jupyterlab-settings` to my docker image. It is hiding only for the active tab after a refresh. Although, this might be a bug related to JupyterLab 4.

**Comment by edublancas** [comment]
thanks for letting me know.

can you try reproducing the issue on jupyterlab 3? if it's a bug, we'll tackle it.

if you want to hide the buttons from the toolbar, you can also try uninstalling jupysql-plugin.

**Comment by edublancas** [comment]
jupysql-plugin 0.4.0 now works with JupyterLab 4. closing this now
