### ISSUE TITLE
jupysql + duckdb breaks if passing `:NUMBER`

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#901]
Jupysql thinks that `:NUMBER` is a parameter in the query, but duckdb uses this syntax for slicing strings (just like Python), we need to fix and escape it so it works just like when we're using duckdb (I think we're already escaping some parameters so we can use that code as a reference).

I can escape manually to get it working: 

![image](https://github.com/ploomber/jupysql/assets/989250/42d6825e-9e77-4756-bef7-5179c3fee365)

but we should do the escaping automatically

Notebook:

```python
import duckdb

conn = duckdb.connect()
```

```python
conn.execute("select 'hello'[:2]").fetchall()
```

    [('he',)]

```python
%load_ext sql
```

```python
%sql duckdb://
```

<span style="None">Connecting to &#x27;duckdb://&#x27;</span>

Set `named_parameters` to False (this is actual the default so shouldn't make a difference)

```python
%config SqlMagic.named_parameters=False
```

This breaks, jupysql thinks `[:2]` is a parameter:

```sql
%%sql
select 'hello'[:2]
```

<span style="None">Running query in &#x27;duckdb://&#x27;</span>

    RuntimeError: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter '2'
    [SQL: select 'hello'[?]]
    [parameters: [{}]]
    (Background on this error at: https://sqlalche.me/e/20/cd3x)
    If you need help solving this issue, send us a message: https://ploomber.io/community

**Comment by edublancas** [comment]
@bryannho what's the status here?

**Comment by bryannho** [comment]
> @bryannho what's the status here? 

Started working on this today, barring issues should be done by early next week
