### ISSUE TITLE
Ipython 8.16.0 is breaking the CI

### ISSUE THREAD

**Issue by neelasha23** [ploomber/jupysql#903]
Release notes: https://ipython.readthedocs.io/en/stable/whatsnew/version8.html

**Comment by edublancas** [comment]
do you have the traceback?

**Comment by neelasha23** [comment]
https://github.com/ploomber/jupysql/actions/runs/6350675691/job/17250770253

**Comment by edublancas** [comment]
ok, are we certain IPython is breaking it?

If so, please open a PR and let's pin IPython so we can fix this and an issue so we can dig up later

@nooodle-soup: this looks similar to what you encountered in your PR

**Comment by nooodle-soup** [comment]
I'll change the ipython version to check and give an update

**Comment by nooodle-soup** [comment]
There's a discrepancy in the jupysql setup.py and our integration tests.
The setup.py has [ipython<=8.12.0](https://github.com/ploomber/jupysql/blob/master/setup.py#L21) and the integration test uses the latest ipython verison ([check here](https://github.com/ploomber/jupysql/actions/runs/6350675691/job/17250770253#step:4:49))

**Comment by nooodle-soup** [comment]
I made a change ([here](https://github.com/ploomber/jupysql/pull/878/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R21)) to the setup file in my PR and the tests that were failing before are now passing.

**Comment by nooodle-soup** [comment]
I made a change ([here](https://github.com/ploomber/jupysql/pull/878/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R21)) to the setup file in my PR and the tests that were failing before are now passing.

Matplotlib tests in test_magic_plot are now failing instead

**Comment by nooodle-soup** [comment]
All the tests now pass when using `pkgmt==0.7.3` instead of the latest pkgmt. You can have a look [here](https://github.com/ploomber/jupysql/pull/878/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R40)

**Comment by nooodle-soup** [comment]
@edublancas @neelasha23  My tests just passed with the latest IPython version.

**Comment by neelasha23** [comment]
They might have fixed in yesterday's release !

**Comment by nooodle-soup** [comment]
Seems so!
