### ISSUE TITLE
Github Workflow for no-changelog PRs always fails in the first run

### ISSUE THREAD

**Issue by nooodle-soup** [ploomber/jupysql#906]
The current Github Workflow for CI checks for a changelog in the PR label. Github, however, does not allow adding labels to PRs while creating them as far as I know.Suggestion:

We could perhaps make a change that checks for something like `label:no-changelog` in the PR itself, adds the label to the PR and then continues with the CI process.

Maybe using `gh pr edit --add-label` ([reference](https://cli.github.com/manual/gh_pr_edit))Acceptance criteria:

A setup that does not require a second push for no-changelog CI workflows to work.

**Comment by edublancas** [comment]
before opening a PR, you can add labels:

![image](https://github.com/ploomber/jupysql/assets/989250/addb55fe-4ce2-48d5-af97-3096dbdc1837)

**Comment by nooodle-soup** [comment]
I do not see that option when creating a pull request from my forked repo
![image](https://github.com/ploomber/jupysql/assets/63967365/6ac49863-283b-417e-81d2-fb8b2c3bcfa0)

**Comment by edublancas** [comment]
I see.

I don't think this is a big problem because most of the PRs require changelog changes, and based on previous experience. I bet that if we implement this, most people will forget that the feature exists and end up adding the label and then triggering the CI.

**Comment by nooodle-soup** [comment]
Okay
I'll close this issue then!

**Comment by nooodle-soup** [comment]
@edublancas There is a way to make sure that the label is only used no-changelog is modified, if you feel that it is worth pursuing. That way no one would be able to add the no-changelog there is no change in the changelog.
We are currently only checking if the PR has a no-changelog label or not, instead of checking that the no-changelog label is only added when there is a change in the changelog. This means currently, every PR can have a no-changelog label and pass the tests, even when the changelog is modified.
