### ISSUE TITLE
Constant 1.5-2.5s delay for DuckDB queries

### ISSUE THREAD

**Issue by szarnyasg** [ploomber/jupysql#914]
### What happens?

I use JupySQL to run queries on an in-memory DuckDB. I noticed that the queries have a constant 1.5-2.5s delay in their execution, even when running something as simple as `SELECT 42`.

I tried both Jupyter notebooks and the CLI IPython. I rebooted my machine and reinstalled all related packages as follows but it made no difference:
```
$ pip freeze | grep jupy | xargs pip uninstall -y
$ pip freeze | grep duck | xargs pip uninstall -y
$ pip install jupysql duckdb-engine
```

Are there any reinstalls I should try or are there any commands I can run to give some diagnostics information?

### To Reproduce

My script is below. Unfortunately, I have no idea how to reproduce this on other machines. I asked someone to run the same script and it was fast as expected.

```
$ ipython
```
```
%reload_ext sql
%sql duckdb:///:memory:
```
```
%%time
%%sql
SELECT 42;
```
Output:
```text
Running query in 'duckdb:///:memory:'
CPU times: user 82.2 ms, sys: 16.8 ms, total: 99 ms
Wall time: 2.55 s
```

### OS:

macOS

### JupySQL Version:

0.10.2

### Full Name:

Gabor Szarnyas

### Affiliation:

DuckDB Labs

**Comment by edublancas** [comment]
Hi @szarnyasg, another user reported a similar issue a few months ago, but we could not reproduce it.

The solution was to turn off the [anonymous telemetry](https://jupysql.ploomber.io/en/latest/community/support.html):

```sh
export PLOOMBER_STATS_ENABLED=false
```

Let me know if that fixes it!

**Comment by szarnyasg** [comment]
Hi @edublancas, thanks for the quick response. Annoyingly, I am now also unable to reproduce it: the issue occurred to me while I was connected to hotel wifi while travelling. This would point towards something to do with network activities, and that certainly fits in to the telemetry theory. I'll keep this solution in mind if I encounter this issue in the future.
