### ISSUE TITLE
Adding some tests with major databases

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#92]
There are cases where we don't know if specific changes will break for some databases (e.g., https://github.com/ploomber/jupysql/pull/91), and we won't know until it happens to users, so we should add some integration tests that run against the major database: SQLite and DuckDB are the easy ones since they're embedded.

Postgres is also an easy one since we can add it as a service in our GitHub Action (we are doing this in ploomber/ploomber repository) –and I'd assume we can do the same for other open-source databases like MySQL.

We won't be able to cover all of them but this would be a good start.

**Comment by idomic** [comment]
I agree the main question for this is how do we validate the ones that require infras. Maybe we can keep it to V2.

**Comment by edublancas** [comment]
for the ones that require infra, yes, let's leave it for v2

**Comment by tonykploomber** [comment]
Hello @edublancas I am looking into this issue,

Do you mean we can follow this GitHub guide to [create PostgreSQL service](https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers) & write an Integration test script to run it?
> Postgres is also an easy one since we can add it as a service in our GitHub Action (we are doing this in ploomber/ploomber repository) –and I'd assume we can do the same for other open-source databases like MySQL.

Let's do it for PostgreSQL one and then do the MySQL later?

**Comment by idomic** [comment]
Both Mysql and Postgressql can run locally, if it can run locally we should do it in a single PR.
Yeah the goal is to have integration tests as part of the CI.

**Comment by tonykploomber** [comment]
@idomic 
Gotcha! Good chance for me to play around with CI/CD workflow

**Comment by edublancas** [comment]
github has support for adding a postgres database, we already do that in ploomber: https://github.com/ploomber/ploomber/blob/2a6287f1beea9f51ecbe59ddebac266cef6c77e8/.github/workflows/ci-unit-linux.yml#L20

we need to look if there's something similar for mysql/mariadb.


the next question (which I don't have an answer for yet) is. In the CI: do we run *all* our tests with *all* databases? or only a subset of the tests?

at least locally, I think tests should only run with SQLite and duckdb, since expecting a local postgres/other will complicate setup too mucg.

**Comment by idomic** [comment]
I think those should be a different set of tests.
Unit tests are already running fine with local DBs.

The integration tests can be a sanity check of a few or our most used APIs on all of those DBs. We can see how much time it adds to the CI and we can improve it on a need-based.

So probably `%sql/%%sql/%sqlplot/%sqlrender` and maybe some python APIs.

**Comment by tonykploomber** [comment]
Per discussion with Eduardo:
1. Create an Issue to collect the database version from user-side in telemetry
2. (Plan in follow-up task) Add matrix in CI to test over different database versions. Abstract the basic test cases for a different database endpoint

**Comment by edublancas** [comment]
> Create an Issue to collect the database version from user-side in telemetry

please open a different issue so we tackle it in another PR

> (Plan in follow-up task) Add matrix in CI to test over different database versions. Abstract the basic test cases framework for covering different database endpoints

same, let's merge this with one Python version and one db version, then in a new issue we can discuss extensions (testing many database versions)

---

regarding the consolidation of our tests so we only write a test once and run it with it with multiple databases, what we want is to use fixtures as test parameters, [here's how to do it](https://miguendes.me/how-to-use-fixtures-as-arguments-in-pytestmarkparametrize). the post proposes two solutions, one that requires no extra packages and another one that does, let's try with the one that requires no extra packages first
