### ISSUE TITLE
Boxplot not using ax parameter

### ISSUE THREAD

**Issue by neelasha23** [ploomber/jupysql#923]
The function for boxplot doesn't use the `ax` parameter and creates a new axes object by running `plt.gca()`. We need to add a condition `if ax is None`

https://github.com/ploomber/jupysql/blob/d71584f639abb9417f8c63bdc1f84d9c67abed58/src/sql/plot.py#L239

**Comment by edublancas** [comment]
is this blocking the solara chat app?

**Comment by neelasha23** [comment]
yes. i think this is the issue that's causing blank plots. Since now we need to pass the `ax` object. we cant use the one generated by pyplot
