### ISSUE TITLE
adding parametrized queries

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#93]
many people are already familiar with parametrized queries since they're available in dbt and airflow, so we should add that. possibly with jinja? 

```sql
%%sql --params {"corpus_name": "hamlet", "limit": 10}
SELECT word, SUM(word_count) as count
FROM `bigquery-public-data.samples.shakespeare`
WHERE corpus = {{corpus_name}}
GROUP BY word
ORDER BY count DESC
LIMIT {{limit}}
```

This is how [BigQuery](https://cloud.google.com/python/docs/reference/bigquery/latest/magics) does it (but with a different syntax).

I'm unsure if the `--params {"corpus_name": "hamlet", "limit": 10}` if the best choice. perhaps something simpler like `-p corpus_name hamlet -p limit 10`? similar to what we do in [ploomber-engine](https://ploomber-engine.readthedocs.io/en/latest/user-guide/running.html#parametrizing-notebooks)

**Comment by idomic** [comment]
I like this.
I think that it should be inline vs passing everything under a flag?
It can be from variables in the notebooks for v1, I think I already saw a similar solution somewhere.

**Comment by edublancas** [comment]
> I think that it should be inline vs passing everything under a flag?

you mean something like this?

```python
limit = 10
corpus_name = "something"
```

```
%%sql 
SELECT word, SUM(word_count) as count
FROM `bigquery-public-data.samples.shakespeare`
WHERE corpus = {{corpus_name}}
GROUP BY word
ORDER BY count DESC
LIMIT {{limit}}
```

**Comment by idomic** [comment]
Exactly.

**Comment by edublancas** [comment]
cool, I'd say there should be two mode. one where the user explicitly says "go grab my global scope" and another one where they pass parameters explicitly.

Here, we grab existing limit and corpus_name from existing scope (shorter version: `%%sql -u`):

```
%%sql --use-globals
SELECT word, SUM(word_count) as count
FROM `bigquery-public-data.samples.shakespeare`
WHERE corpus = {{corpus_name}}
GROUP BY word
ORDER BY count DESC
LIMIT {{limit}}
```

here, we pass values explicitly:

```
%%sql  -p limit 1 -p corpus_name stuff
SELECT word, SUM(word_count) as count
FROM `bigquery-public-data.samples.shakespeare`
WHERE corpus = {{corpus_name}}
GROUP BY word
ORDER BY count DESC
LIMIT {{limit}}
```

Mixing them will use the existing scope and override any passed values:

```
%%sql  -p limit 1 --use-globals
SELECT word, SUM(word_count) as count
FROM `bigquery-public-data.samples.shakespeare`
WHERE corpus = {{corpus_name}}
GROUP BY word
ORDER BY count DESC
LIMIT {{limit}}
```

thoughts?

**Comment by idomic** [comment]
We can do this mix, I don't see why we need `--use-globals` though.

**Comment by edublancas** [comment]
> We can do this mix, I don't see why we need --use-globals though.

**Comment by edublancas** [comment]
>  We can do this mix, I don't see why we need --use-globals though.

following the [zen of python](https://peps.python.org/pep-0020/#the-zen-of-python) 😁: Explicit is better than implicit.

**Comment by idomic** [comment]
lol sure.
Let's gather more feedback.

**Comment by edublancas** [comment]
and, we could even combine it with the `--save` feature:

```sql
%%sql --save some_name --no-execute
SELECT word, SUM(word_count) as count
FROM `bigquery-public-data.samples.shakespeare`
WHERE corpus = {{corpus_name}}
GROUP BY word
ORDER BY count DESC
LIMIT {{limit}}
```

Then:

```
%sql -p limit 10 -p corpus_name one
```

```
%sql -p limit 100 -p corpus_name another
```

**Comment by idomic** [comment]
That could be one example for the docs, `some_name` should probably be `some_query`

**Comment by edublancas** [comment]
> That could be one example for the docs, some_name should probably be some_query.

agree

> Probably the no-execute will always be on in that scenario.

unless you use `--use-globals`

**Comment by tonykploomber** [comment]
@edublancas 

For the --params, the abbreviation `-p` is conflict with our current `--persist`
```
-p / --persist Create a table name in the database from the named DataFrame ([example](https://jupysql.ploomber.io/en/latest/api/magic-sql.html#create-table))
```

**Comment by edublancas** [comment]
let's use capital p: -P

**Comment by tonykploomber** [comment]
Let's think about if we want to keep this
Since: https://jupysql.ploomber.io/en/latest/intro.html?highlight=variable#variable-substitution

**Comment by edublancas** [comment]
I looked at the existing behavior: it needs to be more consistent (see [here](https://jupysql--140.org.readthedocs.build/en/140/user-guide/templating.html#issue-inconsistent-behavior)) and support some  new features. So let's go ahead and implement it with jinja2.Template.

I think the current implementation is happening here: https://github.com/ploomber/jupysql/blob/27823e65a216db36fa0c9dbd1b381a4501f5765d/src/sql/run.py#L393

so we need to:

- [ ] deprecate the existing implementation  (see note below)
- [ ] implement with jinja2
- [ ] ensure we can re-render snippets when we change a parameter value in a snippet with the `--with` option (see [here](https://jupysql--140.org.readthedocs.build/en/140/user-guide/templating.html#issue-once-the-statement-is-rendered-the-values-won-t-change))

what's interesting about the existing implementation is that the original author decided to pass the user's namespace implicitly, so I think let's do it that way; once that's in, we can decide if we add the `--use-globals` and `--parameter` options.

example of the new api:

```python
parameter = "value"
```

```sql
%%sql
select * from table where parameter = '{{parameter}}'
```

should resolve to:

```sql
select * from table where parameter = '{{value}}'
```

## deprecation

I think we should keep the existing behavior for a bit to allow users to migrate.

I think we can detect queries with the existing behavior with some regex that looks for :something $something or {something}, and if so, show  a warning so they use {{something}} (and show our slack link so they can ask for help)

**Comment by tonykploomber** [comment]
I think the original way they parsed the variable was happening earlier before our execution function:

```
# Suppose we execute following calls in notebook:
test_x = 3
%sql SELECT * FROM my_data limit $test_x

```
In the [def execution function](https://github.com/ploomber/jupysql/blob/master/src/sql/magic.py#L195), where our main sql execute handler 

```
    def execute(self, line="", cell="", local_ns={}):
        # skip
        print ("line: ", line)
        # print -> SELECT * FROM my_data limit 3
        command = SQLCommand(self, user_ns, line, cell)
        # args.line: contains the line after the magic with all options removed
        args = command.args
```

After some researches I think Ipython already parsed the line string with `:variable` or `{variable}`
 
## Deprecation

Probably we need to find the way to control that parsing part (either throwing some warning message, or disable the `:variable` or `{variable}` in the future)

## Add Double Curly Bracelets parsing support

In current codebase, if we execute something like:

```
test_x = 3
SELECT * FROM my_data limit '{test_x}'
```
It will become
```
    def execute(self, line="", cell="", local_ns={}):
        # skip
        print ("line: ", line)
        # print -> SELECT * FROM my_data limit '{test_x}'
        command = SQLCommand(self, user_ns, line, cell)
        # args.line: contains the line after the magic with all options removed
        args = command.args
```

We can still parse the `SELECT * FROM my_data limit '{test_x}'` to
`SELECT * FROM my_data limit 3` to fulfill the feature, but I am not sure if this is a good approach since the Ipython already has the logic to handle the parsing part natively, the best approach is we can see & control the original parsing logic in Ipython then modify to our way

**Comment by tonykploomber** [comment]
Update 2/22/23:

## Design Proposal

There is a decorator called [@no_var_expand](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.magic.html#IPython.core.magic.no_var_expand) which can be attached to `def execute(self, line="", cell="", local_ns={}):` function

After the var expand is turned off by our hand, we can write our custom parsers to handle the variable by ourself. There will be two cases:

1. Neither `--use-globals` and `--parameter` is provided, which means we should still provide the legacy variable usage. We use our custom parser (A) to handle `${variable}` & `:variable` in line or cell string
2. Either `--use-globals` and `--parameter` is provided, we use our custom parser (B) to handle `{{variable}}` in line or cell string

Custom parser A: only handle the `${variable}` & `:variable` case, we might reuse the [var_expand func](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.interactiveshell.html#IPython.core.interactiveshell.InteractiveShell.var_expand) in Ipython
Custom parser B: only handle the `{{variable}}` case, we can just use jinja2 template.render function to parse the string

Finally, I think when user provides something like `${variable}` & `:variable` meanwhile with `--use-globals` and `--parameter`, like `%sql --use-global SELECT * FROM my_table limit ${my_limit}`, this mixin usage should not be allowed in this design

@edublancas Kinda complicate...but lmk what you think

**Comment by idomic** [comment]
For both 1 & 2, we can add the feature, support it for the required minimum version and deprecate it in the next major, as per our deprecation policy. I think if there are no major design issues/concerns we should move to talk over an actual PR.

**Comment by tonykploomber** [comment]
@edublancas 
Sounds good to me now!
