### ISSUE TITLE
jupysql conda recipe is broken

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql#936]
we haven't been able to make a new conda release for jupysql because conda requires all dependencies to be available in conda. since jupysql-plugin is now a hard dependency, we need to add it to conda as well:

https://github.com/conda-forge/jupysql-feedstock/pull/22#issuecomment-1795341601

**Comment by neelasha23** [comment]
I do not have push rights to the `jupysql-feedstock` repo. Please add me as mainatiner? @edublancas

**Comment by edublancas** [comment]
added you here: https://github.com/conda-forge/jupysql-feedstock/blob/main/recipe/meta.yaml

is there anything else I need to do?

**Comment by neelasha23** [comment]
Yes [this PR](https://github.com/ploomber/jupysql/pull/966) needs to merged only then I can update the `sqlglot` version in the recipe @edublancas

**Comment by edublancas** [comment]
triggered a new release, should be up on PyPI in a few minutes: https://github.com/ploomber/jupysql/actions/runs/7290388000

and the PR from the conda bot should be also opened automatically

**Comment by edublancas** [comment]
@neelasha23, please be more vigilant about these things, I've just realized that the bot never opened the PR: https://github.com/conda-forge/jupysql-feedstock/commits/main/ - looks like we manually need to create a new one

**Comment by edublancas** [comment]
@neelasha23 merged the conda recipe! it should be up on conda-forge in ~1 hour, please do some quick tests and let me know if it all works as expected.

**Comment by neelasha23** [comment]
The plugin features are working :

<img width="664" alt="Screenshot 2024-01-04 at 10 11 06 AM" src="https://github.com/ploomber/jupysql/assets/29096135/46f50725-c819-44be-9cee-66c26eb0e928">

<img width="998" alt="Screenshot 2024-01-04 at 10 08 05 AM" src="https://github.com/ploomber/jupysql/assets/29096135/9d75b8b7-bf48-4bed-8a77-1b79d8d3269e">

<img width="588" alt="Screenshot 2024-01-04 at 10 05 06 AM" src="https://github.com/ploomber/jupysql/assets/29096135/de6bb382-9e7e-4b38-887f-7a8d87e702d5">

But there's some issue in loading the extension (in jupyterlab as well) :

```

In [1]: %load_ext sql
The sql module is not an IPython extension.
```

Looking into it

@edublancas

**Comment by edublancas** [comment]
I just installed from conda and verified that loading the extension works. great work!

closing this now
