### ISSUE TITLE
Change the url for the docs

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#96]
We need to switch the docs to serve from our domain:
`https://jupysql.readthedocs.io/en/latest/quick-start.html` to  `https://jupysql.ploomber.io/en/latest/quick-start.html`

**Comment by idomic** [comment]
Done

**Comment by edublancas** [comment]
i think let's keep it open since we need to update references in the docs and the blog?

the old ones will still work but it's better to switch

**Comment by idomic** [comment]
Alright.

Now the story is about replacing the base URL (instead of having redirects).
