### ISSUE TITLE
Interested in Spark SQL support via spark connect?

### ISSUE THREAD

**Issue by gilandose** [ploomber/jupysql#965]
Now that there is a thin client for spark: Spark Connect, I've forked your library and been able to add in basic Spark support fairly easily. For now to avoid computation I've directly outputted the Dataframe, as this avoids unnecessary computation. If there would be interest in merging this back to your main, I can work on integrating with the `ResultSet`.

Open to suggestions, but for now this is working really well for me, in terms of providing all the great features like composable CTEs and syntax highlighting, with lazy eval, but still validating the sql against spark, inc schema as it goes.

https://github.com/gilcloud/jupysql

**Comment by edublancas** [comment]
hey @gilandose, this looks good. feel free to open a PR!

I looked at the code and one change I'd suggest is to make the `pyspark` package optional. In one of the files, there's a top import like this `from pyspark.sql import SparkSession` which will break if users don't have pyspark.

other than that, it looks good!
