### ISSUE TITLE
A value is required for bind parameter 'fruit' (snowflake)

### ISSUE THREAD

**Issue by tekumara** [ploomber/jupysql#972]
### What happens?

The snowflake query `select parse_json('{"fruit":"banana"}'):fruit`  errors with:
```
RuntimeError: (Your query contains named parameters (fruit) but the named parameters feature is disabled. Enable it with: %config SqlMagic.named_parameters=True)
(sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'fruit'
[SQL: select parse_json('{"fruit":"banana"}')%(fruit)s]
```

Despite being valid snowflake sql. The `:` is [GET_PATH](https://docs.snowflake.com/en/sql-reference/functions/get_path) 

### To Reproduce

```python
from snowflake.sqlalchemy import URL
from sqlalchemy import create_engine

url = URL(
    user=...
    account=...
)

engine = create_engine(url)

%reload_ext sql

%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False
%config SqlMagic.autopandas = True

%sql select parse_json('{"fruit":"banana"}'):fruit
```

### OS:

macos

### JupySQL Version:

0.10.7

### Full Name:

Oliver Mannion

### Affiliation:

Xero

**Comment by edublancas** [comment]
thanks for reporting this, I think to fix it we need to introduce a way to completely disable named parameters so this doesn't cause issues
