### ISSUE TITLE
Proposal: add flake8 into git pre-commit

### ISSUE THREAD

**Issue by tonykploomber** [ploomber/jupysql#98]
Context:
Every time the developer has to manually run `flake8` locally to see if it's any lint issue, we should integrate that part into our git pre-commit setup, so everytime the developer invokes `git commit`, it will run the flake8 check as well.

We can add the constraint that all commits have to be passed flake8 locally, before pushing to the remote git repository

**Comment by tonykploomber** [comment]
Ref: https://flake8.pycqa.org/en/latest/user/using-hooks.html

**Comment by edublancas** [comment]
we have this already, check this out: https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#coding
