### ISSUE TITLE
Pandas 2.2.0 failing the CI

### ISSUE THREAD

**Issue by neelasha23** [ploomber/jupysql#983]
`Pandas` 2.2.0 (latest release) is incompatible with `SqlAlchemy` v1. 
Failing CI: https://github.com/ploomber/jupysql/actions/runs/7595386596/job/20687893281

**Comment by edublancas** [comment]
I think https://github.com/ploomber/jupysql/pull/982 solves this, right?

**Comment by neelasha23** [comment]
It solves for the time being but we still need to support the latest pandas version for sqlalchemy v1 ?

**Comment by edublancas** [comment]
based on the [release notes](https://pandas.pydata.org/pandas-docs/version/2.2.0/whatsnew/v2.2.0.html#increased-minimum-versions-for-dependencies), pandas no longer supports sqlalchemy 1.x, I'll close this and open a new issue describing the solution
