### ISSUE TITLE
Incomplete examples for `sqlstore`, `%%sql --save` and `%sqlrender`

### ISSUE THREAD

**Issue by idomic** [ploomber/jupysql#99]
We need to add the dummy data to those examples so it's easier to follow.

Adding some sample data would be useful. We can add some "create table" and "insert into" statements at the beginning to show to it works. This is the source: https://github.com/ploomber/jupysql/blob/master/doc/api/magic-render.md (edited)

**Comment by edublancas** [comment]
we've deprecated %sqlrender so this is no longer applicable. we also updated the documentation to better reflect how to use `--save`
